import { useQuery } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { Landmark, RefreshCw, ShieldCheck } from "lucide-react";
import { Navigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { FormDialog } from "@/components/ui/form-dialog";
import { msg } from "@/lib/i18n";
import { useSession } from "@/modules/identity";
import * as api from "./api";
import "./loan.css";

const money = (v: number) => `${new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(v / 100)} ISK`;
const loanState = (v: string) => ({ submitted: msg("待审核"), approved: msg("待放款"), active: msg("还款中"), settled: msg("已结清"), rejected: msg("已驳回"), cancelled: msg("已取消"), defaulted: msg("已逾期") }[v] ?? v);

export default function LoanPage() {
  const session = useSession();
  if (session.isError) return <p role="alert">{session.error.message}</p>;
  if (!session.data) return <p role="status">{msg("正在读取")}</p>;
  if (!session.data.session) return <Navigate to="/login" replace />;
  return <Workspace csrf={session.data.session.csrf_token} />;
}

function Workspace({ csrf }: { csrf: string }) {
  const [principal, setPrincipal] = useState(""); const [interest, setInterest] = useState(""); const [character, setCharacter] = useState(""); const [count, setCount] = useState("1"); const [interval, setInterval] = useState("30"); const [due, setDue] = useState(""); const [message, setMessage] = useState(""); const [applicationOpen, setApplicationOpen] = useState(false); const [applicationBusy, setApplicationBusy] = useState(false);
  const [contributionKind, setContributionKind] = useState<"personal" | "corporation">("personal"); const [contributionCharacter, setContributionCharacter] = useState(""); const [contributionCorporation, setContributionCorporation] = useState(""); const [contributionAmount, setContributionAmount] = useState(""); const [contributionMessage, setContributionMessage] = useState(""); const [contributionOpen, setContributionOpen] = useState(false); const [contributionBusy, setContributionBusy] = useState(false);
  const [creditScore, setCreditScore] = useState(""); const [creditTotal, setCreditTotal] = useState(""); const [creditUnsecured, setCreditUnsecured] = useState(""); const [creditRule, setCreditRule] = useState("manual-v1"); const [creditReason, setCreditReason] = useState(""); const [creditMessage, setCreditMessage] = useState(""); const [creditOpen, setCreditOpen] = useState(false); const [creditBusy, setCreditBusy] = useState(false);
  const context = useQuery({ queryKey: ["loan", "context"], queryFn: ({ signal }) => api.context(signal), staleTime: 30_000 });
  const list = useQuery({ queryKey: ["loan", "cases"], queryFn: ({ signal }) => api.cases(signal), staleTime: 15_000 });
  const contributions = useQuery({ queryKey: ["loan", "contributions"], queryFn: ({ signal }) => api.contributions(signal), staleTime: 15_000 });
  const refresh = () => void Promise.all([context.refetch(), list.refetch(), contributions.refetch()]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(""); const sharedPool = pools[0]; if (!sharedPool) { setMessage(msg("统一贷款池暂不可用")); return; } setApplicationBusy(true); try { await api.createApplication(csrf, { pool_id: Number(sharedPool.id), borrower_character_id: Number(character), principal_minor: Math.round(Number(principal) * 100), interest_minor: Math.round(Number(interest || 0) * 100), installment_count: Number(count), interval_days: Number(interval), first_due_at: new Date(due).toISOString() }); setMessage(""); setApplicationOpen(false); await Promise.all([context.refetch(), list.refetch()]); } catch (e) { setMessage(e instanceof Error ? e.message : msg("贷款申请失败")); } finally { setApplicationBusy(false); } };
  const contribute = async (event: FormEvent) => { event.preventDefault(); setContributionMessage(""); setContributionBusy(true); try { await api.createContribution(csrf, { lender_kind: contributionKind, source_character_id: Number(contributionCharacter), corporation_id: contributionKind === "corporation" ? Number(contributionCorporation) : 0, amount_minor: Math.round(Number(contributionAmount) * 100) }); setContributionMessage(msg("出借额度已提交，请完成入金合同")); setContributionAmount(""); setContributionOpen(false); await Promise.all([contributions.refetch(), context.refetch()]); } catch (e) { setContributionMessage(e instanceof Error ? e.message : msg("出借额度提交失败")); } finally { setContributionBusy(false); } };
  const saveCredit = async (event: FormEvent) => { event.preventDefault(); setCreditMessage(""); setCreditBusy(true); const account = context.data?.credit.account_id ?? ""; try { await api.setCredit(csrf, account, { score: creditScore ? Number(creditScore) : null, total_limit_minor: Math.round(Number(creditTotal) * 100), unsecured_limit_minor: Math.round(Number(creditUnsecured) * 100), state: "active", rule_version: creditRule, reason: creditReason, version: context.data?.credit.version ?? 1 }); setCreditMessage(msg("信用额度已保存")); setCreditOpen(false); await context.refetch(); } catch (e) { setCreditMessage(e instanceof Error ? e.message : msg("信用额度保存失败")); } finally { setCreditBusy(false); } };
  if (context.isError || list.isError || contributions.isError) return <div className="loan-feedback" role="alert"><p>{(context.error ?? list.error ?? contributions.error)?.message}</p><Button variant="outline" onClick={refresh}>{msg("重试")}</Button></div>;
  const pools = context.data?.pools.filter((p) => p.state === "open") ?? []; const summary = context.data?.pool_summary;
  return <div className="loan-page"><header className="loan-heading"><div className="loan-title"><span className="loan-mark"><Landmark aria-hidden="true" /></span><div><h1>{msg("贷款")}</h1><p>{msg("统一资金池：成员可提交出借额度，完成合同入金后供借款使用")}</p></div></div><Button variant="outline" disabled={context.isFetching || list.isFetching || contributions.isFetching} onClick={refresh}><RefreshCw size={16} aria-hidden="true" />{msg("刷新")}</Button></header>
    {context.data?.administrator && <section className="loan-admin"><div className="loan-section-head"><div><h2>{msg("信用审批配置")}</h2><p>{msg("统一贷款池固定为全站单池，管理员只维护借款人的评分和额度。")}</p></div><Button variant="outline" onClick={() => { setCreditMessage(""); setCreditOpen(true); }}>{msg("配置授信")}</Button></div>{creditMessage && !creditOpen && <p className="loan-form-message" role="status">{creditMessage}</p>}{creditOpen && <FormDialog title={msg("配置当前账号信用")} close={() => { if (!creditBusy) setCreditOpen(false); }} busy={creditBusy} submitLabel={msg("保存信用额度")} disabled={!context.data?.credit.account_id} className="loan-form loan-credit-form" onSubmit={saveCredit}><label>{msg("信用评分")}<input autoFocus value={creditScore} onChange={(e) => setCreditScore(e.target.value)} inputMode="numeric" placeholder="0–100" /></label><label>{msg("总额度（ISK）")}<input value={creditTotal} onChange={(e) => setCreditTotal(e.target.value)} inputMode="decimal" required /></label><label>{msg("无担保额度（ISK）")}<input value={creditUnsecured} onChange={(e) => setCreditUnsecured(e.target.value)} inputMode="decimal" required /></label><label>{msg("规则版本")}<input value={creditRule} onChange={(e) => setCreditRule(e.target.value)} required /></label><label>{msg("评分说明")}<input value={creditReason} onChange={(e) => setCreditReason(e.target.value)} /></label>{creditMessage && <p className="loan-form-message" role="alert">{creditMessage}</p>}</FormDialog>}</section>}
    {summary && <section className="loan-credit"><div><span>{msg("待核验入金")}</span><strong>{money(summary.pending_minor)}</strong></div><div><span>{msg("已入池资金")}</span><strong>{money(summary.cash_minor)}</strong></div><div><span>{msg("可放贷余额")}</span><strong>{money(summary.available_minor)}</strong></div></section>}
    {context.data?.credit.state !== "active" && <div className="loan-notice" role="status"><ShieldCheck size={18} aria-hidden="true" /><span>{msg("信用额度尚未配置，审批前需要管理员完成评分和授信。")}</span></div>}
    <section className="loan-apply loan-contribution-entry"><div className="loan-section-head"><div><h2>{msg("提交出借额度")}</h2><p>{msg("出借方先提交额度，再创建转入统一托管方的 ISK 合同；完成核验后才计入可放贷余额。")}</p></div><Button onClick={() => { setContributionMessage(""); setContributionOpen(true); }} disabled={pools.length === 0}>{msg("开始出借")}</Button></div>{contributionMessage && !contributionOpen && <p className="loan-form-message" role="status">{contributionMessage}</p>}{contributionOpen && <FormDialog title={msg("提交出借额度")} close={() => { if (!contributionBusy) setContributionOpen(false); }} busy={contributionBusy} submitLabel={msg("提交出借额度")} disabled={pools.length === 0} className="loan-form loan-contribution-form" onSubmit={contribute}><label>{msg("出借类型")}<select autoFocus value={contributionKind} onChange={(e) => setContributionKind(e.target.value as "personal" | "corporation")}><option value="personal">{msg("个人")}</option><option value="corporation">{msg("军团")}</option></select></label><label>{msg("出借角色 ID")}<input value={contributionCharacter} onChange={(e) => setContributionCharacter(e.target.value)} inputMode="numeric" required /></label>{contributionKind === "corporation" && <label>{msg("出借军团 ID")}<input value={contributionCorporation} onChange={(e) => setContributionCorporation(e.target.value)} inputMode="numeric" required /></label>}<label>{msg("出借额度（ISK）")}<input value={contributionAmount} onChange={(e) => setContributionAmount(e.target.value)} inputMode="decimal" required /></label>{contributionMessage && <p className="loan-form-message" role="alert">{contributionMessage}</p>}</FormDialog>}</section>
    {(contributions.data?.items.length ?? 0) > 0 && <section className="loan-list"><div className="loan-section-head"><h2>{msg("出借记录")}</h2></div><div className="loan-contributions">{contributions.data?.items.map((item) => <ContributionRow key={item.id} csrf={csrf} item={item} onDone={() => void Promise.all([contributions.refetch(), context.refetch()])} />)}</div></section>}
    <section className="loan-apply loan-application-entry"><div className="loan-section-head"><div><h2>{msg("提交贷款申请")}</h2><p>{msg("固定总利息按期等额分期，所有申请自动进入全站唯一贷款池。")}</p></div><Button onClick={() => { setMessage(""); setApplicationOpen(true); }} disabled={context.isPending || pools.length === 0}>{msg("开始申请")}</Button></div>{message && <p className="loan-form-message" role="alert">{message}</p>}{applicationOpen && <FormDialog title={msg("提交贷款申请")} close={() => { if (!applicationBusy) setApplicationOpen(false); }} busy={applicationBusy} submitLabel={msg("提交申请")} disabled={pools.length === 0} className="loan-form loan-application-form" onSubmit={submit}><p className="loan-dialog-note">{msg("申请会自动进入全站唯一贷款池，提交后等待评分、额度、担保或抵押审批。")}</p><label>{msg("收款角色 ID")}<input autoFocus value={character} onChange={(e) => setCharacter(e.target.value)} inputMode="numeric" required /></label><label>{msg("本金（ISK）")}<input value={principal} onChange={(e) => setPrincipal(e.target.value)} inputMode="decimal" required /></label><label>{msg("总利息（ISK）")}<input value={interest} onChange={(e) => setInterest(e.target.value)} inputMode="decimal" required /></label><label>{msg("期数")}<input value={count} onChange={(e) => setCount(e.target.value)} inputMode="numeric" required /></label><label>{msg("间隔天数")}<input value={interval} onChange={(e) => setInterval(e.target.value)} inputMode="numeric" required /></label><label>{msg("首期到期时间")}<input type="datetime-local" value={due} onChange={(e) => setDue(e.target.value)} required /></label>{message && <p className="loan-form-message" role="alert">{message}</p>}</FormDialog>}</section>
    <section className="loan-list"><div className="loan-section-head"><h2>{msg("我的贷款")}</h2></div>{list.isPending ? <p role="status">{msg("正在读取")}</p> : list.data?.items.length ? <div className="loan-table-wrap"><table><thead><tr><th>{msg("编号")}</th><th>{msg("贷款池")}</th><th>{msg("本金")}</th><th>{msg("总应还")}</th><th>{msg("状态")}</th></tr></thead><tbody>{list.data.items.map((item) => <tr key={item.id}><td>{item.public_id}</td><td>{item.pool_name}</td><td>{money(item.principal_minor)}</td><td>{money(item.total_due_minor)}</td><td><span className={`loan-state loan-state-${item.state}`}>{loanState(item.state)}</span></td></tr>)}</tbody></table></div> : <div className="loan-empty"><Landmark size={28} aria-hidden="true" /><p>{msg("暂无贷款记录")}</p></div>}</section>
  </div>;
}

function ContributionRow({ csrf, item, onDone }: { csrf: string; item: api.Contribution; onDone: () => void }) {
  const [kind, setKind] = useState<"character" | "corporation">("character"); const [owner, setOwner] = useState(""); const [contract, setContract] = useState(""); const [message, setMessage] = useState("");
  const deposit = async (event: FormEvent) => { event.preventDefault(); setMessage(""); try { await api.depositContribution(csrf, item.id, { version: item.version, contract_kind: kind, contract_owner_id: Number(owner), contract_id: Number(contract) }); onDone(); } catch (e) { setMessage(e instanceof Error ? e.message : msg("入金合同核验失败")); } };
  const cancel = async () => { setMessage(""); try { await api.cancelContribution(csrf, item.id, { version: item.version }); onDone(); } catch (e) { setMessage(e instanceof Error ? e.message : msg("出借额度取消失败")); } };
  return <article className="loan-contribution"><div><strong>{money(item.amount_minor)}</strong><span>{item.lender_kind === "corporation" ? msg("军团出借") : msg("个人出借")} · {item.state === "funded" ? msg("已入池") : item.state === "pending" ? msg("待入金核验") : msg("已取消")}</span></div>{item.state === "pending" && <form className="loan-form" onSubmit={deposit}><label>{msg("合同类型")}<select value={kind} onChange={(e) => setKind(e.target.value as "character" | "corporation")}><option value="character">{msg("个人角色")}</option><option value="corporation">{msg("军团")}</option></select></label><label>{msg("合同所有者 ID")}<input value={owner} onChange={(e) => setOwner(e.target.value)} inputMode="numeric" required /></label><label>{msg("合同 ID")}<input value={contract} onChange={(e) => setContract(e.target.value)} inputMode="numeric" required /></label><div className="loan-form-actions"><Button type="submit">{msg("核验入金合同")}</Button><Button type="button" variant="outline" onClick={() => void cancel()}>{msg("取消")}</Button>{message && <span role="status">{message}</span>}</div></form>}{item.state !== "pending" && message && <span role="status">{message}</span>}</article>;
}
