// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO access_assignments(user_id,role_id) VALUES($1,$2) ON CONFLICT DO NOTHING
`

type AssignRoleParams struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.RoleID)
	return err
}

const audit = `-- name: Audit :exec
INSERT INTO access_audit(actor,action,subject) VALUES($1,$2,$3)
`

type AuditParams struct {
	Actor   string
	Action  string
	Subject string
}

func (q *Queries) Audit(ctx context.Context, arg AuditParams) error {
	_, err := q.db.Exec(ctx, audit, arg.Actor, arg.Action, arg.Subject)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO access_roles(id,name,grants) VALUES($1,$2,$3) ON CONFLICT(id) DO NOTHING RETURNING id, name, grants, updated_at, version
`

type CreateRoleParams struct {
	ID     pgtype.UUID
	Name   string
	Grants []byte
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (AccessRole, error) {
	row := q.db.QueryRow(ctx, createRole, arg.ID, arg.Name, arg.Grants)
	var i AccessRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grants,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM access_roles WHERE id=$1 AND version=$2
`

type DeleteRoleParams struct {
	ID      pgtype.UUID
	Version int64
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isAdministrator = `-- name: IsAdministrator :one
SELECT EXISTS(SELECT 1 FROM access_administrators WHERE user_id=$1)
`

func (q *Queries) IsAdministrator(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAdministrator, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, actor, action, subject, created_at FROM access_audit WHERE id < $1 ORDER BY id DESC LIMIT 51
`

func (q *Queries) ListAudit(ctx context.Context, id int64) ([]AccessAudit, error) {
	rows, err := q.db.Query(ctx, listAudit, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessAudit{}
	for rows.Next() {
		var i AccessAudit
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.Subject,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, grants, updated_at, version FROM access_roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]AccessRole, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessRole{}
	for rows.Next() {
		var i AccessRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grants,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAdministrator = `-- name: RemoveAdministrator :exec
DELETE FROM access_administrators WHERE user_id=$1
`

func (q *Queries) RemoveAdministrator(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeAdministrator, userID)
	return err
}

const setAdministrator = `-- name: SetAdministrator :exec
INSERT INTO access_administrators(user_id) VALUES($1) ON CONFLICT DO NOTHING
`

func (q *Queries) SetAdministrator(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setAdministrator, userID)
	return err
}

const unassignRole = `-- name: UnassignRole :exec
DELETE FROM access_assignments WHERE user_id=$1 AND role_id=$2
`

type UnassignRoleParams struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}

func (q *Queries) UnassignRole(ctx context.Context, arg UnassignRoleParams) error {
	_, err := q.db.Exec(ctx, unassignRole, arg.UserID, arg.RoleID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE access_roles SET name=$2,grants=$3,version=version+1,updated_at=now()
WHERE id=$1 AND version=$4 RETURNING id, name, grants, updated_at, version
`

type UpdateRoleParams struct {
	ID      pgtype.UUID
	Name    string
	Grants  []byte
	Version int64
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (AccessRole, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Grants,
		arg.Version,
	)
	var i AccessRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grants,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const userRoles = `-- name: UserRoles :many
SELECT r.id, r.name, r.grants, r.updated_at, r.version FROM access_roles r JOIN access_assignments a ON a.role_id=r.id WHERE a.user_id=$1 ORDER BY r.name
`

func (q *Queries) UserRoles(ctx context.Context, userID pgtype.UUID) ([]AccessRole, error) {
	rows, err := q.db.Query(ctx, userRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessRole{}
	for rows.Next() {
		var i AccessRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grants,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
