// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessAudit struct {
	ID        int64
	Actor     string
	Action    string
	Subject   string
	CreatedAt pgtype.Timestamptz
}

type AccessRole struct {
	ID        pgtype.UUID
	Name      string
	Grants    []byte
	UpdatedAt pgtype.Timestamptz
	Version   int64
}
