// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExchangeCoinLedger struct {
	ID                int64
	AccountID         pgtype.UUID
	Kind              string
	Reference         string
	RequestKey        pgtype.UUID
	Delta             int64
	Reason            string
	CreatedAt         pgtype.Timestamptz
	OriginalAccountID pgtype.UUID
}

type ExchangeRedemption struct {
	ID                  int64
	AccountID           pgtype.UUID
	RequestKey          pgtype.UUID
	Fingerprint         string
	RewardID            int64
	TypeID              int64
	Quantity            int32
	RecipientID         int64
	RecipientName       string
	IskPerCoin          int64
	IskValue            int64
	CoinsMinor          int64
	State               string
	Version             int64
	CreatedAt           pgtype.Timestamptz
	DecidedAt           pgtype.Timestamptz
	DecidedBy           pgtype.UUID
	Note                string
	OriginalAccountID   pgtype.UUID
	RewardName          string
	RewardContent       []byte
	CatalogVersion      int64
	SettlementReference string
}

type ExchangeReward struct {
	ID             int64
	TypeID         int64
	Quantity       int32
	IskValue       int64
	Stock          int32
	Enabled        bool
	Version        int64
	Name           string
	Content        []byte
	CatalogVersion int64
	Archived       bool
}

type ExchangeShopAudit struct {
	ID          int64
	ActorID     pgtype.UUID
	RequestKey  pgtype.UUID
	Kind        string
	TargetID    int64
	Fingerprint string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
}

type ExchangeShopSetting struct {
	Singleton  bool
	IskPerCoin int64
	Version    int64
}

type ExchangeSourceAward struct {
	SourceID          string
	Reference         string
	AccountID         pgtype.UUID
	Units             int64
	MinorPerUnit      int64
	Coins             int64
	OriginalAccountID pgtype.UUID
}

type ExchangeSourceRate struct {
	SourceID       string
	MinorPerUnit   int64
	Version        int64
	ConversionMode string
}
