// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rewards.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeRewardStock = `-- name: ChangeRewardStock :exec
UPDATE exchange_rewards SET stock=stock+$2::integer,version=version+1 WHERE id=$1
`

type ChangeRewardStockParams struct {
	ID    int64
	Delta int32
}

func (q *Queries) ChangeRewardStock(ctx context.Context, arg ChangeRewardStockParams) error {
	_, err := q.db.Exec(ctx, changeRewardStock, arg.ID, arg.Delta)
	return err
}

const createRedemption = `-- name: CreateRedemption :one
INSERT INTO exchange_redemptions(account_id,request_key,fingerprint,reward_id,type_id,quantity,recipient_id,recipient_name,isk_per_coin,isk_value,coins_minor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id, account_id, request_key, fingerprint, reward_id, type_id, quantity, recipient_id, recipient_name, isk_per_coin, isk_value, coins_minor, state, version, created_at, decided_at, decided_by, note, original_account_id, reward_name, reward_content, catalog_version, settlement_reference
`

type CreateRedemptionParams struct {
	AccountID     pgtype.UUID
	RequestKey    pgtype.UUID
	Fingerprint   string
	RewardID      int64
	TypeID        int64
	Quantity      int32
	RecipientID   int64
	RecipientName string
	IskPerCoin    int64
	IskValue      int64
	CoinsMinor    int64
}

func (q *Queries) CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (ExchangeRedemption, error) {
	row := q.db.QueryRow(ctx, createRedemption,
		arg.AccountID,
		arg.RequestKey,
		arg.Fingerprint,
		arg.RewardID,
		arg.TypeID,
		arg.Quantity,
		arg.RecipientID,
		arg.RecipientName,
		arg.IskPerCoin,
		arg.IskValue,
		arg.CoinsMinor,
	)
	var i ExchangeRedemption
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestKey,
		&i.Fingerprint,
		&i.RewardID,
		&i.TypeID,
		&i.Quantity,
		&i.RecipientID,
		&i.RecipientName,
		&i.IskPerCoin,
		&i.IskValue,
		&i.CoinsMinor,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.Note,
		&i.OriginalAccountID,
		&i.RewardName,
		&i.RewardContent,
		&i.CatalogVersion,
		&i.SettlementReference,
	)
	return i, err
}

const decideRedemption = `-- name: DecideRedemption :exec
UPDATE exchange_redemptions SET state=$2,note=$3,decided_by=$4,decided_at=now(),version=version+1 WHERE id=$1
`

type DecideRedemptionParams struct {
	ID        int64
	State     string
	Note      string
	DecidedBy pgtype.UUID
}

func (q *Queries) DecideRedemption(ctx context.Context, arg DecideRedemptionParams) error {
	_, err := q.db.Exec(ctx, decideRedemption,
		arg.ID,
		arg.State,
		arg.Note,
		arg.DecidedBy,
	)
	return err
}

const findRedemption = `-- name: FindRedemption :one
SELECT id, account_id, request_key, fingerprint, reward_id, type_id, quantity, recipient_id, recipient_name, isk_per_coin, isk_value, coins_minor, state, version, created_at, decided_at, decided_by, note, original_account_id, reward_name, reward_content, catalog_version, settlement_reference FROM exchange_redemptions WHERE account_id=$1 AND request_key=$2
`

type FindRedemptionParams struct {
	AccountID  pgtype.UUID
	RequestKey pgtype.UUID
}

func (q *Queries) FindRedemption(ctx context.Context, arg FindRedemptionParams) (ExchangeRedemption, error) {
	row := q.db.QueryRow(ctx, findRedemption, arg.AccountID, arg.RequestKey)
	var i ExchangeRedemption
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestKey,
		&i.Fingerprint,
		&i.RewardID,
		&i.TypeID,
		&i.Quantity,
		&i.RecipientID,
		&i.RecipientName,
		&i.IskPerCoin,
		&i.IskValue,
		&i.CoinsMinor,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.Note,
		&i.OriginalAccountID,
		&i.RewardName,
		&i.RewardContent,
		&i.CatalogVersion,
		&i.SettlementReference,
	)
	return i, err
}

const findShopAudit = `-- name: FindShopAudit :one
SELECT id, actor_id, request_key, kind, target_id, fingerprint, payload, created_at FROM exchange_shop_audit WHERE actor_id=$1 AND request_key=$2
`

type FindShopAuditParams struct {
	ActorID    pgtype.UUID
	RequestKey pgtype.UUID
}

func (q *Queries) FindShopAudit(ctx context.Context, arg FindShopAuditParams) (ExchangeShopAudit, error) {
	row := q.db.QueryRow(ctx, findShopAudit, arg.ActorID, arg.RequestKey)
	var i ExchangeShopAudit
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.RequestKey,
		&i.Kind,
		&i.TargetID,
		&i.Fingerprint,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listRedemptions = `-- name: ListRedemptions :many
SELECT id, account_id, request_key, fingerprint, reward_id, type_id, quantity, recipient_id, recipient_name, isk_per_coin, isk_value, coins_minor, state, version, created_at, decided_at, decided_by, note, original_account_id, reward_name, reward_content, catalog_version, settlement_reference FROM exchange_redemptions WHERE id<$1 AND ($2::boolean OR account_id=$3::uuid) ORDER BY id DESC LIMIT 31
`

type ListRedemptionsParams struct {
	BeforeID  int64
	Admin     bool
	AccountID pgtype.UUID
}

func (q *Queries) ListRedemptions(ctx context.Context, arg ListRedemptionsParams) ([]ExchangeRedemption, error) {
	rows, err := q.db.Query(ctx, listRedemptions, arg.BeforeID, arg.Admin, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRedemption{}
	for rows.Next() {
		var i ExchangeRedemption
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RequestKey,
			&i.Fingerprint,
			&i.RewardID,
			&i.TypeID,
			&i.Quantity,
			&i.RecipientID,
			&i.RecipientName,
			&i.IskPerCoin,
			&i.IskValue,
			&i.CoinsMinor,
			&i.State,
			&i.Version,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.Note,
			&i.OriginalAccountID,
			&i.RewardName,
			&i.RewardContent,
			&i.CatalogVersion,
			&i.SettlementReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRewards = `-- name: ListRewards :many
SELECT id, type_id, quantity, isk_value, stock, enabled, version, name, content, catalog_version, archived FROM exchange_rewards WHERE NOT archived AND id>$1 AND (enabled OR $2::boolean) ORDER BY id LIMIT 31
`

type ListRewardsParams struct {
	AfterID int64
	Admin   bool
}

func (q *Queries) ListRewards(ctx context.Context, arg ListRewardsParams) ([]ExchangeReward, error) {
	rows, err := q.db.Query(ctx, listRewards, arg.AfterID, arg.Admin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeReward{}
	for rows.Next() {
		var i ExchangeReward
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Quantity,
			&i.IskValue,
			&i.Stock,
			&i.Enabled,
			&i.Version,
			&i.Name,
			&i.Content,
			&i.CatalogVersion,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccount = `-- name: LockAccount :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,740026))
`

func (q *Queries) LockAccount(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, lockAccount, accountID)
	return err
}

const lockRedemption = `-- name: LockRedemption :one
SELECT id, account_id, request_key, fingerprint, reward_id, type_id, quantity, recipient_id, recipient_name, isk_per_coin, isk_value, coins_minor, state, version, created_at, decided_at, decided_by, note, original_account_id, reward_name, reward_content, catalog_version, settlement_reference FROM exchange_redemptions WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockRedemption(ctx context.Context, id int64) (ExchangeRedemption, error) {
	row := q.db.QueryRow(ctx, lockRedemption, id)
	var i ExchangeRedemption
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestKey,
		&i.Fingerprint,
		&i.RewardID,
		&i.TypeID,
		&i.Quantity,
		&i.RecipientID,
		&i.RecipientName,
		&i.IskPerCoin,
		&i.IskValue,
		&i.CoinsMinor,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.Note,
		&i.OriginalAccountID,
		&i.RewardName,
		&i.RewardContent,
		&i.CatalogVersion,
		&i.SettlementReference,
	)
	return i, err
}

const lockReward = `-- name: LockReward :one
SELECT id, type_id, quantity, isk_value, stock, enabled, version, name, content, catalog_version, archived FROM exchange_rewards WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockReward(ctx context.Context, id int64) (ExchangeReward, error) {
	row := q.db.QueryRow(ctx, lockReward, id)
	var i ExchangeReward
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Quantity,
		&i.IskValue,
		&i.Stock,
		&i.Enabled,
		&i.Version,
		&i.Name,
		&i.Content,
		&i.CatalogVersion,
		&i.Archived,
	)
	return i, err
}

const lockShopSettings = `-- name: LockShopSettings :one
SELECT singleton, isk_per_coin, version FROM exchange_shop_settings WHERE singleton FOR UPDATE
`

func (q *Queries) LockShopSettings(ctx context.Context) (ExchangeShopSetting, error) {
	row := q.db.QueryRow(ctx, lockShopSettings)
	var i ExchangeShopSetting
	err := row.Scan(&i.Singleton, &i.IskPerCoin, &i.Version)
	return i, err
}

const redemption = `-- name: Redemption :one
SELECT id, account_id, request_key, fingerprint, reward_id, type_id, quantity, recipient_id, recipient_name, isk_per_coin, isk_value, coins_minor, state, version, created_at, decided_at, decided_by, note, original_account_id, reward_name, reward_content, catalog_version, settlement_reference FROM exchange_redemptions WHERE id=$1
`

func (q *Queries) Redemption(ctx context.Context, id int64) (ExchangeRedemption, error) {
	row := q.db.QueryRow(ctx, redemption, id)
	var i ExchangeRedemption
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestKey,
		&i.Fingerprint,
		&i.RewardID,
		&i.TypeID,
		&i.Quantity,
		&i.RecipientID,
		&i.RecipientName,
		&i.IskPerCoin,
		&i.IskValue,
		&i.CoinsMinor,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.Note,
		&i.OriginalAccountID,
		&i.RewardName,
		&i.RewardContent,
		&i.CatalogVersion,
		&i.SettlementReference,
	)
	return i, err
}

const saveReward = `-- name: SaveReward :one
INSERT INTO exchange_rewards(type_id,quantity,isk_value,stock,enabled) VALUES($1,$2,$3,$4,$5) RETURNING id, type_id, quantity, isk_value, stock, enabled, version, name, content, catalog_version, archived
`

type SaveRewardParams struct {
	TypeID   int64
	Quantity int32
	IskValue int64
	Stock    int32
	Enabled  bool
}

func (q *Queries) SaveReward(ctx context.Context, arg SaveRewardParams) (ExchangeReward, error) {
	row := q.db.QueryRow(ctx, saveReward,
		arg.TypeID,
		arg.Quantity,
		arg.IskValue,
		arg.Stock,
		arg.Enabled,
	)
	var i ExchangeReward
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Quantity,
		&i.IskValue,
		&i.Stock,
		&i.Enabled,
		&i.Version,
		&i.Name,
		&i.Content,
		&i.CatalogVersion,
		&i.Archived,
	)
	return i, err
}

const setShopRate = `-- name: SetShopRate :exec
UPDATE exchange_shop_settings SET isk_per_coin=$1,version=version+1 WHERE singleton
`

func (q *Queries) SetShopRate(ctx context.Context, iskPerCoin int64) error {
	_, err := q.db.Exec(ctx, setShopRate, iskPerCoin)
	return err
}

const shareShopSettings = `-- name: ShareShopSettings :one
SELECT singleton, isk_per_coin, version FROM exchange_shop_settings WHERE singleton FOR SHARE
`

func (q *Queries) ShareShopSettings(ctx context.Context) (ExchangeShopSetting, error) {
	row := q.db.QueryRow(ctx, shareShopSettings)
	var i ExchangeShopSetting
	err := row.Scan(&i.Singleton, &i.IskPerCoin, &i.Version)
	return i, err
}

const shopAudit = `-- name: ShopAudit :exec
INSERT INTO exchange_shop_audit(actor_id,request_key,kind,target_id,fingerprint,payload) VALUES($1,$2,$3,$4,$5,$6)
`

type ShopAuditParams struct {
	ActorID     pgtype.UUID
	RequestKey  pgtype.UUID
	Kind        string
	TargetID    int64
	Fingerprint string
	Payload     []byte
}

func (q *Queries) ShopAudit(ctx context.Context, arg ShopAuditParams) error {
	_, err := q.db.Exec(ctx, shopAudit,
		arg.ActorID,
		arg.RequestKey,
		arg.Kind,
		arg.TargetID,
		arg.Fingerprint,
		arg.Payload,
	)
	return err
}

const shopBalance = `-- name: ShopBalance :one
SELECT coalesce((SELECT sum(a.delta) FROM exchange_coin_ledger a WHERE a.account_id=$1::uuid AND a.kind='source'),0)::bigint AS earned,
coalesce((SELECT sum(r.coins_minor) FROM exchange_redemptions r WHERE r.account_id=$1::uuid AND r.state IN ('pending','cancel_requested')),0)::bigint +
coalesce((SELECT sum(g.reserved_minor-g.settled_minor-g.released_minor) FROM exchange_alert_grants g WHERE g.account_id=$1::uuid AND g.state='active'),0)::bigint AS reserved,
coalesce((SELECT sum(r.coins_minor) FROM exchange_redemptions r WHERE r.account_id=$1::uuid AND r.state='fulfilled'),0)::bigint +
coalesce((SELECT sum(c.coins_minor) FROM exchange_alert_charges c WHERE c.account_id=$1::uuid AND c.state='settled'),0)::bigint AS spent
`

type ShopBalanceRow struct {
	Earned   int64
	Reserved int64
	Spent    int64
}

func (q *Queries) ShopBalance(ctx context.Context, accountID pgtype.UUID) (ShopBalanceRow, error) {
	row := q.db.QueryRow(ctx, shopBalance, accountID)
	var i ShopBalanceRow
	err := row.Scan(&i.Earned, &i.Reserved, &i.Spent)
	return i, err
}

const shopSettings = `-- name: ShopSettings :one
SELECT singleton, isk_per_coin, version FROM exchange_shop_settings WHERE singleton
`

func (q *Queries) ShopSettings(ctx context.Context) (ExchangeShopSetting, error) {
	row := q.db.QueryRow(ctx, shopSettings)
	var i ExchangeShopSetting
	err := row.Scan(&i.Singleton, &i.IskPerCoin, &i.Version)
	return i, err
}

const updateReward = `-- name: UpdateReward :one
UPDATE exchange_rewards SET type_id=$2,quantity=$3,isk_value=$4,stock=$5,enabled=$6,version=version+1 WHERE id=$1 RETURNING id, type_id, quantity, isk_value, stock, enabled, version, name, content, catalog_version, archived
`

type UpdateRewardParams struct {
	ID       int64
	TypeID   int64
	Quantity int32
	IskValue int64
	Stock    int32
	Enabled  bool
}

func (q *Queries) UpdateReward(ctx context.Context, arg UpdateRewardParams) (ExchangeReward, error) {
	row := q.db.QueryRow(ctx, updateReward,
		arg.ID,
		arg.TypeID,
		arg.Quantity,
		arg.IskValue,
		arg.Stock,
		arg.Enabled,
	)
	var i ExchangeReward
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Quantity,
		&i.IskValue,
		&i.Stock,
		&i.Enabled,
		&i.Version,
		&i.Name,
		&i.Content,
		&i.CatalogVersion,
		&i.Archived,
	)
	return i, err
}
