// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const coinEntry = `-- name: CoinEntry :exec
INSERT INTO exchange_coin_ledger(account_id,kind,reference,request_key,delta,reason) VALUES($1,$2,$3,$4,$5,$6)
`

type CoinEntryParams struct {
	AccountID  pgtype.UUID
	Kind       string
	Reference  string
	RequestKey pgtype.UUID
	Delta      int64
	Reason     string
}

func (q *Queries) CoinEntry(ctx context.Context, arg CoinEntryParams) error {
	_, err := q.db.Exec(ctx, coinEntry,
		arg.AccountID,
		arg.Kind,
		arg.Reference,
		arg.RequestKey,
		arg.Delta,
		arg.Reason,
	)
	return err
}

const coinHistory = `-- name: CoinHistory :many
SELECT id, account_id, kind, reference, request_key, delta, reason, created_at, original_account_id FROM exchange_coin_ledger WHERE account_id=$1 AND id<$2 ORDER BY id DESC LIMIT 31
`

type CoinHistoryParams struct {
	AccountID pgtype.UUID
	BeforeID  int64
}

func (q *Queries) CoinHistory(ctx context.Context, arg CoinHistoryParams) ([]ExchangeCoinLedger, error) {
	rows, err := q.db.Query(ctx, coinHistory, arg.AccountID, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeCoinLedger{}
	for rows.Next() {
		var i ExchangeCoinLedger
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.Reference,
			&i.RequestKey,
			&i.Delta,
			&i.Reason,
			&i.CreatedAt,
			&i.OriginalAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSourceRate = `-- name: LockSourceRate :one
SELECT source_id, minor_per_unit, version, conversion_mode FROM exchange_source_rates WHERE source_id=$1 FOR UPDATE
`

func (q *Queries) LockSourceRate(ctx context.Context, sourceID string) (ExchangeSourceRate, error) {
	row := q.db.QueryRow(ctx, lockSourceRate, sourceID)
	var i ExchangeSourceRate
	err := row.Scan(
		&i.SourceID,
		&i.MinorPerUnit,
		&i.Version,
		&i.ConversionMode,
	)
	return i, err
}

const saveSourceAward = `-- name: SaveSourceAward :exec
INSERT INTO exchange_source_awards(source_id,reference,account_id,units,minor_per_unit,coins) VALUES($1,$2,$3,$4,$5,$6)
ON CONFLICT(source_id,reference) DO UPDATE SET units=excluded.units,minor_per_unit=excluded.minor_per_unit,coins=excluded.coins
`

type SaveSourceAwardParams struct {
	SourceID     string
	Reference    string
	AccountID    pgtype.UUID
	Units        int64
	MinorPerUnit int64
	Coins        int64
}

func (q *Queries) SaveSourceAward(ctx context.Context, arg SaveSourceAwardParams) error {
	_, err := q.db.Exec(ctx, saveSourceAward,
		arg.SourceID,
		arg.Reference,
		arg.AccountID,
		arg.Units,
		arg.MinorPerUnit,
		arg.Coins,
	)
	return err
}

const setSourceRate = `-- name: SetSourceRate :exec
UPDATE exchange_source_rates SET minor_per_unit=$2,conversion_mode=$3,version=version+1 WHERE source_id=$1
`

type SetSourceRateParams struct {
	SourceID       string
	MinorPerUnit   int64
	ConversionMode string
}

func (q *Queries) SetSourceRate(ctx context.Context, arg SetSourceRateParams) error {
	_, err := q.db.Exec(ctx, setSourceRate, arg.SourceID, arg.MinorPerUnit, arg.ConversionMode)
	return err
}

const shareSourceRate = `-- name: ShareSourceRate :one
SELECT source_id, minor_per_unit, version, conversion_mode FROM exchange_source_rates WHERE source_id=$1 FOR SHARE
`

func (q *Queries) ShareSourceRate(ctx context.Context, sourceID string) (ExchangeSourceRate, error) {
	row := q.db.QueryRow(ctx, shareSourceRate, sourceID)
	var i ExchangeSourceRate
	err := row.Scan(
		&i.SourceID,
		&i.MinorPerUnit,
		&i.Version,
		&i.ConversionMode,
	)
	return i, err
}

const sourceAward = `-- name: SourceAward :one
SELECT source_id, reference, account_id, units, minor_per_unit, coins, original_account_id FROM exchange_source_awards WHERE source_id=$1 AND reference=$2 FOR UPDATE
`

type SourceAwardParams struct {
	SourceID  string
	Reference string
}

func (q *Queries) SourceAward(ctx context.Context, arg SourceAwardParams) (ExchangeSourceAward, error) {
	row := q.db.QueryRow(ctx, sourceAward, arg.SourceID, arg.Reference)
	var i ExchangeSourceAward
	err := row.Scan(
		&i.SourceID,
		&i.Reference,
		&i.AccountID,
		&i.Units,
		&i.MinorPerUnit,
		&i.Coins,
		&i.OriginalAccountID,
	)
	return i, err
}

const sourceRates = `-- name: SourceRates :many
SELECT source_id, minor_per_unit, version, conversion_mode FROM exchange_source_rates ORDER BY source_id
`

func (q *Queries) SourceRates(ctx context.Context) ([]ExchangeSourceRate, error) {
	rows, err := q.db.Query(ctx, sourceRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeSourceRate{}
	for rows.Next() {
		var i ExchangeSourceRate
		if err := rows.Scan(
			&i.SourceID,
			&i.MinorPerUnit,
			&i.Version,
			&i.ConversionMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
