// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeCharacters = `-- name: ActiveCharacters :many
SELECT character_id,owner_hash,name FROM identity_characters WHERE user_id=$1 AND status='active' ORDER BY character_id
`

type ActiveCharactersRow struct {
	CharacterID int64
	OwnerHash   []byte
	Name        string
}

func (q *Queries) ActiveCharacters(ctx context.Context, userID pgtype.UUID) ([]ActiveCharactersRow, error) {
	rows, err := q.db.Query(ctx, activeCharacters, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveCharactersRow{}
	for rows.Next() {
		var i ActiveCharactersRow
		if err := rows.Scan(&i.CharacterID, &i.OwnerHash, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const blockCharacter = `-- name: BlockCharacter :exec
UPDATE identity_characters SET status = 'blocked' WHERE character_id = $1
`

func (q *Queries) BlockCharacter(ctx context.Context, characterID int64) error {
	_, err := q.db.Exec(ctx, blockCharacter, characterID)
	return err
}

const boundCharacters = `-- name: BoundCharacters :many
SELECT character_id,user_id,name,owner_hash FROM identity_characters WHERE character_id=ANY($1::bigint[]) AND status='active' ORDER BY character_id
`

type BoundCharactersRow struct {
	CharacterID int64
	UserID      pgtype.UUID
	Name        string
	OwnerHash   []byte
}

func (q *Queries) BoundCharacters(ctx context.Context, dollar_1 []int64) ([]BoundCharactersRow, error) {
	rows, err := q.db.Query(ctx, boundCharacters, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoundCharactersRow{}
	for rows.Next() {
		var i BoundCharactersRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.UserID,
			&i.Name,
			&i.OwnerHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const characterEvent = `-- name: CharacterEvent :exec
INSERT INTO identity_character_events(user_id,character_id,action) VALUES($1,$2,$3)
`

type CharacterEventParams struct {
	UserID      pgtype.UUID
	CharacterID int64
	Action      string
}

func (q *Queries) CharacterEvent(ctx context.Context, arg CharacterEventParams) error {
	_, err := q.db.Exec(ctx, characterEvent, arg.UserID, arg.CharacterID, arg.Action)
	return err
}

const createCharacter = `-- name: CreateCharacter :exec
INSERT INTO identity_characters (character_id, user_id, name, owner_hash) VALUES ($1, $2, $3, $4)
`

type CreateCharacterParams struct {
	CharacterID int64
	UserID      pgtype.UUID
	Name        string
	OwnerHash   []byte
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) error {
	_, err := q.db.Exec(ctx, createCharacter,
		arg.CharacterID,
		arg.UserID,
		arg.Name,
		arg.OwnerHash,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO identity_users DEFAULT VALUES RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM identity_characters WHERE character_id=$1 AND user_id=$2
`

type DeleteCharacterParams struct {
	CharacterID int64
	UserID      pgtype.UUID
}

func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) error {
	_, err := q.db.Exec(ctx, deleteCharacter, arg.CharacterID, arg.UserID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM identity_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT character_id, user_id, name, owner_hash, status, verified_at FROM identity_characters WHERE character_id = $1 FOR UPDATE
`

func (q *Queries) GetCharacter(ctx context.Context, characterID int64) (IdentityCharacter, error) {
	row := q.db.QueryRow(ctx, getCharacter, characterID)
	var i IdentityCharacter
	err := row.Scan(
		&i.CharacterID,
		&i.UserID,
		&i.Name,
		&i.OwnerHash,
		&i.Status,
		&i.VerifiedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.user_id, c.character_id, c.name, s.csrf_token, s.expires_at, m.character_id AS main_id, m.name AS main_name
FROM identity_sessions s JOIN identity_characters c ON c.character_id = s.character_id AND c.user_id = s.user_id
JOIN identity_users u ON u.id=s.user_id
JOIN identity_characters m ON m.character_id=u.main_character_id AND m.user_id=u.id
WHERE s.token_hash = $1 AND s.expires_at > now() AND c.status = 'active'
`

type GetSessionRow struct {
	UserID      pgtype.UUID
	CharacterID int64
	Name        string
	CsrfToken   string
	ExpiresAt   pgtype.Timestamptz
	MainID      int64
	MainName    string
}

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.UserID,
		&i.CharacterID,
		&i.Name,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.MainID,
		&i.MainName,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO identity_sessions (token_hash, user_id, character_id, csrf_token, expires_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertSessionParams struct {
	TokenHash   []byte
	UserID      pgtype.UUID
	CharacterID int64
	CsrfToken   string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.TokenHash,
		arg.UserID,
		arg.CharacterID,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	return err
}

const limitUserSessions = `-- name: LimitUserSessions :exec
DELETE FROM identity_sessions WHERE token_hash IN (
  SELECT s.token_hash FROM identity_sessions s WHERE s.user_id = $1 ORDER BY s.created_at DESC, s.token_hash OFFSET 4
)
`

func (q *Queries) LimitUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, limitUserSessions, userID)
	return err
}

const listCharacters = `-- name: ListCharacters :many
SELECT c.character_id,c.name,c.status,(c.character_id=u.main_character_id)::boolean AS is_main
FROM identity_characters c JOIN identity_users u ON u.id=c.user_id
WHERE c.user_id=$1 ORDER BY (c.character_id=u.main_character_id) DESC,c.name,c.character_id
`

type ListCharactersRow struct {
	CharacterID int64
	Name        string
	Status      string
	IsMain      bool
}

func (q *Queries) ListCharacters(ctx context.Context, userID pgtype.UUID) ([]ListCharactersRow, error) {
	rows, err := q.db.Query(ctx, listCharacters, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCharactersRow{}
	for rows.Next() {
		var i ListCharactersRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Name,
			&i.Status,
			&i.IsMain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSession = `-- name: LockSession :one
SELECT s.user_id, s.character_id FROM identity_sessions s
JOIN identity_characters c ON c.character_id=s.character_id AND c.user_id=s.user_id
WHERE s.token_hash=$1 AND s.expires_at>now() AND c.status='active' FOR UPDATE OF s
`

type LockSessionRow struct {
	UserID      pgtype.UUID
	CharacterID int64
}

func (q *Queries) LockSession(ctx context.Context, tokenHash []byte) (LockSessionRow, error) {
	row := q.db.QueryRow(ctx, lockSession, tokenHash)
	var i LockSessionRow
	err := row.Scan(&i.UserID, &i.CharacterID)
	return i, err
}

const lockUser = `-- name: LockUser :one
SELECT id, created_at, main_character_id FROM identity_users WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id pgtype.UUID) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i IdentityUser
	err := row.Scan(&i.ID, &i.CreatedAt, &i.MainCharacterID)
	return i, err
}

const pruneSessions = `-- name: PruneSessions :exec
DELETE FROM identity_sessions WHERE token_hash IN (
  SELECT token_hash FROM identity_sessions WHERE expires_at <= now() LIMIT 1000
)
`

func (q *Queries) PruneSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneSessions)
	return err
}

const revokeCharacterSessions = `-- name: RevokeCharacterSessions :exec
DELETE FROM identity_sessions WHERE character_id = $1
`

func (q *Queries) RevokeCharacterSessions(ctx context.Context, characterID int64) error {
	_, err := q.db.Exec(ctx, revokeCharacterSessions, characterID)
	return err
}

const searchMembers = `-- name: SearchMembers :many
SELECT u.id, m.character_id, m.name,
 (SELECT count(*) FROM identity_characters c WHERE c.user_id=u.id)::int AS character_count
FROM identity_users u JOIN identity_characters m ON m.user_id=u.id AND m.character_id=u.main_character_id
WHERE u.id > $1::uuid AND
 ($2::text = '' OR u.id::text = $2::text OR EXISTS (
 SELECT 1 FROM identity_characters c WHERE c.user_id=u.id AND
 (strpos(lower(c.name),lower($2::text)) > 0 OR c.character_id::text = $2::text)))
ORDER BY u.id LIMIT 26
`

type SearchMembersParams struct {
	AfterID pgtype.UUID
	Search  string
}

type SearchMembersRow struct {
	ID             pgtype.UUID
	CharacterID    int64
	Name           string
	CharacterCount int32
}

func (q *Queries) SearchMembers(ctx context.Context, arg SearchMembersParams) ([]SearchMembersRow, error) {
	rows, err := q.db.Query(ctx, searchMembers, arg.AfterID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMembersRow{}
	for rows.Next() {
		var i SearchMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.CharacterCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMain = `-- name: SetMain :exec
UPDATE identity_users SET main_character_id=$2 WHERE id=$1
`

type SetMainParams struct {
	ID              pgtype.UUID
	MainCharacterID pgtype.Int8
}

func (q *Queries) SetMain(ctx context.Context, arg SetMainParams) error {
	_, err := q.db.Exec(ctx, setMain, arg.ID, arg.MainCharacterID)
	return err
}

const updateCharacter = `-- name: UpdateCharacter :exec
UPDATE identity_characters SET name = $2, verified_at = now() WHERE character_id = $1
`

type UpdateCharacterParams struct {
	CharacterID int64
	Name        string
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) error {
	_, err := q.db.Exec(ctx, updateCharacter, arg.CharacterID, arg.Name)
	return err
}

const userForCharacter = `-- name: UserForCharacter :one
SELECT user_id FROM identity_characters WHERE character_id=$1 AND status='active'
`

func (q *Queries) UserForCharacter(ctx context.Context, characterID int64) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, userForCharacter, characterID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
