// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityCharacter struct {
	CharacterID int64
	UserID      pgtype.UUID
	Name        string
	OwnerHash   []byte
	Status      string
	VerifiedAt  pgtype.Timestamptz
}

type IdentityUser struct {
	ID              pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	MainCharacterID pgtype.Int8
}
