// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const audit = `-- name: Audit :exec
INSERT INTO attendance_audit(event_id,actor_id,action,request_key,payload) VALUES($1,$2,$3,$4,$5)
`

type AuditParams struct {
	EventID    int64
	ActorID    pgtype.UUID
	Action     string
	RequestKey pgtype.UUID
	Payload    []byte
}

func (q *Queries) Audit(ctx context.Context, arg AuditParams) error {
	_, err := q.db.Exec(ctx, audit,
		arg.EventID,
		arg.ActorID,
		arg.Action,
		arg.RequestKey,
		arg.Payload,
	)
	return err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO attendance_events(corporation_id,title,starts_at,created_by,request_key) VALUES($1,$2,$3,$4,$5)
ON CONFLICT(created_by,request_key) DO UPDATE SET request_key=excluded.request_key RETURNING id, corporation_id, title, starts_at, created_by, request_key, state, version, created_at, ends_at, pap_points, pap_issued
`

type CreateEventParams struct {
	CorporationID int64
	Title         string
	StartsAt      pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	RequestKey    pgtype.UUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (AttendanceEvent, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.CorporationID,
		arg.Title,
		arg.StartsAt,
		arg.CreatedBy,
		arg.RequestKey,
	)
	var i AttendanceEvent
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.Title,
		&i.StartsAt,
		&i.CreatedBy,
		&i.RequestKey,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.EndsAt,
		&i.PapPoints,
		&i.PapIssued,
	)
	return i, err
}

const eventCorporations = `-- name: EventCorporations :many
SELECT DISTINCT corporation_id FROM attendance_events ORDER BY corporation_id
`

func (q *Queries) EventCorporations(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, eventCorporations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var corporation_id int64
		if err := rows.Scan(&corporation_id); err != nil {
			return nil, err
		}
		items = append(items, corporation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAudit = `-- name: FindAudit :one
SELECT id, event_id, actor_id, action, request_key, payload, created_at FROM attendance_audit WHERE event_id=$1 AND request_key=$2
`

type FindAuditParams struct {
	EventID    int64
	RequestKey pgtype.UUID
}

func (q *Queries) FindAudit(ctx context.Context, arg FindAuditParams) (AttendanceAudit, error) {
	row := q.db.QueryRow(ctx, findAudit, arg.EventID, arg.RequestKey)
	var i AttendanceAudit
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ActorID,
		&i.Action,
		&i.RequestKey,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, corporation_id, title, starts_at, created_by, request_key, state, version, created_at, ends_at, pap_points, pap_issued FROM attendance_events WHERE id=$1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (AttendanceEvent, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i AttendanceEvent
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.Title,
		&i.StartsAt,
		&i.CreatedBy,
		&i.RequestKey,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.EndsAt,
		&i.PapPoints,
		&i.PapIssued,
	)
	return i, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, event_id, actor_id, action, request_key, payload, created_at FROM attendance_audit WHERE event_id=$1 AND id>$2 ORDER BY id LIMIT 51
`

type ListAuditParams struct {
	EventID int64
	AfterID int64
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AttendanceAudit, error) {
	rows, err := q.db.Query(ctx, listAudit, arg.EventID, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceAudit{}
	for rows.Next() {
		var i AttendanceAudit
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ActorID,
			&i.Action,
			&i.RequestKey,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT event_id, character_id, account_id, character_name, source, present, recorded_at, original_account_id FROM attendance_entries WHERE event_id=$1 ORDER BY recorded_at,character_id
`

func (q *Queries) ListEntries(ctx context.Context, eventID int64) ([]AttendanceEntry, error) {
	rows, err := q.db.Query(ctx, listEntries, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceEntry{}
	for rows.Next() {
		var i AttendanceEntry
		if err := rows.Scan(
			&i.EventID,
			&i.CharacterID,
			&i.AccountID,
			&i.CharacterName,
			&i.Source,
			&i.Present,
			&i.RecordedAt,
			&i.OriginalAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.corporation_id, e.title, e.starts_at, e.created_by, e.request_key, e.state, e.version, e.created_at, e.ends_at, e.pap_points, e.pap_issued, (SELECT count(DISTINCT a.account_id) FROM attendance_entries a WHERE a.event_id=e.id AND a.present)::int AS participants
FROM attendance_events e WHERE e.id<$1
AND (e.corporation_id=ANY($2::bigint[]) OR EXISTS(SELECT 1 FROM attendance_entries a WHERE a.event_id=e.id AND a.account_id=$3::uuid AND a.present))
ORDER BY e.id DESC LIMIT 31
`

type ListEventsParams struct {
	BeforeID     int64
	Corporations []int64
	AccountID    pgtype.UUID
}

type ListEventsRow struct {
	ID            int64
	CorporationID int64
	Title         string
	StartsAt      pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	RequestKey    pgtype.UUID
	State         string
	Version       int64
	CreatedAt     pgtype.Timestamptz
	EndsAt        pgtype.Timestamptz
	PapPoints     int32
	PapIssued     bool
	Participants  int32
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.BeforeID, arg.Corporations, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.Title,
			&i.StartsAt,
			&i.CreatedBy,
			&i.RequestKey,
			&i.State,
			&i.Version,
			&i.CreatedAt,
			&i.EndsAt,
			&i.PapPoints,
			&i.PapIssued,
			&i.Participants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPAP = `-- name: ListPendingPAP :many
SELECT e.id, e.corporation_id, e.title, e.starts_at, e.created_by, e.request_key, e.state, e.version, e.created_at, e.ends_at, e.pap_points, e.pap_issued, (SELECT count(DISTINCT a.account_id) FROM attendance_entries a WHERE a.event_id=e.id AND a.present AND a.account_id IS NOT NULL)::int AS participants
FROM attendance_events e
WHERE e.corporation_id=ANY($1::bigint[])
  AND e.state='closed'
  AND NOT e.pap_issued
  AND EXISTS (SELECT 1 FROM attendance_entries a WHERE a.event_id=e.id AND a.present AND a.account_id IS NOT NULL)
ORDER BY e.ends_at DESC NULLS LAST, e.id DESC LIMIT 200
`

type ListPendingPAPRow struct {
	ID            int64
	CorporationID int64
	Title         string
	StartsAt      pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	RequestKey    pgtype.UUID
	State         string
	Version       int64
	CreatedAt     pgtype.Timestamptz
	EndsAt        pgtype.Timestamptz
	PapPoints     int32
	PapIssued     bool
	Participants  int32
}

func (q *Queries) ListPendingPAP(ctx context.Context, corporations []int64) ([]ListPendingPAPRow, error) {
	rows, err := q.db.Query(ctx, listPendingPAP, corporations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingPAPRow{}
	for rows.Next() {
		var i ListPendingPAPRow
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.Title,
			&i.StartsAt,
			&i.CreatedBy,
			&i.RequestKey,
			&i.State,
			&i.Version,
			&i.CreatedAt,
			&i.EndsAt,
			&i.PapPoints,
			&i.PapIssued,
			&i.Participants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEvent = `-- name: LockEvent :one
SELECT id, corporation_id, title, starts_at, created_by, request_key, state, version, created_at, ends_at, pap_points, pap_issued FROM attendance_events WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockEvent(ctx context.Context, id int64) (AttendanceEvent, error) {
	row := q.db.QueryRow(ctx, lockEvent, id)
	var i AttendanceEvent
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.Title,
		&i.StartsAt,
		&i.CreatedBy,
		&i.RequestKey,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.EndsAt,
		&i.PapPoints,
		&i.PapIssued,
	)
	return i, err
}

const saveEntry = `-- name: SaveEntry :exec
INSERT INTO attendance_entries(event_id,character_id,account_id,character_name,source,present,recorded_at) VALUES($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT(event_id,character_id) DO UPDATE SET present=excluded.present,source=excluded.source,recorded_at=excluded.recorded_at
WHERE excluded.source='manual' OR attendance_entries.source<>'manual'
`

type SaveEntryParams struct {
	EventID       int64
	CharacterID   int64
	AccountID     pgtype.UUID
	CharacterName string
	Source        string
	Present       bool
	RecordedAt    pgtype.Timestamptz
}

func (q *Queries) SaveEntry(ctx context.Context, arg SaveEntryParams) error {
	_, err := q.db.Exec(ctx, saveEntry,
		arg.EventID,
		arg.CharacterID,
		arg.AccountID,
		arg.CharacterName,
		arg.Source,
		arg.Present,
		arg.RecordedAt,
	)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE attendance_events SET state=$2,version=version+1,ends_at=CASE WHEN $2='closed' THEN now() ELSE NULL END WHERE id=$1 RETURNING id, corporation_id, title, starts_at, created_by, request_key, state, version, created_at, ends_at, pap_points, pap_issued
`

type UpdateEventParams struct {
	ID    int64
	State string
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (AttendanceEvent, error) {
	row := q.db.QueryRow(ctx, updateEvent, arg.ID, arg.State)
	var i AttendanceEvent
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.Title,
		&i.StartsAt,
		&i.CreatedBy,
		&i.RequestKey,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.EndsAt,
		&i.PapPoints,
		&i.PapIssued,
	)
	return i, err
}
