// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battle.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const battleEntry = `-- name: BattleEntry :one
SELECT event_id, character_id, account_id, character_name, source, present, recorded_at, original_account_id FROM attendance_entries WHERE event_id=$1 AND character_id=$2
`

type BattleEntryParams struct {
	EventID     int64
	CharacterID int64
}

func (q *Queries) BattleEntry(ctx context.Context, arg BattleEntryParams) (AttendanceEntry, error) {
	row := q.db.QueryRow(ctx, battleEntry, arg.EventID, arg.CharacterID)
	var i AttendanceEntry
	err := row.Scan(
		&i.EventID,
		&i.CharacterID,
		&i.AccountID,
		&i.CharacterName,
		&i.Source,
		&i.Present,
		&i.RecordedAt,
		&i.OriginalAccountID,
	)
	return i, err
}

const claimBattleTask = `-- name: ClaimBattleTask :one
UPDATE attendance_battle_tasks SET state='running',lease_until=now()+interval '90 seconds',fence=fence+1
WHERE id=$1 AND state IN ('pending','running') AND next_due_at<=now() AND (lease_until IS NULL OR lease_until<now()) RETURNING id, event_id, character_id, account_id, owner_hash, kind, snapshot_id, state, reason, next_due_at, lease_until, fence, failures, progress, checked_at, original_account_id
`

func (q *Queries) ClaimBattleTask(ctx context.Context, id int64) (AttendanceBattleTask, error) {
	row := q.db.QueryRow(ctx, claimBattleTask, id)
	var i AttendanceBattleTask
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.CharacterID,
		&i.AccountID,
		&i.OwnerHash,
		&i.Kind,
		&i.SnapshotID,
		&i.State,
		&i.Reason,
		&i.NextDueAt,
		&i.LeaseUntil,
		&i.Fence,
		&i.Failures,
		&i.Progress,
		&i.CheckedAt,
		&i.OriginalAccountID,
	)
	return i, err
}

const completeBattleTask = `-- name: CompleteBattleTask :exec
UPDATE attendance_battle_tasks SET state=$2,reason=$3,next_due_at=$4,progress=$5,failures=$6,checked_at=now(),lease_until=NULL
WHERE id=$1 AND fence=$7 AND lease_until>now()
`

type CompleteBattleTaskParams struct {
	ID        int64
	State     string
	Reason    string
	NextDueAt pgtype.Timestamptz
	Progress  []byte
	Failures  int32
	Fence     int64
}

func (q *Queries) CompleteBattleTask(ctx context.Context, arg CompleteBattleTaskParams) error {
	_, err := q.db.Exec(ctx, completeBattleTask,
		arg.ID,
		arg.State,
		arg.Reason,
		arg.NextDueAt,
		arg.Progress,
		arg.Failures,
		arg.Fence,
	)
	return err
}

const dueBattleTasks = `-- name: DueBattleTasks :many
SELECT id,kind FROM attendance_battle_tasks WHERE state IN ('pending','running') AND next_due_at<=now()
AND (lease_until IS NULL OR lease_until<now()) ORDER BY CASE WHEN kind='fitting' THEN 0 ELSE 1 END,next_due_at,id LIMIT 50
`

type DueBattleTasksRow struct {
	ID   int64
	Kind string
}

func (q *Queries) DueBattleTasks(ctx context.Context) ([]DueBattleTasksRow, error) {
	rows, err := q.db.Query(ctx, dueBattleTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueBattleTasksRow{}
	for rows.Next() {
		var i DueBattleTasksRow
		if err := rows.Scan(&i.ID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entryLossCounts = `-- name: EntryLossCounts :many
SELECT character_id,count(*)::int AS losses FROM attendance_losses WHERE event_id=$1 AND state='confirmed' GROUP BY character_id
`

type EntryLossCountsRow struct {
	CharacterID int64
	Losses      int32
}

func (q *Queries) EntryLossCounts(ctx context.Context, eventID int64) ([]EntryLossCountsRow, error) {
	rows, err := q.db.Query(ctx, entryLossCounts, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryLossCountsRow{}
	for rows.Next() {
		var i EntryLossCountsRow
		if err := rows.Scan(&i.CharacterID, &i.Losses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entryShips = `-- name: EntryShips :many
SELECT DISTINCT ON (character_id) character_id,ship_type_id,solar_system_id,observed_at FROM attendance_ships WHERE event_id=$1 ORDER BY character_id,observed_at DESC,id DESC
`

type EntryShipsRow struct {
	CharacterID   int64
	ShipTypeID    int64
	SolarSystemID int64
	ObservedAt    pgtype.Timestamptz
}

func (q *Queries) EntryShips(ctx context.Context, eventID int64) ([]EntryShipsRow, error) {
	rows, err := q.db.Query(ctx, entryShips, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryShipsRow{}
	for rows.Next() {
		var i EntryShipsRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.ShipTypeID,
			&i.SolarSystemID,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShip = `-- name: GetShip :one
SELECT id, event_id, character_id, request_key, ship_type_id, solar_system_id, joined_at, observed_at, fitting_state, fitting FROM attendance_ships WHERE id=$1
`

func (q *Queries) GetShip(ctx context.Context, id int64) (AttendanceShip, error) {
	row := q.db.QueryRow(ctx, getShip, id)
	var i AttendanceShip
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.CharacterID,
		&i.RequestKey,
		&i.ShipTypeID,
		&i.SolarSystemID,
		&i.JoinedAt,
		&i.ObservedAt,
		&i.FittingState,
		&i.Fitting,
	)
	return i, err
}

const listBattleTasks = `-- name: ListBattleTasks :many
SELECT DISTINCT ON (kind) id,kind,state,reason,checked_at,next_due_at FROM attendance_battle_tasks WHERE event_id=$1 AND character_id=$2 ORDER BY kind,id DESC
`

type ListBattleTasksParams struct {
	EventID     int64
	CharacterID int64
}

type ListBattleTasksRow struct {
	ID        int64
	Kind      string
	State     string
	Reason    string
	CheckedAt pgtype.Timestamptz
	NextDueAt pgtype.Timestamptz
}

func (q *Queries) ListBattleTasks(ctx context.Context, arg ListBattleTasksParams) ([]ListBattleTasksRow, error) {
	rows, err := q.db.Query(ctx, listBattleTasks, arg.EventID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBattleTasksRow{}
	for rows.Next() {
		var i ListBattleTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.State,
			&i.Reason,
			&i.CheckedAt,
			&i.NextDueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLosses = `-- name: ListLosses :many
SELECT event_id, character_id, killmail_id, occurred_at, ship_type_id, solar_system_id, items, state, version FROM attendance_losses WHERE event_id=$1 AND character_id=$2 ORDER BY occurred_at DESC,killmail_id DESC LIMIT 101
`

type ListLossesParams struct {
	EventID     int64
	CharacterID int64
}

func (q *Queries) ListLosses(ctx context.Context, arg ListLossesParams) ([]AttendanceLoss, error) {
	rows, err := q.db.Query(ctx, listLosses, arg.EventID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceLoss{}
	for rows.Next() {
		var i AttendanceLoss
		if err := rows.Scan(
			&i.EventID,
			&i.CharacterID,
			&i.KillmailID,
			&i.OccurredAt,
			&i.ShipTypeID,
			&i.SolarSystemID,
			&i.Items,
			&i.State,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShips = `-- name: ListShips :many
SELECT id, event_id, character_id, request_key, ship_type_id, solar_system_id, joined_at, observed_at, fitting_state, fitting FROM attendance_ships WHERE event_id=$1 AND character_id=$2 ORDER BY id DESC LIMIT 21
`

type ListShipsParams struct {
	EventID     int64
	CharacterID int64
}

func (q *Queries) ListShips(ctx context.Context, arg ListShipsParams) ([]AttendanceShip, error) {
	rows, err := q.db.Query(ctx, listShips, arg.EventID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceShip{}
	for rows.Next() {
		var i AttendanceShip
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.CharacterID,
			&i.RequestKey,
			&i.ShipTypeID,
			&i.SolarSystemID,
			&i.JoinedAt,
			&i.ObservedAt,
			&i.FittingState,
			&i.Fitting,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBattleTask = `-- name: LockBattleTask :one
SELECT id, event_id, character_id, account_id, owner_hash, kind, snapshot_id, state, reason, next_due_at, lease_until, fence, failures, progress, checked_at, original_account_id FROM attendance_battle_tasks WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockBattleTask(ctx context.Context, id int64) (AttendanceBattleTask, error) {
	row := q.db.QueryRow(ctx, lockBattleTask, id)
	var i AttendanceBattleTask
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.CharacterID,
		&i.AccountID,
		&i.OwnerHash,
		&i.Kind,
		&i.SnapshotID,
		&i.State,
		&i.Reason,
		&i.NextDueAt,
		&i.LeaseUntil,
		&i.Fence,
		&i.Failures,
		&i.Progress,
		&i.CheckedAt,
		&i.OriginalAccountID,
	)
	return i, err
}

const lockLoss = `-- name: LockLoss :one
SELECT event_id, character_id, killmail_id, occurred_at, ship_type_id, solar_system_id, items, state, version FROM attendance_losses WHERE event_id=$1 AND killmail_id=$2 FOR UPDATE
`

type LockLossParams struct {
	EventID    int64
	KillmailID int64
}

func (q *Queries) LockLoss(ctx context.Context, arg LockLossParams) (AttendanceLoss, error) {
	row := q.db.QueryRow(ctx, lockLoss, arg.EventID, arg.KillmailID)
	var i AttendanceLoss
	err := row.Scan(
		&i.EventID,
		&i.CharacterID,
		&i.KillmailID,
		&i.OccurredAt,
		&i.ShipTypeID,
		&i.SolarSystemID,
		&i.Items,
		&i.State,
		&i.Version,
	)
	return i, err
}

const retryBattleTasks = `-- name: RetryBattleTasks :exec
UPDATE attendance_battle_tasks SET state='pending',reason='',failures=0,next_due_at=now(),fence=fence+1,lease_until=NULL
WHERE event_id=$1 AND character_id=$2 AND account_id=$3 AND owner_hash=$4
AND state IN ('ready','failed','blocked') AND kind='losses'
`

type RetryBattleTasksParams struct {
	EventID     int64
	CharacterID int64
	AccountID   pgtype.UUID
	OwnerHash   []byte
}

func (q *Queries) RetryBattleTasks(ctx context.Context, arg RetryBattleTasksParams) error {
	_, err := q.db.Exec(ctx, retryBattleTasks,
		arg.EventID,
		arg.CharacterID,
		arg.AccountID,
		arg.OwnerHash,
	)
	return err
}

const reviewLoss = `-- name: ReviewLoss :exec
UPDATE attendance_losses SET state=$3,version=version+1 WHERE event_id=$1 AND killmail_id=$2
`

type ReviewLossParams struct {
	EventID    int64
	KillmailID int64
	State      string
}

func (q *Queries) ReviewLoss(ctx context.Context, arg ReviewLossParams) error {
	_, err := q.db.Exec(ctx, reviewLoss, arg.EventID, arg.KillmailID, arg.State)
	return err
}

const saveFitting = `-- name: SaveFitting :exec
UPDATE attendance_ships SET fitting_state=$2,fitting=$3 WHERE id=$1
`

type SaveFittingParams struct {
	ID           int64
	FittingState string
	Fitting      []byte
}

func (q *Queries) SaveFitting(ctx context.Context, arg SaveFittingParams) error {
	_, err := q.db.Exec(ctx, saveFitting, arg.ID, arg.FittingState, arg.Fitting)
	return err
}

const saveLoss = `-- name: SaveLoss :exec
INSERT INTO attendance_losses(event_id,character_id,killmail_id,occurred_at,ship_type_id,solar_system_id,items) VALUES($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT(event_id,killmail_id) DO NOTHING
`

type SaveLossParams struct {
	EventID       int64
	CharacterID   int64
	KillmailID    int64
	OccurredAt    pgtype.Timestamptz
	ShipTypeID    int64
	SolarSystemID int64
	Items         []byte
}

func (q *Queries) SaveLoss(ctx context.Context, arg SaveLossParams) error {
	_, err := q.db.Exec(ctx, saveLoss,
		arg.EventID,
		arg.CharacterID,
		arg.KillmailID,
		arg.OccurredAt,
		arg.ShipTypeID,
		arg.SolarSystemID,
		arg.Items,
	)
	return err
}

const saveShip = `-- name: SaveShip :one
INSERT INTO attendance_ships(event_id,character_id,request_key,ship_type_id,solar_system_id,joined_at,observed_at)
VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id
`

type SaveShipParams struct {
	EventID       int64
	CharacterID   int64
	RequestKey    pgtype.UUID
	ShipTypeID    int64
	SolarSystemID int64
	JoinedAt      pgtype.Timestamptz
	ObservedAt    pgtype.Timestamptz
}

func (q *Queries) SaveShip(ctx context.Context, arg SaveShipParams) (int64, error) {
	row := q.db.QueryRow(ctx, saveShip,
		arg.EventID,
		arg.CharacterID,
		arg.RequestKey,
		arg.ShipTypeID,
		arg.SolarSystemID,
		arg.JoinedAt,
		arg.ObservedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const seedBattleTask = `-- name: SeedBattleTask :exec
INSERT INTO attendance_battle_tasks(event_id,character_id,account_id,owner_hash,kind,snapshot_id) VALUES($1,$2,$3,$4,$5,$6)
ON CONFLICT(event_id,character_id,kind,snapshot_id) DO NOTHING
`

type SeedBattleTaskParams struct {
	EventID     int64
	CharacterID int64
	AccountID   pgtype.UUID
	OwnerHash   []byte
	Kind        string
	SnapshotID  int64
}

func (q *Queries) SeedBattleTask(ctx context.Context, arg SeedBattleTaskParams) error {
	_, err := q.db.Exec(ctx, seedBattleTask,
		arg.EventID,
		arg.CharacterID,
		arg.AccountID,
		arg.OwnerHash,
		arg.Kind,
		arg.SnapshotID,
	)
	return err
}
