// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceAudit struct {
	ID         int64
	EventID    int64
	ActorID    pgtype.UUID
	Action     string
	RequestKey pgtype.UUID
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
}

type AttendanceBattleTask struct {
	ID                int64
	EventID           int64
	CharacterID       int64
	AccountID         pgtype.UUID
	OwnerHash         []byte
	Kind              string
	SnapshotID        int64
	State             string
	Reason            string
	NextDueAt         pgtype.Timestamptz
	LeaseUntil        pgtype.Timestamptz
	Fence             int64
	Failures          int32
	Progress          []byte
	CheckedAt         pgtype.Timestamptz
	OriginalAccountID pgtype.UUID
}

type AttendanceEntry struct {
	EventID           int64
	CharacterID       int64
	AccountID         pgtype.UUID
	CharacterName     string
	Source            string
	Present           bool
	RecordedAt        pgtype.Timestamptz
	OriginalAccountID pgtype.UUID
}

type AttendanceEvent struct {
	ID            int64
	CorporationID int64
	Title         string
	StartsAt      pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	RequestKey    pgtype.UUID
	State         string
	Version       int64
	CreatedAt     pgtype.Timestamptz
	EndsAt        pgtype.Timestamptz
	PapPoints     int32
	PapIssued     bool
}

type AttendanceLoss struct {
	EventID       int64
	CharacterID   int64
	KillmailID    int64
	OccurredAt    pgtype.Timestamptz
	ShipTypeID    int64
	SolarSystemID int64
	Items         []byte
	State         string
	Version       int64
}

type AttendancePapAward struct {
	EventID           int64
	CharacterID       int64
	AccountID         pgtype.UUID
	CharacterName     string
	Points            int32
	UpdatedAt         pgtype.Timestamptz
	OriginalAccountID pgtype.UUID
}

type AttendanceShip struct {
	ID            int64
	EventID       int64
	CharacterID   int64
	RequestKey    pgtype.UUID
	ShipTypeID    int64
	SolarSystemID int64
	JoinedAt      pgtype.Timestamptz
	ObservedAt    pgtype.Timestamptz
	FittingState  string
	Fitting       []byte
}
