// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pap.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPAPLedger = `-- name: AddPAPLedger :exec
INSERT INTO attendance_pap_ledger(event_id,character_id,account_id,actor_id,request_key,delta,balance,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type AddPAPLedgerParams struct {
	EventID     int64
	CharacterID int64
	AccountID   pgtype.UUID
	ActorID     pgtype.UUID
	RequestKey  pgtype.UUID
	Delta       int32
	Balance     int32
	Reason      string
}

func (q *Queries) AddPAPLedger(ctx context.Context, arg AddPAPLedgerParams) error {
	_, err := q.db.Exec(ctx, addPAPLedger,
		arg.EventID,
		arg.CharacterID,
		arg.AccountID,
		arg.ActorID,
		arg.RequestKey,
		arg.Delta,
		arg.Balance,
		arg.Reason,
	)
	return err
}

const pAPAwards = `-- name: PAPAwards :many
SELECT event_id, character_id, account_id, character_name, points, updated_at, original_account_id FROM attendance_pap_awards WHERE event_id=$1 ORDER BY character_id
`

func (q *Queries) PAPAwards(ctx context.Context, eventID int64) ([]AttendancePapAward, error) {
	rows, err := q.db.Query(ctx, pAPAwards, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendancePapAward{}
	for rows.Next() {
		var i AttendancePapAward
		if err := rows.Scan(
			&i.EventID,
			&i.CharacterID,
			&i.AccountID,
			&i.CharacterName,
			&i.Points,
			&i.UpdatedAt,
			&i.OriginalAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pAPLedger = `-- name: PAPLedger :many
SELECT l.id, l.event_id, l.character_id, l.account_id, l.actor_id, l.request_key, l.delta, l.balance, l.reason, l.created_at, l.original_account_id,a.character_name FROM attendance_pap_ledger l JOIN attendance_pap_awards a USING(event_id,character_id)
WHERE l.event_id=$1 AND l.id>$2 AND ($3::boolean OR l.account_id=$4::uuid)
ORDER BY l.id LIMIT 51
`

type PAPLedgerParams struct {
	EventID   int64
	AfterID   int64
	Manage    bool
	AccountID pgtype.UUID
}

type PAPLedgerRow struct {
	ID                int64
	EventID           int64
	CharacterID       int64
	AccountID         pgtype.UUID
	ActorID           pgtype.UUID
	RequestKey        pgtype.UUID
	Delta             int32
	Balance           int32
	Reason            string
	CreatedAt         pgtype.Timestamptz
	OriginalAccountID pgtype.UUID
	CharacterName     string
}

func (q *Queries) PAPLedger(ctx context.Context, arg PAPLedgerParams) ([]PAPLedgerRow, error) {
	rows, err := q.db.Query(ctx, pAPLedger,
		arg.EventID,
		arg.AfterID,
		arg.Manage,
		arg.AccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PAPLedgerRow{}
	for rows.Next() {
		var i PAPLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.CharacterID,
			&i.AccountID,
			&i.ActorID,
			&i.RequestKey,
			&i.Delta,
			&i.Balance,
			&i.Reason,
			&i.CreatedAt,
			&i.OriginalAccountID,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pAPReport = `-- name: PAPReport :many
SELECT a.event_id, a.character_id, a.account_id, a.character_name, a.points, a.updated_at, a.original_account_id,e.title,e.starts_at,e.corporation_id
FROM attendance_pap_awards a JOIN attendance_events e ON e.id=a.event_id
WHERE a.points>0 AND e.starts_at>=$1 AND e.starts_at<$2
AND (($3::bigint>0 AND e.corporation_id=$3) OR ($3=0 AND a.account_id=$4::uuid))
ORDER BY e.starts_at DESC,a.event_id DESC,a.character_id LIMIT 51 OFFSET $5
`

type PAPReportParams struct {
	Since         pgtype.Timestamptz
	Until         pgtype.Timestamptz
	CorporationID int64
	AccountID     pgtype.UUID
	RowOffset     int32
}

type PAPReportRow struct {
	EventID           int64
	CharacterID       int64
	AccountID         pgtype.UUID
	CharacterName     string
	Points            int32
	UpdatedAt         pgtype.Timestamptz
	OriginalAccountID pgtype.UUID
	Title             string
	StartsAt          pgtype.Timestamptz
	CorporationID     int64
}

func (q *Queries) PAPReport(ctx context.Context, arg PAPReportParams) ([]PAPReportRow, error) {
	rows, err := q.db.Query(ctx, pAPReport,
		arg.Since,
		arg.Until,
		arg.CorporationID,
		arg.AccountID,
		arg.RowOffset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PAPReportRow{}
	for rows.Next() {
		var i PAPReportRow
		if err := rows.Scan(
			&i.EventID,
			&i.CharacterID,
			&i.AccountID,
			&i.CharacterName,
			&i.Points,
			&i.UpdatedAt,
			&i.OriginalAccountID,
			&i.Title,
			&i.StartsAt,
			&i.CorporationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pAPTotals = `-- name: PAPTotals :one
SELECT coalesce(sum(a.points),0)::bigint AS points,count(DISTINCT a.event_id)::bigint AS events,count(*)::bigint AS participations
FROM attendance_pap_awards a JOIN attendance_events e ON e.id=a.event_id
WHERE a.points>0 AND e.starts_at>=$1 AND e.starts_at<$2
AND (($3::bigint>0 AND e.corporation_id=$3) OR ($3=0 AND a.account_id=$4::uuid))
`

type PAPTotalsParams struct {
	Since         pgtype.Timestamptz
	Until         pgtype.Timestamptz
	CorporationID int64
	AccountID     pgtype.UUID
}

type PAPTotalsRow struct {
	Points         int64
	Events         int64
	Participations int64
}

func (q *Queries) PAPTotals(ctx context.Context, arg PAPTotalsParams) (PAPTotalsRow, error) {
	row := q.db.QueryRow(ctx, pAPTotals,
		arg.Since,
		arg.Until,
		arg.CorporationID,
		arg.AccountID,
	)
	var i PAPTotalsRow
	err := row.Scan(&i.Points, &i.Events, &i.Participations)
	return i, err
}

const savePAPAward = `-- name: SavePAPAward :exec
INSERT INTO attendance_pap_awards(event_id,character_id,account_id,character_name,points) VALUES($1,$2,$3,$4,$5)
ON CONFLICT(event_id,character_id) DO UPDATE SET points=excluded.points,updated_at=now()
`

type SavePAPAwardParams struct {
	EventID       int64
	CharacterID   int64
	AccountID     pgtype.UUID
	CharacterName string
	Points        int32
}

func (q *Queries) SavePAPAward(ctx context.Context, arg SavePAPAwardParams) error {
	_, err := q.db.Exec(ctx, savePAPAward,
		arg.EventID,
		arg.CharacterID,
		arg.AccountID,
		arg.CharacterName,
		arg.Points,
	)
	return err
}

const setEventPAP = `-- name: SetEventPAP :exec
UPDATE attendance_events SET pap_points=$2,pap_issued=$3,version=version+1 WHERE id=$1
`

type SetEventPAPParams struct {
	ID        int64
	PapPoints int32
	PapIssued bool
}

func (q *Queries) SetEventPAP(ctx context.Context, arg SetEventPAPParams) error {
	_, err := q.db.Exec(ctx, setEventPAP, arg.ID, arg.PapPoints, arg.PapIssued)
	return err
}
