// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rewards.sql

package store

import (
	"context"
)

const lockPAPAccount = `-- name: LockPAPAccount :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,740025))
`

func (q *Queries) LockPAPAccount(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, lockPAPAccount, accountID)
	return err
}
