// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommunityBotEvent struct {
	Source      string
	EventID     string
	PayloadHash []byte
	ReceivedAt  pgtype.Timestamptz
}

type CommunityProfile struct {
	UserID      pgtype.UUID
	QqNumber    string
	KookName    string
	Version     int64
	QqVersion   int64
	KookVersion int64
	UpdatedAt   pgtype.Timestamptz
}

type CommunityQqGroupApplication struct {
	ID            int64
	UserID        pgtype.UUID
	GroupOpenid   string
	QqNumber      string
	QqVersion     int64
	CodeHash      []byte
	Status        string
	MemberOpenid  pgtype.Text
	JoinRequestID pgtype.Text
	FailureReason pgtype.Text
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	ApprovedAt    pgtype.Timestamptz
	BoundAt       pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type CommunityQqGroupSetting struct {
	GroupOpenid string
	Label       string
	Enabled     bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
