// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureProfile = `-- name: EnsureProfile :exec
INSERT INTO community_profiles(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING
`

func (q *Queries) EnsureProfile(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureProfile, userID)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT p.user_id, p.qq_number, p.kook_name, p.version, p.qq_version, p.kook_version, p.updated_at,
 EXISTS(SELECT 1 FROM community_confirmations c WHERE c.user_id=p.user_id AND c.platform='qq' AND c.field_version=p.qq_version AND c.invalidated_at IS NULL) AS qq_confirmed,
 EXISTS(SELECT 1 FROM community_confirmations c WHERE c.user_id=p.user_id AND c.platform='kook' AND c.field_version=p.kook_version AND c.invalidated_at IS NULL) AS kook_confirmed
FROM community_profiles p WHERE p.user_id=$1
`

type GetProfileRow struct {
	UserID        pgtype.UUID
	QqNumber      string
	KookName      string
	Version       int64
	QqVersion     int64
	KookVersion   int64
	UpdatedAt     pgtype.Timestamptz
	QqConfirmed   bool
	KookConfirmed bool
}

func (q *Queries) GetProfile(ctx context.Context, userID pgtype.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.UserID,
		&i.QqNumber,
		&i.KookName,
		&i.Version,
		&i.QqVersion,
		&i.KookVersion,
		&i.UpdatedAt,
		&i.QqConfirmed,
		&i.KookConfirmed,
	)
	return i, err
}

const invalidateConfirmations = `-- name: InvalidateConfirmations :exec
UPDATE community_confirmations SET invalidated_at=now() WHERE user_id=$1 AND platform=ANY($2::text[]) AND invalidated_at IS NULL
`

type InvalidateConfirmationsParams struct {
	UserID  pgtype.UUID
	Column2 []string
}

func (q *Queries) InvalidateConfirmations(ctx context.Context, arg InvalidateConfirmationsParams) error {
	_, err := q.db.Exec(ctx, invalidateConfirmations, arg.UserID, arg.Column2)
	return err
}

const lockProfile = `-- name: LockProfile :one
SELECT user_id, qq_number, kook_name, version, qq_version, kook_version, updated_at FROM community_profiles WHERE user_id=$1 FOR UPDATE
`

func (q *Queries) LockProfile(ctx context.Context, userID pgtype.UUID) (CommunityProfile, error) {
	row := q.db.QueryRow(ctx, lockProfile, userID)
	var i CommunityProfile
	err := row.Scan(
		&i.UserID,
		&i.QqNumber,
		&i.KookName,
		&i.Version,
		&i.QqVersion,
		&i.KookVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const recordProfileChange = `-- name: RecordProfileChange :exec
INSERT INTO community_profile_events(user_id,profile_version,changed_platforms) VALUES($1,$2,$3)
`

type RecordProfileChangeParams struct {
	UserID           pgtype.UUID
	ProfileVersion   int64
	ChangedPlatforms []string
}

func (q *Queries) RecordProfileChange(ctx context.Context, arg RecordProfileChangeParams) error {
	_, err := q.db.Exec(ctx, recordProfileChange, arg.UserID, arg.ProfileVersion, arg.ChangedPlatforms)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE community_profiles SET qq_number=$2,kook_name=$3,
 qq_version=qq_version+CASE WHEN qq_number<>$2 THEN 1 ELSE 0 END,
 kook_version=kook_version+CASE WHEN kook_name<>$3 THEN 1 ELSE 0 END,
 version=version+1,updated_at=now() WHERE user_id=$1
`

type UpdateProfileParams struct {
	UserID   pgtype.UUID
	QqNumber string
	KookName string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile, arg.UserID, arg.QqNumber, arg.KookName)
	return err
}
