// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qqbot.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findQQProfile = `-- name: FindQQProfile :one
SELECT p.user_id, p.qq_number, p.kook_name, p.version, p.qq_version, p.kook_version, p.updated_at,
 EXISTS(SELECT 1 FROM community_confirmations c WHERE c.user_id=p.user_id AND c.platform='qq' AND c.field_version=p.qq_version AND c.invalidated_at IS NULL) AS qq_confirmed,
 EXISTS(SELECT 1 FROM community_confirmations c WHERE c.user_id=p.user_id AND c.platform='kook' AND c.field_version=p.kook_version AND c.invalidated_at IS NULL) AS kook_confirmed
FROM community_profiles p
WHERE p.qq_number=$1
FOR UPDATE
`

type FindQQProfileRow struct {
	UserID        pgtype.UUID
	QqNumber      string
	KookName      string
	Version       int64
	QqVersion     int64
	KookVersion   int64
	UpdatedAt     pgtype.Timestamptz
	QqConfirmed   bool
	KookConfirmed bool
}

func (q *Queries) FindQQProfile(ctx context.Context, qqNumber string) (FindQQProfileRow, error) {
	row := q.db.QueryRow(ctx, findQQProfile, qqNumber)
	var i FindQQProfileRow
	err := row.Scan(
		&i.UserID,
		&i.QqNumber,
		&i.KookName,
		&i.Version,
		&i.QqVersion,
		&i.KookVersion,
		&i.UpdatedAt,
		&i.QqConfirmed,
		&i.KookConfirmed,
	)
	return i, err
}

const getBotEvent = `-- name: GetBotEvent :one
SELECT source, event_id, payload_hash, received_at
FROM community_bot_events
WHERE source=$1 AND event_id=$2
`

type GetBotEventParams struct {
	Source  string
	EventID string
}

func (q *Queries) GetBotEvent(ctx context.Context, arg GetBotEventParams) (CommunityBotEvent, error) {
	row := q.db.QueryRow(ctx, getBotEvent, arg.Source, arg.EventID)
	var i CommunityBotEvent
	err := row.Scan(
		&i.Source,
		&i.EventID,
		&i.PayloadHash,
		&i.ReceivedAt,
	)
	return i, err
}

const insertBotEvent = `-- name: InsertBotEvent :exec
INSERT INTO community_bot_events(source,event_id,payload_hash)
VALUES($1,$2,$3)
ON CONFLICT(source,event_id) DO NOTHING
`

type InsertBotEventParams struct {
	Source      string
	EventID     string
	PayloadHash []byte
}

func (q *Queries) InsertBotEvent(ctx context.Context, arg InsertBotEventParams) error {
	_, err := q.db.Exec(ctx, insertBotEvent, arg.Source, arg.EventID, arg.PayloadHash)
	return err
}

const insertConfirmation = `-- name: InsertConfirmation :exec
INSERT INTO community_confirmations(user_id,platform,field_version,source,actor,event_id)
VALUES($1,'qq',$2,$3,$4,$5)
`

type InsertConfirmationParams struct {
	UserID       pgtype.UUID
	FieldVersion int64
	Source       string
	Actor        string
	EventID      string
}

func (q *Queries) InsertConfirmation(ctx context.Context, arg InsertConfirmationParams) error {
	_, err := q.db.Exec(ctx, insertConfirmation,
		arg.UserID,
		arg.FieldVersion,
		arg.Source,
		arg.Actor,
		arg.EventID,
	)
	return err
}

const invalidateQQConfirmations = `-- name: InvalidateQQConfirmations :exec
UPDATE community_confirmations
SET invalidated_at=now()
WHERE user_id=$1 AND platform='qq' AND invalidated_at IS NULL
`

func (q *Queries) InvalidateQQConfirmations(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidateQQConfirmations, userID)
	return err
}
