// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qqgroup.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expireQQGroupApplications = `-- name: ExpireQQGroupApplications :exec
UPDATE community_qq_group_applications SET status='expired',updated_at=now()
WHERE status IN ('pending','approving') AND expires_at<=now()
`

func (q *Queries) ExpireQQGroupApplications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireQQGroupApplications)
	return err
}

const findQQGroupApplicationByCode = `-- name: FindQQGroupApplicationByCode :one
SELECT id,user_id,group_openid,qq_number,qq_version,code_hash,status,member_openid,join_request_id,
 failure_reason,created_at,expires_at,approved_at,bound_at,updated_at
FROM community_qq_group_applications
WHERE code_hash=$1 AND status='pending' AND expires_at>now()
FOR UPDATE
`

func (q *Queries) FindQQGroupApplicationByCode(ctx context.Context, codeHash []byte) (CommunityQqGroupApplication, error) {
	row := q.db.QueryRow(ctx, findQQGroupApplicationByCode, codeHash)
	var i CommunityQqGroupApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupOpenid,
		&i.QqNumber,
		&i.QqVersion,
		&i.CodeHash,
		&i.Status,
		&i.MemberOpenid,
		&i.JoinRequestID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.BoundAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findQQGroupApplicationByMember = `-- name: FindQQGroupApplicationByMember :one
SELECT id,user_id,group_openid,qq_number,qq_version,code_hash,status,member_openid,join_request_id,
 failure_reason,created_at,expires_at,approved_at,bound_at,updated_at
FROM community_qq_group_applications
WHERE group_openid=$1 AND member_openid=$2 AND status='approved'
ORDER BY updated_at DESC LIMIT 1 FOR UPDATE
`

type FindQQGroupApplicationByMemberParams struct {
	GroupOpenid  string
	MemberOpenid pgtype.Text
}

func (q *Queries) FindQQGroupApplicationByMember(ctx context.Context, arg FindQQGroupApplicationByMemberParams) (CommunityQqGroupApplication, error) {
	row := q.db.QueryRow(ctx, findQQGroupApplicationByMember, arg.GroupOpenid, arg.MemberOpenid)
	var i CommunityQqGroupApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupOpenid,
		&i.QqNumber,
		&i.QqVersion,
		&i.CodeHash,
		&i.Status,
		&i.MemberOpenid,
		&i.JoinRequestID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.BoundAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQQBotSettings = `-- name: GetQQBotSettings :one
SELECT app_id,api_base,secret_ciphertext,created_at,updated_at
FROM community_qq_bot_settings
WHERE id=true
`

type GetQQBotSettingsRow struct {
	AppID            string
	ApiBase          string
	SecretCiphertext []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetQQBotSettings(ctx context.Context) (GetQQBotSettingsRow, error) {
	row := q.db.QueryRow(ctx, getQQBotSettings)
	var i GetQQBotSettingsRow
	err := row.Scan(
		&i.AppID,
		&i.ApiBase,
		&i.SecretCiphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertQQGroupApplication = `-- name: InsertQQGroupApplication :one
INSERT INTO community_qq_group_applications(user_id,group_openid,qq_number,qq_version,code_hash,status,expires_at)
VALUES($1,$2,$3,$4,$5,'pending',$6)
RETURNING id,group_openid,qq_number,qq_version,status,expires_at
`

type InsertQQGroupApplicationParams struct {
	UserID      pgtype.UUID
	GroupOpenid string
	QqNumber    string
	QqVersion   int64
	CodeHash    []byte
	ExpiresAt   pgtype.Timestamptz
}

type InsertQQGroupApplicationRow struct {
	ID          int64
	GroupOpenid string
	QqNumber    string
	QqVersion   int64
	Status      string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) InsertQQGroupApplication(ctx context.Context, arg InsertQQGroupApplicationParams) (InsertQQGroupApplicationRow, error) {
	row := q.db.QueryRow(ctx, insertQQGroupApplication,
		arg.UserID,
		arg.GroupOpenid,
		arg.QqNumber,
		arg.QqVersion,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i InsertQQGroupApplicationRow
	err := row.Scan(
		&i.ID,
		&i.GroupOpenid,
		&i.QqNumber,
		&i.QqVersion,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const insertQQGroupBinding = `-- name: InsertQQGroupBinding :exec
INSERT INTO community_qq_group_bindings(user_id,group_openid,member_openid,qq_number,application_id)
VALUES($1,$2,$3,$4,$5)
ON CONFLICT(group_openid,member_openid) DO UPDATE SET user_id=EXCLUDED.user_id,qq_number=EXCLUDED.qq_number,application_id=EXCLUDED.application_id,bound_at=now()
`

type InsertQQGroupBindingParams struct {
	UserID        pgtype.UUID
	GroupOpenid   string
	MemberOpenid  string
	QqNumber      string
	ApplicationID int64
}

func (q *Queries) InsertQQGroupBinding(ctx context.Context, arg InsertQQGroupBindingParams) error {
	_, err := q.db.Exec(ctx, insertQQGroupBinding,
		arg.UserID,
		arg.GroupOpenid,
		arg.MemberOpenid,
		arg.QqNumber,
		arg.ApplicationID,
	)
	return err
}

const insertQQGroupSetting = `-- name: InsertQQGroupSetting :exec
INSERT INTO community_qq_group_settings(group_openid,label,enabled)
VALUES($1,$2,$3)
`

type InsertQQGroupSettingParams struct {
	GroupOpenid string
	Label       string
	Enabled     bool
}

func (q *Queries) InsertQQGroupSetting(ctx context.Context, arg InsertQQGroupSettingParams) error {
	_, err := q.db.Exec(ctx, insertQQGroupSetting, arg.GroupOpenid, arg.Label, arg.Enabled)
	return err
}

const latestQQGroupApplication = `-- name: LatestQQGroupApplication :one
SELECT id,user_id,group_openid,qq_number,qq_version,code_hash,status,member_openid,join_request_id,
 failure_reason,created_at,expires_at,approved_at,bound_at,updated_at
FROM community_qq_group_applications
WHERE user_id=$1
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LatestQQGroupApplication(ctx context.Context, userID pgtype.UUID) (CommunityQqGroupApplication, error) {
	row := q.db.QueryRow(ctx, latestQQGroupApplication, userID)
	var i CommunityQqGroupApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupOpenid,
		&i.QqNumber,
		&i.QqVersion,
		&i.CodeHash,
		&i.Status,
		&i.MemberOpenid,
		&i.JoinRequestID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.BoundAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQQGroupApplications = `-- name: ListQQGroupApplications :many
SELECT id,user_id,group_openid,qq_number,qq_version,status,member_openid,join_request_id,failure_reason,
 created_at,expires_at,approved_at,bound_at,updated_at
FROM community_qq_group_applications
WHERE ($1::text='' OR group_openid=$1) AND ($2::text='' OR status=$2)
ORDER BY created_at DESC LIMIT $3
`

type ListQQGroupApplicationsParams struct {
	Column1 string
	Column2 string
	Limit   int32
}

type ListQQGroupApplicationsRow struct {
	ID            int64
	UserID        pgtype.UUID
	GroupOpenid   string
	QqNumber      string
	QqVersion     int64
	Status        string
	MemberOpenid  pgtype.Text
	JoinRequestID pgtype.Text
	FailureReason pgtype.Text
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	ApprovedAt    pgtype.Timestamptz
	BoundAt       pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListQQGroupApplications(ctx context.Context, arg ListQQGroupApplicationsParams) ([]ListQQGroupApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listQQGroupApplications, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQQGroupApplicationsRow{}
	for rows.Next() {
		var i ListQQGroupApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupOpenid,
			&i.QqNumber,
			&i.QqVersion,
			&i.Status,
			&i.MemberOpenid,
			&i.JoinRequestID,
			&i.FailureReason,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ApprovedAt,
			&i.BoundAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQQGroupSettings = `-- name: ListQQGroupSettings :many
SELECT group_openid,label,enabled,created_at,updated_at
FROM community_qq_group_settings
ORDER BY created_at ASC, group_openid ASC
`

func (q *Queries) ListQQGroupSettings(ctx context.Context) ([]CommunityQqGroupSetting, error) {
	rows, err := q.db.Query(ctx, listQQGroupSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommunityQqGroupSetting{}
	for rows.Next() {
		var i CommunityQqGroupSetting
		if err := rows.Scan(
			&i.GroupOpenid,
			&i.Label,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveQQGroupApplication = `-- name: LockActiveQQGroupApplication :one
SELECT id,user_id,group_openid,qq_number,qq_version,code_hash,status,member_openid,join_request_id,
 failure_reason,created_at,expires_at,approved_at,bound_at,updated_at
FROM community_qq_group_applications
WHERE user_id=$1 AND group_openid=$2 AND status IN ('pending','approving','approved','bound')
ORDER BY created_at DESC LIMIT 1 FOR UPDATE
`

type LockActiveQQGroupApplicationParams struct {
	UserID      pgtype.UUID
	GroupOpenid string
}

func (q *Queries) LockActiveQQGroupApplication(ctx context.Context, arg LockActiveQQGroupApplicationParams) (CommunityQqGroupApplication, error) {
	row := q.db.QueryRow(ctx, lockActiveQQGroupApplication, arg.UserID, arg.GroupOpenid)
	var i CommunityQqGroupApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupOpenid,
		&i.QqNumber,
		&i.QqVersion,
		&i.CodeHash,
		&i.Status,
		&i.MemberOpenid,
		&i.JoinRequestID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.BoundAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockQQGroupApplication = `-- name: LockQQGroupApplication :one
SELECT id,user_id,group_openid,qq_number,qq_version,code_hash,status,member_openid,join_request_id,
 failure_reason,created_at,expires_at,approved_at,bound_at,updated_at
FROM community_qq_group_applications WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockQQGroupApplication(ctx context.Context, id int64) (CommunityQqGroupApplication, error) {
	row := q.db.QueryRow(ctx, lockQQGroupApplication, id)
	var i CommunityQqGroupApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupOpenid,
		&i.QqNumber,
		&i.QqVersion,
		&i.CodeHash,
		&i.Status,
		&i.MemberOpenid,
		&i.JoinRequestID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.BoundAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markQQGroupApplicationApproved = `-- name: MarkQQGroupApplicationApproved :exec
UPDATE community_qq_group_applications
SET status='approved',approved_at=now(),failure_reason=NULL,updated_at=now()
WHERE id=$1 AND status='approving'
`

func (q *Queries) MarkQQGroupApplicationApproved(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markQQGroupApplicationApproved, id)
	return err
}

const markQQGroupApplicationApproving = `-- name: MarkQQGroupApplicationApproving :exec
UPDATE community_qq_group_applications
SET status='approving',member_openid=$2,join_request_id=$3,updated_at=now()
WHERE id=$1 AND status='pending'
`

type MarkQQGroupApplicationApprovingParams struct {
	ID            int64
	MemberOpenid  pgtype.Text
	JoinRequestID pgtype.Text
}

func (q *Queries) MarkQQGroupApplicationApproving(ctx context.Context, arg MarkQQGroupApplicationApprovingParams) error {
	_, err := q.db.Exec(ctx, markQQGroupApplicationApproving, arg.ID, arg.MemberOpenid, arg.JoinRequestID)
	return err
}

const markQQGroupApplicationBound = `-- name: MarkQQGroupApplicationBound :exec
UPDATE community_qq_group_applications
SET status='bound',bound_at=now(),updated_at=now()
WHERE id=$1 AND status='approved'
`

func (q *Queries) MarkQQGroupApplicationBound(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markQQGroupApplicationBound, id)
	return err
}

const markQQGroupApplicationFailed = `-- name: MarkQQGroupApplicationFailed :exec
UPDATE community_qq_group_applications
SET status='failed',failure_reason=$2,updated_at=now()
WHERE id=$1 AND status IN ('approving','pending')
`

type MarkQQGroupApplicationFailedParams struct {
	ID            int64
	FailureReason pgtype.Text
}

func (q *Queries) MarkQQGroupApplicationFailed(ctx context.Context, arg MarkQQGroupApplicationFailedParams) error {
	_, err := q.db.Exec(ctx, markQQGroupApplicationFailed, arg.ID, arg.FailureReason)
	return err
}

const markQQGroupApplicationRejected = `-- name: MarkQQGroupApplicationRejected :exec
UPDATE community_qq_group_applications
SET status='rejected',failure_reason=$2,updated_at=now()
WHERE id=$1 AND status IN ('pending','approving')
`

type MarkQQGroupApplicationRejectedParams struct {
	ID            int64
	FailureReason pgtype.Text
}

func (q *Queries) MarkQQGroupApplicationRejected(ctx context.Context, arg MarkQQGroupApplicationRejectedParams) error {
	_, err := q.db.Exec(ctx, markQQGroupApplicationRejected, arg.ID, arg.FailureReason)
	return err
}

const markQQGroupSettingsInitialized = `-- name: MarkQQGroupSettingsInitialized :exec
INSERT INTO community_qq_group_settings_meta(id,updated_at) VALUES(true,now())
ON CONFLICT(id) DO UPDATE SET updated_at=EXCLUDED.updated_at
`

func (q *Queries) MarkQQGroupSettingsInitialized(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markQQGroupSettingsInitialized)
	return err
}

const qQBotSettingsInitialized = `-- name: QQBotSettingsInitialized :one
SELECT EXISTS(SELECT 1 FROM community_qq_bot_settings WHERE id=true)
`

func (q *Queries) QQBotSettingsInitialized(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, qQBotSettingsInitialized)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const qQGroupSettingsInitialized = `-- name: QQGroupSettingsInitialized :one
SELECT EXISTS(SELECT 1 FROM community_qq_group_settings_meta WHERE id=true)
`

func (q *Queries) QQGroupSettingsInitialized(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, qQGroupSettingsInitialized)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const replaceQQGroupSettings = `-- name: ReplaceQQGroupSettings :exec
DELETE FROM community_qq_group_settings
`

func (q *Queries) ReplaceQQGroupSettings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, replaceQQGroupSettings)
	return err
}

const upsertQQBotSettings = `-- name: UpsertQQBotSettings :exec
INSERT INTO community_qq_bot_settings(id,app_id,api_base,secret_ciphertext,updated_at)
VALUES(true,$1,$2,$3,now())
ON CONFLICT(id) DO UPDATE SET app_id=EXCLUDED.app_id,api_base=EXCLUDED.api_base,
 secret_ciphertext=EXCLUDED.secret_ciphertext,updated_at=EXCLUDED.updated_at
`

type UpsertQQBotSettingsParams struct {
	AppID            string
	ApiBase          string
	SecretCiphertext []byte
}

func (q *Queries) UpsertQQBotSettings(ctx context.Context, arg UpsertQQBotSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertQQBotSettings, arg.AppID, arg.ApiBase, arg.SecretCiphertext)
	return err
}
