// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qqofficial.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findQQBinding = `-- name: FindQQBinding :one
SELECT user_id,openid,qq_version FROM community_qq_bindings WHERE openid=$1
`

type FindQQBindingRow struct {
	UserID    pgtype.UUID
	Openid    string
	QqVersion int64
}

func (q *Queries) FindQQBinding(ctx context.Context, openid string) (FindQQBindingRow, error) {
	row := q.db.QueryRow(ctx, findQQBinding, openid)
	var i FindQQBindingRow
	err := row.Scan(&i.UserID, &i.Openid, &i.QqVersion)
	return i, err
}

const insertQQChallenge = `-- name: InsertQQChallenge :exec
INSERT INTO community_qq_link_challenges(user_id,code_hash,qq_version,expires_at) VALUES($1,$2,$3,$4)
`

type InsertQQChallengeParams struct {
	UserID    pgtype.UUID
	CodeHash  []byte
	QqVersion int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertQQChallenge(ctx context.Context, arg InsertQQChallengeParams) error {
	_, err := q.db.Exec(ctx, insertQQChallenge,
		arg.UserID,
		arg.CodeHash,
		arg.QqVersion,
		arg.ExpiresAt,
	)
	return err
}

const invalidateQQChallenges = `-- name: InvalidateQQChallenges :exec
UPDATE community_qq_link_challenges SET used_at=COALESCE(used_at,now()) WHERE user_id=$1 AND used_at IS NULL
`

func (q *Queries) InvalidateQQChallenges(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidateQQChallenges, userID)
	return err
}

const lockQQChallenge = `-- name: LockQQChallenge :one
SELECT id,user_id,qq_version,expires_at,used_at FROM community_qq_link_challenges WHERE code_hash=$1 FOR UPDATE
`

type LockQQChallengeRow struct {
	ID        int64
	UserID    pgtype.UUID
	QqVersion int64
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

func (q *Queries) LockQQChallenge(ctx context.Context, codeHash []byte) (LockQQChallengeRow, error) {
	row := q.db.QueryRow(ctx, lockQQChallenge, codeHash)
	var i LockQQChallengeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QqVersion,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markQQChallengeUsed = `-- name: MarkQQChallengeUsed :exec
UPDATE community_qq_link_challenges SET used_at=now() WHERE id=$1 AND used_at IS NULL
`

func (q *Queries) MarkQQChallengeUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markQQChallengeUsed, id)
	return err
}

const upsertQQBinding = `-- name: UpsertQQBinding :exec
INSERT INTO community_qq_bindings(user_id,openid,qq_version) VALUES($1,$2,$3)
ON CONFLICT(user_id) DO UPDATE SET openid=EXCLUDED.openid,qq_version=EXCLUDED.qq_version,bound_at=now()
`

type UpsertQQBindingParams struct {
	UserID    pgtype.UUID
	Openid    string
	QqVersion int64
}

func (q *Queries) UpsertQQBinding(ctx context.Context, arg UpsertQQBindingParams) error {
	_, err := q.db.Exec(ctx, upsertQQBinding, arg.UserID, arg.Openid, arg.QqVersion)
	return err
}
