// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package store

import (
	"context"
)

const getPlatformMetadata = `-- name: GetPlatformMetadata :one
SELECT schema_version, environment FROM platform_metadata WHERE singleton = true
`

type GetPlatformMetadataRow struct {
	SchemaVersion int32
	Environment   string
}

func (q *Queries) GetPlatformMetadata(ctx context.Context) (GetPlatformMetadataRow, error) {
	row := q.db.QueryRow(ctx, getPlatformMetadata)
	var i GetPlatformMetadataRow
	err := row.Scan(&i.SchemaVersion, &i.Environment)
	return i, err
}
