// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fittings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraft = `-- name: CreateDraft :one
INSERT INTO fittings_drafts(account_id,name,fit,request_key) VALUES($1,$2,$3,$4) ON CONFLICT(account_id,request_key) DO UPDATE SET request_key=excluded.request_key RETURNING id, account_id, name, fit, version, request_key, created_at, updated_at, original_account_id
`

type CreateDraftParams struct {
	AccountID  pgtype.UUID
	Name       string
	Fit        []byte
	RequestKey pgtype.UUID
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (FittingsDraft, error) {
	row := q.db.QueryRow(ctx, createDraft,
		arg.AccountID,
		arg.Name,
		arg.Fit,
		arg.RequestKey,
	)
	var i FittingsDraft
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Fit,
		&i.Version,
		&i.RequestKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalAccountID,
	)
	return i, err
}

const deleteDraft = `-- name: DeleteDraft :execrows
DELETE FROM fittings_drafts WHERE id=$1 AND account_id=$2 AND version=$3
`

type DeleteDraftParams struct {
	ID        int64
	AccountID pgtype.UUID
	Version   int64
}

func (q *Queries) DeleteDraft(ctx context.Context, arg DeleteDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraft, arg.ID, arg.AccountID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDraft = `-- name: GetDraft :one
SELECT id, account_id, name, fit, version, request_key, created_at, updated_at, original_account_id FROM fittings_drafts WHERE id=$1
`

func (q *Queries) GetDraft(ctx context.Context, id int64) (FittingsDraft, error) {
	row := q.db.QueryRow(ctx, getDraft, id)
	var i FittingsDraft
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Fit,
		&i.Version,
		&i.RequestKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalAccountID,
	)
	return i, err
}

const listDrafts = `-- name: ListDrafts :many
SELECT id,name,version,updated_at FROM fittings_drafts WHERE account_id=$1 AND id<$2 ORDER BY id DESC LIMIT 31
`

type ListDraftsParams struct {
	AccountID pgtype.UUID
	BeforeID  int64
}

type ListDraftsRow struct {
	ID        int64
	Name      string
	Version   int64
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListDrafts(ctx context.Context, arg ListDraftsParams) ([]ListDraftsRow, error) {
	rows, err := q.db.Query(ctx, listDrafts, arg.AccountID, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftsRow{}
	for rows.Next() {
		var i ListDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDraft = `-- name: UpdateDraft :one
UPDATE fittings_drafts SET name=$3,fit=$4,version=version+1,updated_at=now() WHERE id=$1 AND account_id=$2 AND version=$5 RETURNING id, account_id, name, fit, version, request_key, created_at, updated_at, original_account_id
`

type UpdateDraftParams struct {
	ID        int64
	AccountID pgtype.UUID
	Name      string
	Fit       []byte
	Version   int64
}

func (q *Queries) UpdateDraft(ctx context.Context, arg UpdateDraftParams) (FittingsDraft, error) {
	row := q.db.QueryRow(ctx, updateDraft,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.Fit,
		arg.Version,
	)
	var i FittingsDraft
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Fit,
		&i.Version,
		&i.RequestKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalAccountID,
	)
	return i, err
}
