// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FittingsDraft struct {
	ID                int64
	AccountID         pgtype.UUID
	Name              string
	Fit               []byte
	Version           int64
	RequestKey        pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	OriginalAccountID pgtype.UUID
}
