// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const corporationSnapshot = `-- name: CorporationSnapshot :one
SELECT corporation_id,corporation_name,alliance_id,ceo_id FROM eve_role_snapshots
WHERE corporation_id=$1 AND valid_until>now() ORDER BY synced_at DESC LIMIT 1
`

type CorporationSnapshotRow struct {
	CorporationID   int64
	CorporationName string
	AllianceID      int64
	CeoID           int64
}

func (q *Queries) CorporationSnapshot(ctx context.Context, corporationID int64) (CorporationSnapshotRow, error) {
	row := q.db.QueryRow(ctx, corporationSnapshot, corporationID)
	var i CorporationSnapshotRow
	err := row.Scan(
		&i.CorporationID,
		&i.CorporationName,
		&i.AllianceID,
		&i.CeoID,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM eve_credentials WHERE character_id=$1
`

func (q *Queries) DeleteCredential(ctx context.Context, characterID int64) error {
	_, err := q.db.Exec(ctx, deleteCredential, characterID)
	return err
}

const getAuthorization = `-- name: GetAuthorization :one
SELECT c.state,c.owner_hash,c.scopes,s.corporation_id,s.corporation_name,s.alliance_id,s.ceo_id,s.roles,s.roles_at_hq,s.roles_at_base,s.roles_at_other,s.synced_at,s.valid_until
FROM eve_credentials c LEFT JOIN eve_role_snapshots s USING(character_id) WHERE c.character_id=$1
`

type GetAuthorizationRow struct {
	State           string
	OwnerHash       []byte
	Scopes          []string
	CorporationID   pgtype.Int8
	CorporationName pgtype.Text
	AllianceID      pgtype.Int8
	CeoID           pgtype.Int8
	Roles           []string
	RolesAtHq       []string
	RolesAtBase     []string
	RolesAtOther    []string
	SyncedAt        pgtype.Timestamptz
	ValidUntil      pgtype.Timestamptz
}

func (q *Queries) GetAuthorization(ctx context.Context, characterID int64) (GetAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, getAuthorization, characterID)
	var i GetAuthorizationRow
	err := row.Scan(
		&i.State,
		&i.OwnerHash,
		&i.Scopes,
		&i.CorporationID,
		&i.CorporationName,
		&i.AllianceID,
		&i.CeoID,
		&i.Roles,
		&i.RolesAtHq,
		&i.RolesAtBase,
		&i.RolesAtOther,
		&i.SyncedAt,
		&i.ValidUntil,
	)
	return i, err
}

const invalidateSnapshot = `-- name: InvalidateSnapshot :exec
DELETE FROM eve_role_snapshots WHERE character_id=$1
`

func (q *Queries) InvalidateSnapshot(ctx context.Context, characterID int64) error {
	_, err := q.db.Exec(ctx, invalidateSnapshot, characterID)
	return err
}

const nextCredential = `-- name: NextCredential :one
SELECT character_id, owner_hash, sealed, state, next_sync_at, updated_at, scopes, grant_generation, refresh_revision, roles_not_before FROM eve_credentials WHERE state <> 'reauthorize' AND next_sync_at <= now()
ORDER BY next_sync_at, character_id LIMIT 1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) NextCredential(ctx context.Context) (EveCredential, error) {
	row := q.db.QueryRow(ctx, nextCredential)
	var i EveCredential
	err := row.Scan(
		&i.CharacterID,
		&i.OwnerHash,
		&i.Sealed,
		&i.State,
		&i.NextSyncAt,
		&i.UpdatedAt,
		&i.Scopes,
		&i.GrantGeneration,
		&i.RefreshRevision,
		&i.RolesNotBefore,
	)
	return i, err
}

const revokeCredential = `-- name: RevokeCredential :exec
UPDATE eve_credentials SET state='reauthorize', sealed=''::bytea, scopes='{}' WHERE character_id=$1
`

func (q *Queries) RevokeCredential(ctx context.Context, characterID int64) error {
	_, err := q.db.Exec(ctx, revokeCredential, characterID)
	return err
}

const saveCredential = `-- name: SaveCredential :exec
INSERT INTO eve_credentials(character_id, owner_hash, sealed, scopes) VALUES ($1,$2,$3,$4)
ON CONFLICT(character_id) DO UPDATE SET owner_hash=excluded.owner_hash, sealed=excluded.sealed,
state=CASE WHEN eve_credentials.owner_hash=excluded.owner_hash AND eve_credentials.state IN ('ready','retry') THEN eve_credentials.state ELSE 'pending' END,
next_sync_at=CASE WHEN eve_credentials.owner_hash=excluded.owner_hash AND eve_credentials.state <> 'reauthorize' THEN greatest(eve_credentials.next_sync_at,now()) ELSE now() END,
updated_at=now(), scopes=excluded.scopes
`

type SaveCredentialParams struct {
	CharacterID int64
	OwnerHash   []byte
	Sealed      []byte
	Scopes      []string
}

func (q *Queries) SaveCredential(ctx context.Context, arg SaveCredentialParams) error {
	_, err := q.db.Exec(ctx, saveCredential,
		arg.CharacterID,
		arg.OwnerHash,
		arg.Sealed,
		arg.Scopes,
	)
	return err
}

const saveSnapshot = `-- name: SaveSnapshot :exec
INSERT INTO eve_role_snapshots(character_id,owner_hash,corporation_id,corporation_name,alliance_id,ceo_id,roles,roles_at_hq,roles_at_base,roles_at_other,synced_at,valid_until)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
ON CONFLICT(character_id) DO UPDATE SET owner_hash=excluded.owner_hash, corporation_id=excluded.corporation_id,
corporation_name=excluded.corporation_name, alliance_id=excluded.alliance_id, ceo_id=excluded.ceo_id,
roles=excluded.roles, roles_at_hq=excluded.roles_at_hq, roles_at_base=excluded.roles_at_base,
roles_at_other=excluded.roles_at_other, synced_at=excluded.synced_at, valid_until=excluded.valid_until
`

type SaveSnapshotParams struct {
	CharacterID     int64
	OwnerHash       []byte
	CorporationID   int64
	CorporationName string
	AllianceID      int64
	CeoID           int64
	Roles           []string
	RolesAtHq       []string
	RolesAtBase     []string
	RolesAtOther    []string
	SyncedAt        pgtype.Timestamptz
	ValidUntil      pgtype.Timestamptz
}

func (q *Queries) SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) error {
	_, err := q.db.Exec(ctx, saveSnapshot,
		arg.CharacterID,
		arg.OwnerHash,
		arg.CorporationID,
		arg.CorporationName,
		arg.AllianceID,
		arg.CeoID,
		arg.Roles,
		arg.RolesAtHq,
		arg.RolesAtBase,
		arg.RolesAtOther,
		arg.SyncedAt,
		arg.ValidUntil,
	)
	return err
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE eve_credentials SET sealed=$2, state=$3, next_sync_at=$4, scopes=$5, updated_at=now() WHERE character_id=$1
`

type UpdateCredentialParams struct {
	CharacterID int64
	Sealed      []byte
	State       string
	NextSyncAt  pgtype.Timestamptz
	Scopes      []string
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential,
		arg.CharacterID,
		arg.Sealed,
		arg.State,
		arg.NextSyncAt,
		arg.Scopes,
	)
	return err
}
