// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contract_read.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const readContractBids = `-- name: ReadContractBids :many
SELECT owner_kind,owner_id,contract_id,bid_id,bidder_id,amount::text AS amount,date_bid FROM eve_contract_bids WHERE owner_kind=$1 AND owner_id=$2 AND contract_id=$3 AND bid_id<$4 ORDER BY bid_id DESC LIMIT 101
`

type ReadContractBidsParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
	BidID      int64
}

type ReadContractBidsRow struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
	BidID      int64
	BidderID   int64
	Amount     string
	DateBid    pgtype.Timestamptz
}

func (q *Queries) ReadContractBids(ctx context.Context, arg ReadContractBidsParams) ([]ReadContractBidsRow, error) {
	rows, err := q.db.Query(ctx, readContractBids,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContractID,
		arg.BidID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadContractBidsRow{}
	for rows.Next() {
		var i ReadContractBidsRow
		if err := rows.Scan(
			&i.OwnerKind,
			&i.OwnerID,
			&i.ContractID,
			&i.BidID,
			&i.BidderID,
			&i.Amount,
			&i.DateBid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readContractCorporations = `-- name: ReadContractCorporations :many
SELECT DISTINCT ON (corporation_id) corporation_id,corporation_name,alliance_id,ceo_id
FROM eve_role_snapshots WHERE valid_until>now() ORDER BY corporation_id,synced_at DESC
`

type ReadContractCorporationsRow struct {
	CorporationID   int64
	CorporationName string
	AllianceID      int64
	CeoID           int64
}

func (q *Queries) ReadContractCorporations(ctx context.Context) ([]ReadContractCorporationsRow, error) {
	rows, err := q.db.Query(ctx, readContractCorporations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadContractCorporationsRow{}
	for rows.Next() {
		var i ReadContractCorporationsRow
		if err := rows.Scan(
			&i.CorporationID,
			&i.CorporationName,
			&i.AllianceID,
			&i.CeoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readContractDetailStates = `-- name: ReadContractDetailStates :many
SELECT part,state,reason,last_success_at FROM eve_contract_details WHERE owner_kind=$1 AND owner_id=$2 AND contract_id=$3 ORDER BY part
`

type ReadContractDetailStatesParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
}

type ReadContractDetailStatesRow struct {
	Part          string
	State         string
	Reason        string
	LastSuccessAt pgtype.Timestamptz
}

func (q *Queries) ReadContractDetailStates(ctx context.Context, arg ReadContractDetailStatesParams) ([]ReadContractDetailStatesRow, error) {
	rows, err := q.db.Query(ctx, readContractDetailStates, arg.OwnerKind, arg.OwnerID, arg.ContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadContractDetailStatesRow{}
	for rows.Next() {
		var i ReadContractDetailStatesRow
		if err := rows.Scan(
			&i.Part,
			&i.State,
			&i.Reason,
			&i.LastSuccessAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readContractItems = `-- name: ReadContractItems :many
SELECT owner_kind, owner_id, contract_id, record_id, type_id, quantity, is_included, is_singleton, raw_quantity FROM eve_contract_items WHERE owner_kind=$1 AND owner_id=$2 AND contract_id=$3 AND record_id>$4 ORDER BY record_id LIMIT 101
`

type ReadContractItemsParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
	RecordID   int64
}

func (q *Queries) ReadContractItems(ctx context.Context, arg ReadContractItemsParams) ([]EveContractItem, error) {
	rows, err := q.db.Query(ctx, readContractItems,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContractID,
		arg.RecordID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EveContractItem{}
	for rows.Next() {
		var i EveContractItem
		if err := rows.Scan(
			&i.OwnerKind,
			&i.OwnerID,
			&i.ContractID,
			&i.RecordID,
			&i.TypeID,
			&i.Quantity,
			&i.IsIncluded,
			&i.IsSingleton,
			&i.RawQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readContractList = `-- name: ReadContractList :many
SELECT owner_kind, owner_id, contract_id, source_character_id, source_generation, contract_type, status, payload, checked_at, in_scope FROM eve_contracts
WHERE owner_kind=$1 AND owner_id=$2
AND in_scope
AND contract_id<$3
AND ($4::text='' OR status=$4)
AND ($5::text='' OR contract_type=$5)
AND ($6::text='' OR strpos(lower(coalesce(payload->>'title','')),lower($6))>0 OR contract_id::text=$6)
ORDER BY contract_id DESC LIMIT 26
`

type ReadContractListParams struct {
	OwnerKind string
	OwnerID   int64
	BeforeID  int64
	Status    string
	Kind      string
	Search    string
}

func (q *Queries) ReadContractList(ctx context.Context, arg ReadContractListParams) ([]EveContract, error) {
	rows, err := q.db.Query(ctx, readContractList,
		arg.OwnerKind,
		arg.OwnerID,
		arg.BeforeID,
		arg.Status,
		arg.Kind,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EveContract{}
	for rows.Next() {
		var i EveContract
		if err := rows.Scan(
			&i.OwnerKind,
			&i.OwnerID,
			&i.ContractID,
			&i.SourceCharacterID,
			&i.SourceGeneration,
			&i.ContractType,
			&i.Status,
			&i.Payload,
			&i.CheckedAt,
			&i.InScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readContractSummaryItems = `-- name: ReadContractSummaryItems :many
WITH types AS (
 SELECT i.contract_id,i.is_included,i.type_id,sum(i.quantity)::text AS quantity,min(i.record_id) AS first_record
 FROM eve_contract_items i
 JOIN eve_contract_details d USING(owner_kind,owner_id,contract_id)
 WHERE i.owner_kind=$1 AND i.owner_id=$2
 AND i.contract_id=ANY($3::bigint[]) AND d.part='items' AND d.state='ready'
 GROUP BY i.contract_id,i.is_included,i.type_id
), ranked AS (
 SELECT contract_id, is_included, type_id, quantity, first_record,count(*) OVER(PARTITION BY contract_id,is_included) AS type_count,
 row_number() OVER(PARTITION BY contract_id,is_included ORDER BY first_record,type_id) AS position
 FROM types
)
SELECT contract_id,is_included,type_id,quantity,type_count FROM ranked WHERE position=1 ORDER BY contract_id,is_included DESC
`

type ReadContractSummaryItemsParams struct {
	OwnerKind   string
	OwnerID     int64
	ContractIds []int64
}

type ReadContractSummaryItemsRow struct {
	ContractID int64
	IsIncluded bool
	TypeID     int64
	Quantity   string
	TypeCount  int64
}

func (q *Queries) ReadContractSummaryItems(ctx context.Context, arg ReadContractSummaryItemsParams) ([]ReadContractSummaryItemsRow, error) {
	rows, err := q.db.Query(ctx, readContractSummaryItems, arg.OwnerKind, arg.OwnerID, arg.ContractIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadContractSummaryItemsRow{}
	for rows.Next() {
		var i ReadContractSummaryItemsRow
		if err := rows.Scan(
			&i.ContractID,
			&i.IsIncluded,
			&i.TypeID,
			&i.Quantity,
			&i.TypeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readEntityNames = `-- name: ReadEntityNames :many
SELECT entity_id, name, category, expires_at, language FROM eve_entity_names WHERE entity_id=ANY($1::bigint[]) AND language=$2 AND expires_at>now()
`

type ReadEntityNamesParams struct {
	Ids      []int64
	Language string
}

func (q *Queries) ReadEntityNames(ctx context.Context, arg ReadEntityNamesParams) ([]EveEntityName, error) {
	rows, err := q.db.Query(ctx, readEntityNames, arg.Ids, arg.Language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EveEntityName{}
	for rows.Next() {
		var i EveEntityName
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Category,
			&i.ExpiresAt,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveEntityName = `-- name: SaveEntityName :exec
INSERT INTO eve_entity_names(entity_id,name,category,language,expires_at) VALUES($1,$2,$3,$4,now()+interval '1 day')
ON CONFLICT(entity_id,language) DO UPDATE SET name=excluded.name,category=excluded.category,expires_at=excluded.expires_at
`

type SaveEntityNameParams struct {
	EntityID int64
	Name     string
	Category string
	Language string
}

func (q *Queries) SaveEntityName(ctx context.Context, arg SaveEntityNameParams) error {
	_, err := q.db.Exec(ctx, saveEntityName,
		arg.EntityID,
		arg.Name,
		arg.Category,
		arg.Language,
	)
	return err
}
