// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contracts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimContractDetail = `-- name: ClaimContractDetail :one
UPDATE eve_contract_details SET lease_until=now()+interval '90 seconds',fence=fence+1,state='running'
WHERE owner_kind=$1 AND owner_id=$2 AND contract_id=$3 AND part=$4 AND generation=$5 AND source_character_id=$6
AND (lease_until IS NULL OR lease_until<now()) RETURNING owner_kind, owner_id, contract_id, part, target_id, source_character_id, generation, state, reason, next_due_at, page, pages, fence, lease_until, last_success_at
`

type ClaimContractDetailParams struct {
	OwnerKind         string
	OwnerID           int64
	ContractID        int64
	Part              string
	Generation        int64
	SourceCharacterID int64
}

func (q *Queries) ClaimContractDetail(ctx context.Context, arg ClaimContractDetailParams) (EveContractDetail, error) {
	row := q.db.QueryRow(ctx, claimContractDetail,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContractID,
		arg.Part,
		arg.Generation,
		arg.SourceCharacterID,
	)
	var i EveContractDetail
	err := row.Scan(
		&i.OwnerKind,
		&i.OwnerID,
		&i.ContractID,
		&i.Part,
		&i.TargetID,
		&i.SourceCharacterID,
		&i.Generation,
		&i.State,
		&i.Reason,
		&i.NextDueAt,
		&i.Page,
		&i.Pages,
		&i.Fence,
		&i.LeaseUntil,
		&i.LastSuccessAt,
	)
	return i, err
}

const contractCorporationSource = `-- name: ContractCorporationSource :one
SELECT c.character_id FROM eve_credentials c JOIN eve_role_snapshots s USING(character_id)
JOIN eve_sync_targets t ON t.character_id=c.character_id AND t.resource='corporation_contracts'
WHERE s.corporation_id=$1 AND s.valid_until>now() AND s.owner_hash=c.owner_hash
AND c.state IN ('ready','retry') AND (c.roles_not_before IS NULL OR c.roles_not_before<=now())
AND 'esi-contracts.read_corporation_contracts.v1'=ANY(c.scopes) AND t.state<>'blocked'
ORDER BY c.character_id LIMIT 1
`

func (q *Queries) ContractCorporationSource(ctx context.Context, corporationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, contractCorporationSource, corporationID)
	var character_id int64
	err := row.Scan(&character_id)
	return character_id, err
}

const contractDetailStats = `-- name: ContractDetailStats :one
SELECT count(*) FILTER(WHERE d.state IN ('pending','running'))::integer AS pending,
count(*) FILTER(WHERE d.state IN ('blocked','failed'))::integer AS failed
FROM eve_contract_details d JOIN eve_contracts c USING(owner_kind,owner_id,contract_id)
WHERE d.target_id=$1 AND c.in_scope
`

type ContractDetailStatsRow struct {
	Pending int32
	Failed  int32
}

func (q *Queries) ContractDetailStats(ctx context.Context, targetID int64) (ContractDetailStatsRow, error) {
	row := q.db.QueryRow(ctx, contractDetailStats, targetID)
	var i ContractDetailStatsRow
	err := row.Scan(&i.Pending, &i.Failed)
	return i, err
}

const deleteContractCursor = `-- name: DeleteContractCursor :exec
DELETE FROM eve_contract_cursors WHERE target_id=$1
`

func (q *Queries) DeleteContractCursor(ctx context.Context, targetID int64) error {
	_, err := q.db.Exec(ctx, deleteContractCursor, targetID)
	return err
}

const deletePersonalContracts = `-- name: DeletePersonalContracts :exec
DELETE FROM eve_contracts WHERE owner_kind='character' AND owner_id=$1
`

func (q *Queries) DeletePersonalContracts(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, deletePersonalContracts, ownerID)
	return err
}

const excludeContractDetails = `-- name: ExcludeContractDetails :exec
UPDATE eve_contract_details SET state='blocked',reason='out_of_scope',lease_until=NULL,fence=fence+1
WHERE owner_kind=$1 AND owner_id=$2 AND contract_id=$3 AND reason<>'out_of_scope'
`

type ExcludeContractDetailsParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
}

func (q *Queries) ExcludeContractDetails(ctx context.Context, arg ExcludeContractDetailsParams) error {
	_, err := q.db.Exec(ctx, excludeContractDetails, arg.OwnerKind, arg.OwnerID, arg.ContractID)
	return err
}

const finishContractDetail = `-- name: FinishContractDetail :exec
UPDATE eve_contract_details SET state=$5,reason=$6,next_due_at=$7,page=$8,pages=$9,lease_until=NULL,
last_success_at=CASE WHEN $5='ready' THEN now() ELSE last_success_at END
WHERE owner_kind=$1 AND owner_id=$2 AND contract_id=$3 AND part=$4
`

type FinishContractDetailParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
	Part       string
	State      string
	Reason     string
	NextDueAt  pgtype.Timestamptz
	Page       int32
	Pages      int32
}

func (q *Queries) FinishContractDetail(ctx context.Context, arg FinishContractDetailParams) error {
	_, err := q.db.Exec(ctx, finishContractDetail,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContractID,
		arg.Part,
		arg.State,
		arg.Reason,
		arg.NextDueAt,
		arg.Page,
		arg.Pages,
	)
	return err
}

const getContract = `-- name: GetContract :one
SELECT owner_kind, owner_id, contract_id, source_character_id, source_generation, contract_type, status, payload, checked_at, in_scope FROM eve_contracts WHERE owner_kind=$1 AND owner_id=$2 AND contract_id=$3 AND in_scope
`

type GetContractParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
}

func (q *Queries) GetContract(ctx context.Context, arg GetContractParams) (EveContract, error) {
	row := q.db.QueryRow(ctx, getContract, arg.OwnerKind, arg.OwnerID, arg.ContractID)
	var i EveContract
	err := row.Scan(
		&i.OwnerKind,
		&i.OwnerID,
		&i.ContractID,
		&i.SourceCharacterID,
		&i.SourceGeneration,
		&i.ContractType,
		&i.Status,
		&i.Payload,
		&i.CheckedAt,
		&i.InScope,
	)
	return i, err
}

const getContractCursor = `-- name: GetContractCursor :one
SELECT target_id, generation, owner_id, page, pages, expires_at FROM eve_contract_cursors WHERE target_id=$1
`

func (q *Queries) GetContractCursor(ctx context.Context, targetID int64) (EveContractCursor, error) {
	row := q.db.QueryRow(ctx, getContractCursor, targetID)
	var i EveContractCursor
	err := row.Scan(
		&i.TargetID,
		&i.Generation,
		&i.OwnerID,
		&i.Page,
		&i.Pages,
		&i.ExpiresAt,
	)
	return i, err
}

const getContractDetail = `-- name: GetContractDetail :one
SELECT owner_kind, owner_id, contract_id, part, target_id, source_character_id, generation, state, reason, next_due_at, page, pages, fence, lease_until, last_success_at FROM eve_contract_details WHERE owner_kind=$1 AND owner_id=$2 AND contract_id=$3 AND part=$4
`

type GetContractDetailParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
	Part       string
}

func (q *Queries) GetContractDetail(ctx context.Context, arg GetContractDetailParams) (EveContractDetail, error) {
	row := q.db.QueryRow(ctx, getContractDetail,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContractID,
		arg.Part,
	)
	var i EveContractDetail
	err := row.Scan(
		&i.OwnerKind,
		&i.OwnerID,
		&i.ContractID,
		&i.Part,
		&i.TargetID,
		&i.SourceCharacterID,
		&i.Generation,
		&i.State,
		&i.Reason,
		&i.NextDueAt,
		&i.Page,
		&i.Pages,
		&i.Fence,
		&i.LeaseUntil,
		&i.LastSuccessAt,
	)
	return i, err
}

const insertContractBids = `-- name: InsertContractBids :exec
INSERT INTO eve_contract_bids(owner_kind,owner_id,contract_id,bid_id,bidder_id,amount,date_bid)
SELECT $1,$2,$3,x.bid_id,x.bidder_id,x.amount,x.date_bid FROM jsonb_to_recordset($4::jsonb)
AS x(bid_id bigint,bidder_id bigint,amount numeric,date_bid timestamptz)
ON CONFLICT(owner_kind,owner_id,contract_id,bid_id) DO UPDATE SET amount=excluded.amount,date_bid=excluded.date_bid,bidder_id=excluded.bidder_id
`

type InsertContractBidsParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
	Bids       []byte
}

func (q *Queries) InsertContractBids(ctx context.Context, arg InsertContractBidsParams) error {
	_, err := q.db.Exec(ctx, insertContractBids,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContractID,
		arg.Bids,
	)
	return err
}

const insertContractItems = `-- name: InsertContractItems :exec
INSERT INTO eve_contract_items(owner_kind,owner_id,contract_id,record_id,type_id,quantity,is_included,is_singleton,raw_quantity)
SELECT $1,$2,$3,x.record_id,x.type_id,x.quantity,x.is_included,x.is_singleton,x.raw_quantity FROM jsonb_to_recordset($4::jsonb)
AS x(record_id bigint,type_id bigint,quantity bigint,is_included boolean,is_singleton boolean,raw_quantity bigint)
`

type InsertContractItemsParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
	Items      []byte
}

func (q *Queries) InsertContractItems(ctx context.Context, arg InsertContractItemsParams) error {
	_, err := q.db.Exec(ctx, insertContractItems,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContractID,
		arg.Items,
	)
	return err
}

const lockContractDetail = `-- name: LockContractDetail :one
SELECT owner_kind, owner_id, contract_id, part, target_id, source_character_id, generation, state, reason, next_due_at, page, pages, fence, lease_until, last_success_at FROM eve_contract_details WHERE owner_kind=$1 AND owner_id=$2 AND contract_id=$3 AND part=$4 FOR UPDATE
`

type LockContractDetailParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
	Part       string
}

func (q *Queries) LockContractDetail(ctx context.Context, arg LockContractDetailParams) (EveContractDetail, error) {
	row := q.db.QueryRow(ctx, lockContractDetail,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContractID,
		arg.Part,
	)
	var i EveContractDetail
	err := row.Scan(
		&i.OwnerKind,
		&i.OwnerID,
		&i.ContractID,
		&i.Part,
		&i.TargetID,
		&i.SourceCharacterID,
		&i.Generation,
		&i.State,
		&i.Reason,
		&i.NextDueAt,
		&i.Page,
		&i.Pages,
		&i.Fence,
		&i.LeaseUntil,
		&i.LastSuccessAt,
	)
	return i, err
}

const prepareContractDetail = `-- name: PrepareContractDetail :one
INSERT INTO eve_contract_details(owner_kind,owner_id,contract_id,part,target_id,source_character_id,generation)
VALUES($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT(owner_kind,owner_id,contract_id,part) DO UPDATE SET
 target_id=excluded.target_id,source_character_id=excluded.source_character_id,generation=excluded.generation,
 state=CASE WHEN eve_contract_details.part='items' AND eve_contract_details.last_success_at IS NOT NULL THEN 'ready' WHEN eve_contract_details.reason='out_of_scope' OR eve_contract_details.source_character_id<>excluded.source_character_id OR eve_contract_details.generation<>excluded.generation THEN 'pending' ELSE eve_contract_details.state END,
 next_due_at=CASE WHEN eve_contract_details.reason='out_of_scope' THEN now() ELSE eve_contract_details.next_due_at END,
 page=CASE WHEN eve_contract_details.source_character_id<>excluded.source_character_id OR eve_contract_details.generation<>excluded.generation THEN 1 ELSE eve_contract_details.page END,
 pages=CASE WHEN eve_contract_details.source_character_id<>excluded.source_character_id OR eve_contract_details.generation<>excluded.generation THEN 0 ELSE eve_contract_details.pages END,
 reason=CASE WHEN eve_contract_details.reason='out_of_scope' OR (eve_contract_details.part='items' AND eve_contract_details.last_success_at IS NOT NULL) OR eve_contract_details.source_character_id<>excluded.source_character_id OR eve_contract_details.generation<>excluded.generation THEN '' ELSE eve_contract_details.reason END,
 lease_until=CASE WHEN eve_contract_details.source_character_id<>excluded.source_character_id OR eve_contract_details.generation<>excluded.generation THEN NULL ELSE eve_contract_details.lease_until END
RETURNING owner_kind, owner_id, contract_id, part, target_id, source_character_id, generation, state, reason, next_due_at, page, pages, fence, lease_until, last_success_at
`

type PrepareContractDetailParams struct {
	OwnerKind         string
	OwnerID           int64
	ContractID        int64
	Part              string
	TargetID          int64
	SourceCharacterID int64
	Generation        int64
}

func (q *Queries) PrepareContractDetail(ctx context.Context, arg PrepareContractDetailParams) (EveContractDetail, error) {
	row := q.db.QueryRow(ctx, prepareContractDetail,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContractID,
		arg.Part,
		arg.TargetID,
		arg.SourceCharacterID,
		arg.Generation,
	)
	var i EveContractDetail
	err := row.Scan(
		&i.OwnerKind,
		&i.OwnerID,
		&i.ContractID,
		&i.Part,
		&i.TargetID,
		&i.SourceCharacterID,
		&i.Generation,
		&i.State,
		&i.Reason,
		&i.NextDueAt,
		&i.Page,
		&i.Pages,
		&i.Fence,
		&i.LeaseUntil,
		&i.LastSuccessAt,
	)
	return i, err
}

const queueContractDetail = `-- name: QueueContractDetail :exec
UPDATE eve_contract_details SET state='pending',reason='' WHERE owner_kind=$1 AND owner_id=$2 AND contract_id=$3 AND part=$4 AND state<>'running'
`

type QueueContractDetailParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
	Part       string
}

func (q *Queries) QueueContractDetail(ctx context.Context, arg QueueContractDetailParams) error {
	_, err := q.db.Exec(ctx, queueContractDetail,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContractID,
		arg.Part,
	)
	return err
}

const replaceContractItems = `-- name: ReplaceContractItems :exec
DELETE FROM eve_contract_items WHERE owner_kind=$1 AND owner_id=$2 AND contract_id=$3
`

type ReplaceContractItemsParams struct {
	OwnerKind  string
	OwnerID    int64
	ContractID int64
}

func (q *Queries) ReplaceContractItems(ctx context.Context, arg ReplaceContractItemsParams) error {
	_, err := q.db.Exec(ctx, replaceContractItems, arg.OwnerKind, arg.OwnerID, arg.ContractID)
	return err
}

const saveContractCursor = `-- name: SaveContractCursor :exec
INSERT INTO eve_contract_cursors(target_id,generation,owner_id,page,pages,expires_at) VALUES($1,$2,$3,$4,$5,$6)
ON CONFLICT(target_id) DO UPDATE SET generation=excluded.generation,owner_id=excluded.owner_id,page=excluded.page,pages=excluded.pages,expires_at=excluded.expires_at
`

type SaveContractCursorParams struct {
	TargetID   int64
	Generation int64
	OwnerID    int64
	Page       int32
	Pages      int32
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) SaveContractCursor(ctx context.Context, arg SaveContractCursorParams) error {
	_, err := q.db.Exec(ctx, saveContractCursor,
		arg.TargetID,
		arg.Generation,
		arg.OwnerID,
		arg.Page,
		arg.Pages,
		arg.ExpiresAt,
	)
	return err
}

const upsertContract = `-- name: UpsertContract :one
INSERT INTO eve_contracts(owner_kind,owner_id,contract_id,source_character_id,source_generation,contract_type,status,payload)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT(owner_kind,owner_id,contract_id) DO UPDATE SET source_character_id=excluded.source_character_id,
 source_generation=excluded.source_generation,contract_type=excluded.contract_type,status=excluded.status,payload=excluded.payload,checked_at=now()
RETURNING in_scope
`

type UpsertContractParams struct {
	OwnerKind         string
	OwnerID           int64
	ContractID        int64
	SourceCharacterID int64
	SourceGeneration  int64
	ContractType      string
	Status            string
	Payload           []byte
}

func (q *Queries) UpsertContract(ctx context.Context, arg UpsertContractParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertContract,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContractID,
		arg.SourceCharacterID,
		arg.SourceGeneration,
		arg.ContractType,
		arg.Status,
		arg.Payload,
	)
	var in_scope bool
	err := row.Scan(&in_scope)
	return in_scope, err
}
