// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flows.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeFlow = `-- name: ConsumeFlow :one
DELETE FROM eve_login_flows
WHERE state_hash = $1 AND browser_hash = $2 AND session_hash = $3 AND expires_at > now()
RETURNING verifier, requested_scopes, intent, target_user_id, expected_character_id
`

type ConsumeFlowParams struct {
	StateHash   []byte
	BrowserHash []byte
	SessionHash []byte
}

type ConsumeFlowRow struct {
	Verifier            string
	RequestedScopes     []string
	Intent              string
	TargetUserID        pgtype.UUID
	ExpectedCharacterID pgtype.Int8
}

func (q *Queries) ConsumeFlow(ctx context.Context, arg ConsumeFlowParams) (ConsumeFlowRow, error) {
	row := q.db.QueryRow(ctx, consumeFlow, arg.StateHash, arg.BrowserHash, arg.SessionHash)
	var i ConsumeFlowRow
	err := row.Scan(
		&i.Verifier,
		&i.RequestedScopes,
		&i.Intent,
		&i.TargetUserID,
		&i.ExpectedCharacterID,
	)
	return i, err
}

const createFlow = `-- name: CreateFlow :exec
INSERT INTO eve_login_flows (state_hash, browser_hash, session_hash, verifier, requested_scopes) VALUES ($1, $2, $3, $4, $5)
`

type CreateFlowParams struct {
	StateHash       []byte
	BrowserHash     []byte
	SessionHash     []byte
	Verifier        string
	RequestedScopes []string
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) error {
	_, err := q.db.Exec(ctx, createFlow,
		arg.StateHash,
		arg.BrowserHash,
		arg.SessionHash,
		arg.Verifier,
		arg.RequestedScopes,
	)
	return err
}

const pruneFlows = `-- name: PruneFlows :exec
DELETE FROM eve_login_flows WHERE state_hash IN (
  SELECT state_hash FROM eve_login_flows WHERE expires_at <= now() LIMIT 1000
)
`

func (q *Queries) PruneFlows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneFlows)
	return err
}

const removeUserFlows = `-- name: RemoveUserFlows :exec
DELETE FROM eve_login_flows WHERE target_user_id=$1
`

func (q *Queries) RemoveUserFlows(ctx context.Context, targetUserID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeUserFlows, targetUserID)
	return err
}

const setFlowIntent = `-- name: SetFlowIntent :exec
UPDATE eve_login_flows SET intent=$2,target_user_id=$3,expected_character_id=$4 WHERE state_hash=$1
`

type SetFlowIntentParams struct {
	StateHash           []byte
	Intent              string
	TargetUserID        pgtype.UUID
	ExpectedCharacterID pgtype.Int8
}

func (q *Queries) SetFlowIntent(ctx context.Context, arg SetFlowIntentParams) error {
	_, err := q.db.Exec(ctx, setFlowIntent,
		arg.StateHash,
		arg.Intent,
		arg.TargetUserID,
		arg.ExpectedCharacterID,
	)
	return err
}
