// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EveContract struct {
	OwnerKind         string
	OwnerID           int64
	ContractID        int64
	SourceCharacterID int64
	SourceGeneration  int64
	ContractType      string
	Status            string
	Payload           []byte
	CheckedAt         pgtype.Timestamptz
	InScope           bool
}

type EveContractCursor struct {
	TargetID   int64
	Generation int64
	OwnerID    int64
	Page       int32
	Pages      int32
	ExpiresAt  pgtype.Timestamptz
}

type EveContractDetail struct {
	OwnerKind         string
	OwnerID           int64
	ContractID        int64
	Part              string
	TargetID          int64
	SourceCharacterID int64
	Generation        int64
	State             string
	Reason            string
	NextDueAt         pgtype.Timestamptz
	Page              int32
	Pages             int32
	Fence             int64
	LeaseUntil        pgtype.Timestamptz
	LastSuccessAt     pgtype.Timestamptz
}

type EveContractItem struct {
	OwnerKind   string
	OwnerID     int64
	ContractID  int64
	RecordID    int64
	TypeID      int64
	Quantity    int64
	IsIncluded  bool
	IsSingleton bool
	RawQuantity pgtype.Int8
}

type EveCredential struct {
	CharacterID     int64
	OwnerHash       []byte
	Sealed          []byte
	State           string
	NextSyncAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Scopes          []string
	GrantGeneration int64
	RefreshRevision int64
	RolesNotBefore  pgtype.Timestamptz
}

type EveEntityName struct {
	EntityID  int64
	Name      string
	Category  string
	ExpiresAt pgtype.Timestamptz
	Language  string
}

type EveEsiCache struct {
	CacheKey         string
	CharacterID      pgtype.Int8
	Generation       int64
	Body             []byte
	Etag             string
	LastModified     string
	ContentUpdatedAt pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	PageCount        int32
}

type EveEsiLimit struct {
	LimitKey      string
	BlockedUntil  pgtype.Timestamptz
	NextRequestAt pgtype.Timestamptz
	Remaining     int64
	Capacity      int64
	WindowSeconds int64
	ResetAt       pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type EveEsiRouteUsage struct {
	BucketID           int64
	Route              string
	NetworkRequests    int64
	CacheHits          int64
	LocalWaits         int64
	UpstreamLimits     int64
	UsedTokens         int64
	MeasuredResponses  int64
	UnmeasuredRequests int64
	LastStatus         int32
	LastUsed           pgtype.Int8
	LastResponseAt     pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type EveFittingSnapshot struct {
	CharacterID int64
	Resource    string
	Generation  int64
	ObservedAt  pgtype.Timestamptz
	Payload     []byte
}

type EveSyncRun struct {
	ID         int64
	TargetID   int64
	JobID      int64
	Fence      int64
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Outcome    string
	Reason     string
	HttpStatus int32
}

type EveSyncTarget struct {
	ID               int64
	CharacterID      int64
	Resource         string
	Generation       int64
	DisplayName      string
	State            string
	Reason           string
	NextDueAt        pgtype.Timestamptz
	LastAttemptAt    pgtype.Timestamptz
	LastSuccessAt    pgtype.Timestamptz
	ValidUntil       pgtype.Timestamptz
	ContentUpdatedAt pgtype.Timestamptz
	ActiveJobID      pgtype.Int8
	CompletedJobID   pgtype.Int8
	Fence            int64
	LeaseUntil       pgtype.Timestamptz
	Failures         int32
	UpdatedAt        pgtype.Timestamptz
}
