// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: online.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activityCharacters = `-- name: ActivityCharacters :many
SELECT character_id FROM eve_character_profiles WHERE corporation_id=$1 AND valid_until>now() ORDER BY character_id
`

func (q *Queries) ActivityCharacters(ctx context.Context, corporationID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, activityCharacters, corporationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var character_id int64
		if err := rows.Scan(&character_id); err != nil {
			return nil, err
		}
		items = append(items, character_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activityCorporations = `-- name: ActivityCorporations :many
SELECT DISTINCT corporation_id FROM eve_character_profiles ORDER BY corporation_id
`

func (q *Queries) ActivityCorporations(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, activityCorporations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var corporation_id int64
		if err := rows.Scan(&corporation_id); err != nil {
			return nil, err
		}
		items = append(items, corporation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupOnlineSamples = `-- name: CleanupOnlineSamples :exec
DELETE FROM eve_online_samples WHERE (character_id,observed_at) IN (SELECT character_id,observed_at FROM eve_online_samples WHERE observed_at<now()-interval '31 days' ORDER BY observed_at LIMIT 10000)
`

func (q *Queries) CleanupOnlineSamples(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOnlineSamples)
	return err
}

const deleteOnlineHistory = `-- name: DeleteOnlineHistory :exec
DELETE FROM eve_online_samples WHERE character_id=$1
`

func (q *Queries) DeleteOnlineHistory(ctx context.Context, characterID int64) error {
	_, err := q.db.Exec(ctx, deleteOnlineHistory, characterID)
	return err
}

const onlineIntervals = `-- name: OnlineIntervals :many
WITH observations AS (
 SELECT character_id,generation,observed_at,online,corporation_id,
 lag(corporation_id) OVER w AS previous_corporation,
 lag(observed_at) OVER w AS previous_at,lag(online) OVER w AS previous_online,lag(generation) OVER w AS previous_generation
 FROM eve_online_samples WHERE character_id=ANY($1::bigint[]) AND observed_at>=$2::timestamptz-interval '300 seconds' AND observed_at<=$3::timestamptz
 WINDOW w AS (PARTITION BY character_id ORDER BY observed_at)
), intervals AS (
 SELECT character_id,tstzrange(greatest(previous_at,$2::timestamptz),observed_at,'[)') AS span
 FROM observations WHERE online AND previous_online AND generation=previous_generation
 AND ($4::bigint=0 OR (corporation_id=$4 AND previous_corporation=$4))
 AND observed_at>$2::timestamptz AND observed_at-previous_at<=interval '300 seconds'
), merged AS (SELECT character_id,range_agg(span) AS spans FROM intervals GROUP BY character_id)
SELECT character_id,lower(span)::timestamptz AS starts_at,upper(span)::timestamptz AS ends_at FROM merged CROSS JOIN LATERAL unnest(spans) span ORDER BY character_id,starts_at
`

type OnlineIntervalsParams struct {
	Ids           []int64
	Since         pgtype.Timestamptz
	UntilAt       pgtype.Timestamptz
	CorporationID int64
}

type OnlineIntervalsRow struct {
	CharacterID int64
	StartsAt    pgtype.Timestamptz
	EndsAt      pgtype.Timestamptz
}

func (q *Queries) OnlineIntervals(ctx context.Context, arg OnlineIntervalsParams) ([]OnlineIntervalsRow, error) {
	rows, err := q.db.Query(ctx, onlineIntervals,
		arg.Ids,
		arg.Since,
		arg.UntilAt,
		arg.CorporationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnlineIntervalsRow{}
	for rows.Next() {
		var i OnlineIntervalsRow
		if err := rows.Scan(&i.CharacterID, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const onlineLatest = `-- name: OnlineLatest :many
SELECT c.character_id,c.grant_generation,c.state,c.scopes,p.name,p.corporation_id,s.observed_at,s.online,coalesce(s.generation,0)::bigint AS generation,coalesce(s.corporation_id,0)::bigint AS observed_corporation_id
FROM eve_credentials c LEFT JOIN eve_character_profiles p ON p.character_id=c.character_id
LEFT JOIN LATERAL (SELECT character_id, generation, corporation_id, observed_at, online FROM eve_online_samples a WHERE a.character_id=c.character_id ORDER BY observed_at DESC LIMIT 1) s ON true
WHERE c.character_id=ANY($1::bigint[]) ORDER BY c.character_id
`

type OnlineLatestRow struct {
	CharacterID           int64
	GrantGeneration       int64
	State                 string
	Scopes                []string
	Name                  pgtype.Text
	CorporationID         pgtype.Int8
	ObservedAt            pgtype.Timestamptz
	Online                pgtype.Bool
	Generation            int64
	ObservedCorporationID int64
}

func (q *Queries) OnlineLatest(ctx context.Context, ids []int64) ([]OnlineLatestRow, error) {
	rows, err := q.db.Query(ctx, onlineLatest, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnlineLatestRow{}
	for rows.Next() {
		var i OnlineLatestRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.GrantGeneration,
			&i.State,
			&i.Scopes,
			&i.Name,
			&i.CorporationID,
			&i.ObservedAt,
			&i.Online,
			&i.Generation,
			&i.ObservedCorporationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const onlineSampleCounts = `-- name: OnlineSampleCounts :many
SELECT character_id,to_char(observed_at AT TIME ZONE 'Asia/Shanghai','YYYY-MM-DD')::text AS day,count(*)::bigint AS samples
FROM eve_online_samples WHERE character_id=ANY($1::bigint[]) AND observed_at>=$2::timestamptz AND observed_at<=$3::timestamptz AND online IS NOT NULL AND ($4::bigint=0 OR corporation_id=$4)
GROUP BY character_id,day ORDER BY day,character_id
`

type OnlineSampleCountsParams struct {
	Ids           []int64
	Since         pgtype.Timestamptz
	UntilAt       pgtype.Timestamptz
	CorporationID int64
}

type OnlineSampleCountsRow struct {
	CharacterID int64
	Day         string
	Samples     int64
}

func (q *Queries) OnlineSampleCounts(ctx context.Context, arg OnlineSampleCountsParams) ([]OnlineSampleCountsRow, error) {
	rows, err := q.db.Query(ctx, onlineSampleCounts,
		arg.Ids,
		arg.Since,
		arg.UntilAt,
		arg.CorporationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnlineSampleCountsRow{}
	for rows.Next() {
		var i OnlineSampleCountsRow
		if err := rows.Scan(&i.CharacterID, &i.Day, &i.Samples); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOnlineSample = `-- name: SaveOnlineSample :exec
INSERT INTO eve_online_samples(character_id,generation,observed_at,online,corporation_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING
`

type SaveOnlineSampleParams struct {
	CharacterID   int64
	Generation    int64
	ObservedAt    pgtype.Timestamptz
	Online        pgtype.Bool
	CorporationID int64
}

func (q *Queries) SaveOnlineSample(ctx context.Context, arg SaveOnlineSampleParams) error {
	_, err := q.db.Exec(ctx, saveOnlineSample,
		arg.CharacterID,
		arg.Generation,
		arg.ObservedAt,
		arg.Online,
		arg.CorporationID,
	)
	return err
}

const seedOnlineTargets = `-- name: SeedOnlineTargets :exec
INSERT INTO eve_sync_targets(character_id,resource,generation,display_name,state,reason)
SELECT c.character_id,'online',c.grant_generation,coalesce(p.name,''),
 CASE WHEN c.state='reauthorize' OR NOT 'esi-location.read_online.v1'=ANY(c.scopes) THEN 'blocked' ELSE 'idle' END,
 CASE WHEN c.state='reauthorize' THEN 'reauthorize' WHEN NOT 'esi-location.read_online.v1'=ANY(c.scopes) THEN 'missing_scope' ELSE '' END
FROM eve_credentials c LEFT JOIN eve_character_profiles p ON p.character_id=c.character_id
ON CONFLICT(character_id,resource) DO UPDATE SET generation=excluded.generation,state=excluded.state,reason=excluded.reason,
 active_job_id=NULL,lease_until=NULL,fence=eve_sync_targets.fence+1,next_due_at=now(),failures=0
WHERE eve_sync_targets.generation<>excluded.generation OR eve_sync_targets.reason='module_disabled'
`

func (q *Queries) SeedOnlineTargets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedOnlineTargets)
	return err
}
