// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_online.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const publicOnlineLatest = `-- name: PublicOnlineLatest :many
SELECT c.character_id,c.owner_hash,c.grant_generation,c.state,c.scopes,
 s.observed_at,s.online,coalesce(s.generation,0)::bigint AS generation
FROM eve_credentials c
JOIN eve_character_profiles p ON p.character_id=c.character_id AND p.corporation_id=$1 AND p.valid_until>now()
LEFT JOIN LATERAL (SELECT a.character_id, a.generation, a.corporation_id, a.observed_at, a.online FROM eve_online_samples a WHERE a.character_id=c.character_id AND a.corporation_id=$1 ORDER BY a.observed_at DESC LIMIT 1) s ON true
WHERE c.character_id=ANY($2::bigint[])
`

type PublicOnlineLatestParams struct {
	CorporationID int64
	Ids           []int64
}

type PublicOnlineLatestRow struct {
	CharacterID     int64
	OwnerHash       []byte
	GrantGeneration int64
	State           string
	Scopes          []string
	ObservedAt      pgtype.Timestamptz
	Online          pgtype.Bool
	Generation      int64
}

func (q *Queries) PublicOnlineLatest(ctx context.Context, arg PublicOnlineLatestParams) ([]PublicOnlineLatestRow, error) {
	rows, err := q.db.Query(ctx, publicOnlineLatest, arg.CorporationID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicOnlineLatestRow{}
	for rows.Next() {
		var i PublicOnlineLatestRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.OwnerHash,
			&i.GrantGeneration,
			&i.State,
			&i.Scopes,
			&i.ObservedAt,
			&i.Online,
			&i.Generation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
