// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_observation.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupESIBuckets = `-- name: CleanupESIBuckets :exec
DELETE FROM eve_esi_buckets WHERE id IN (SELECT id FROM eve_esi_buckets WHERE updated_at<now()-interval '30 days' ORDER BY updated_at LIMIT 100)
`

func (q *Queries) CleanupESIBuckets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupESIBuckets)
	return err
}

const eSIBucketExists = `-- name: ESIBucketExists :one
SELECT EXISTS(SELECT 1 FROM eve_esi_buckets WHERE id=$1 AND group_name<>'')
`

func (q *Queries) ESIBucketExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, eSIBucketExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listESIBuckets = `-- name: ListESIBuckets :many
SELECT b.id, b.limit_key, b.group_name, b.character_id, b.observed_since, b.updated_at, b.header_at, b.capacity, b.window_seconds, b.remaining, b.retry_at,coalesce((SELECT display_name FROM eve_sync_targets t WHERE t.character_id=b.character_id ORDER BY t.id LIMIT 1),'')::text AS display_name,
 CASE WHEN l.capacity>0 THEN greatest(0,l.capacity-(SELECT coalesce(sum(c.amount),0) FROM eve_esi_charges c WHERE c.limit_key=b.limit_key AND c.expires_at>clock_timestamp())) ELSE -1 END::bigint AS local_remaining,
 l.capacity AS local_capacity,
 (SELECT min(c.expires_at) FROM eve_esi_charges c WHERE c.limit_key=b.limit_key AND c.amount>0 AND c.expires_at>clock_timestamp())::timestamptz AS local_reset_at,l.blocked_until,
 (SELECT blocked_until FROM eve_esi_limits WHERE limit_key='egress')::timestamptz AS egress_blocked_until,
 coalesce((SELECT sum(u.used_tokens) FROM eve_esi_route_usage u WHERE u.bucket_id=b.id),0)::bigint AS used_tokens,
 coalesce((SELECT sum(u.network_requests) FROM eve_esi_route_usage u WHERE u.bucket_id=b.id),0)::bigint AS network_requests,
 coalesce((SELECT sum(u.unmeasured_requests) FROM eve_esi_route_usage u WHERE u.bucket_id=b.id),0)::bigint AS unmeasured_requests
FROM eve_esi_buckets b LEFT JOIN eve_esi_limits l USING(limit_key)
WHERE b.group_name<>'' AND b.id>$1 AND ($2::text='' OR b.group_name ILIKE '%'||$2||'%' OR b.character_id::text=$2
 OR EXISTS(SELECT 1 FROM eve_sync_targets t WHERE t.character_id=b.character_id AND t.display_name ILIKE '%'||$2||'%'))
ORDER BY b.id LIMIT 31
`

type ListESIBucketsParams struct {
	AfterID int64
	Search  string
}

type ListESIBucketsRow struct {
	ID                 int64
	LimitKey           string
	GroupName          string
	CharacterID        int64
	ObservedSince      pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	HeaderAt           pgtype.Timestamptz
	Capacity           pgtype.Int8
	WindowSeconds      pgtype.Int8
	Remaining          pgtype.Int8
	RetryAt            pgtype.Timestamptz
	DisplayName        string
	LocalRemaining     int64
	LocalCapacity      pgtype.Int8
	LocalResetAt       pgtype.Timestamptz
	BlockedUntil       pgtype.Timestamptz
	EgressBlockedUntil pgtype.Timestamptz
	UsedTokens         int64
	NetworkRequests    int64
	UnmeasuredRequests int64
}

func (q *Queries) ListESIBuckets(ctx context.Context, arg ListESIBucketsParams) ([]ListESIBucketsRow, error) {
	rows, err := q.db.Query(ctx, listESIBuckets, arg.AfterID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListESIBucketsRow{}
	for rows.Next() {
		var i ListESIBucketsRow
		if err := rows.Scan(
			&i.ID,
			&i.LimitKey,
			&i.GroupName,
			&i.CharacterID,
			&i.ObservedSince,
			&i.UpdatedAt,
			&i.HeaderAt,
			&i.Capacity,
			&i.WindowSeconds,
			&i.Remaining,
			&i.RetryAt,
			&i.DisplayName,
			&i.LocalRemaining,
			&i.LocalCapacity,
			&i.LocalResetAt,
			&i.BlockedUntil,
			&i.EgressBlockedUntil,
			&i.UsedTokens,
			&i.NetworkRequests,
			&i.UnmeasuredRequests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listESIRouteUsage = `-- name: ListESIRouteUsage :many
SELECT bucket_id, route, network_requests, cache_hits, local_waits, upstream_limits, used_tokens, measured_responses, unmeasured_requests, last_status, last_used, last_response_at, updated_at FROM eve_esi_route_usage WHERE bucket_id=$1 AND route>$2::text ORDER BY route LIMIT 31
`

type ListESIRouteUsageParams struct {
	BucketID   int64
	AfterRoute string
}

func (q *Queries) ListESIRouteUsage(ctx context.Context, arg ListESIRouteUsageParams) ([]EveEsiRouteUsage, error) {
	rows, err := q.db.Query(ctx, listESIRouteUsage, arg.BucketID, arg.AfterRoute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EveEsiRouteUsage{}
	for rows.Next() {
		var i EveEsiRouteUsage
		if err := rows.Scan(
			&i.BucketID,
			&i.Route,
			&i.NetworkRequests,
			&i.CacheHits,
			&i.LocalWaits,
			&i.UpstreamLimits,
			&i.UsedTokens,
			&i.MeasuredResponses,
			&i.UnmeasuredRequests,
			&i.LastStatus,
			&i.LastUsed,
			&i.LastResponseAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observeESIBucket = `-- name: ObserveESIBucket :one
INSERT INTO eve_esi_buckets(limit_key,group_name,character_id,header_at,capacity,window_seconds,remaining,retry_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT(limit_key) DO UPDATE SET updated_at=clock_timestamp(),
 header_at=CASE WHEN excluded.header_at>=eve_esi_buckets.header_at OR eve_esi_buckets.header_at IS NULL THEN coalesce(excluded.header_at,eve_esi_buckets.header_at) ELSE eve_esi_buckets.header_at END,
 capacity=CASE WHEN excluded.header_at>=eve_esi_buckets.header_at OR eve_esi_buckets.header_at IS NULL THEN coalesce(excluded.capacity,eve_esi_buckets.capacity) ELSE eve_esi_buckets.capacity END,
 window_seconds=CASE WHEN excluded.header_at>=eve_esi_buckets.header_at OR eve_esi_buckets.header_at IS NULL THEN coalesce(excluded.window_seconds,eve_esi_buckets.window_seconds) ELSE eve_esi_buckets.window_seconds END,
 remaining=CASE WHEN excluded.header_at>=eve_esi_buckets.header_at OR eve_esi_buckets.header_at IS NULL THEN excluded.remaining ELSE eve_esi_buckets.remaining END,
 retry_at=greatest(eve_esi_buckets.retry_at,excluded.retry_at)
RETURNING id
`

type ObserveESIBucketParams struct {
	LimitKey      string
	GroupName     string
	CharacterID   int64
	HeaderAt      pgtype.Timestamptz
	Capacity      pgtype.Int8
	WindowSeconds pgtype.Int8
	Remaining     pgtype.Int8
	RetryAt       pgtype.Timestamptz
}

func (q *Queries) ObserveESIBucket(ctx context.Context, arg ObserveESIBucketParams) (int64, error) {
	row := q.db.QueryRow(ctx, observeESIBucket,
		arg.LimitKey,
		arg.GroupName,
		arg.CharacterID,
		arg.HeaderAt,
		arg.Capacity,
		arg.WindowSeconds,
		arg.Remaining,
		arg.RetryAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const observeESIRouteUsage = `-- name: ObserveESIRouteUsage :exec
INSERT INTO eve_esi_route_usage(bucket_id,route,network_requests,cache_hits,local_waits,upstream_limits,used_tokens,measured_responses,unmeasured_requests,last_status,last_used,last_response_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
ON CONFLICT(bucket_id,route) DO UPDATE SET
 network_requests=eve_esi_route_usage.network_requests+excluded.network_requests,
 cache_hits=eve_esi_route_usage.cache_hits+excluded.cache_hits,
 local_waits=eve_esi_route_usage.local_waits+excluded.local_waits,
 upstream_limits=eve_esi_route_usage.upstream_limits+excluded.upstream_limits,
 used_tokens=eve_esi_route_usage.used_tokens+excluded.used_tokens,
 measured_responses=eve_esi_route_usage.measured_responses+excluded.measured_responses,
 unmeasured_requests=eve_esi_route_usage.unmeasured_requests+excluded.unmeasured_requests,
 last_status=CASE WHEN excluded.last_response_at>=eve_esi_route_usage.last_response_at OR eve_esi_route_usage.last_response_at IS NULL THEN excluded.last_status ELSE eve_esi_route_usage.last_status END,
 last_used=CASE WHEN excluded.last_response_at>=eve_esi_route_usage.last_response_at OR eve_esi_route_usage.last_response_at IS NULL THEN excluded.last_used ELSE eve_esi_route_usage.last_used END,
 last_response_at=greatest(eve_esi_route_usage.last_response_at,excluded.last_response_at),updated_at=clock_timestamp()
`

type ObserveESIRouteUsageParams struct {
	BucketID           int64
	Route              string
	NetworkRequests    int64
	CacheHits          int64
	LocalWaits         int64
	UpstreamLimits     int64
	UsedTokens         int64
	MeasuredResponses  int64
	UnmeasuredRequests int64
	LastStatus         int32
	LastUsed           pgtype.Int8
	LastResponseAt     pgtype.Timestamptz
}

func (q *Queries) ObserveESIRouteUsage(ctx context.Context, arg ObserveESIRouteUsageParams) error {
	_, err := q.db.Exec(ctx, observeESIRouteUsage,
		arg.BucketID,
		arg.Route,
		arg.NetworkRequests,
		arg.CacheHits,
		arg.LocalWaits,
		arg.UpstreamLimits,
		arg.UsedTokens,
		arg.MeasuredResponses,
		arg.UnmeasuredRequests,
		arg.LastStatus,
		arg.LastUsed,
		arg.LastResponseAt,
	)
	return err
}
