// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sliding_budget.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupESICharges = `-- name: CleanupESICharges :exec
DELETE FROM eve_esi_charges WHERE id IN (SELECT id FROM eve_esi_charges WHERE expires_at<clock_timestamp() ORDER BY expires_at LIMIT 10000)
`

func (q *Queries) CleanupESICharges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupESICharges)
	return err
}

const configureESIBudget = `-- name: ConfigureESIBudget :exec
UPDATE eve_esi_limits SET capacity=$2,window_seconds=$3,updated_at=clock_timestamp() WHERE limit_key=$1
`

type ConfigureESIBudgetParams struct {
	LimitKey      string
	Capacity      int64
	WindowSeconds int64
}

func (q *Queries) ConfigureESIBudget(ctx context.Context, arg ConfigureESIBudgetParams) error {
	_, err := q.db.Exec(ctx, configureESIBudget, arg.LimitKey, arg.Capacity, arg.WindowSeconds)
	return err
}

const eSIBudgetUsage = `-- name: ESIBudgetUsage :one
SELECT coalesce(sum(amount),0)::bigint AS used,
 min(expires_at)::timestamptz AS next_expiry,
 max(expires_at)::timestamptz AS full_expiry
FROM eve_esi_charges WHERE limit_key=$1 AND expires_at>clock_timestamp() AND amount>0
`

type ESIBudgetUsageRow struct {
	Used       int64
	NextExpiry pgtype.Timestamptz
	FullExpiry pgtype.Timestamptz
}

func (q *Queries) ESIBudgetUsage(ctx context.Context, limitKey string) (ESIBudgetUsageRow, error) {
	row := q.db.QueryRow(ctx, eSIBudgetUsage, limitKey)
	var i ESIBudgetUsageRow
	err := row.Scan(&i.Used, &i.NextExpiry, &i.FullExpiry)
	return i, err
}

const insertESICharge = `-- name: InsertESICharge :one
INSERT INTO eve_esi_charges(limit_key,amount,expires_at,settled) VALUES($1,$2,$3,$4) RETURNING id
`

type InsertESIChargeParams struct {
	LimitKey  string
	Amount    int64
	ExpiresAt pgtype.Timestamptz
	Settled   bool
}

func (q *Queries) InsertESICharge(ctx context.Context, arg InsertESIChargeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertESICharge,
		arg.LimitKey,
		arg.Amount,
		arg.ExpiresAt,
		arg.Settled,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const settleESICharge = `-- name: SettleESICharge :execrows
UPDATE eve_esi_charges SET limit_key=$2,amount=$3,expires_at=$4,settled=true WHERE id=$1 AND NOT settled
`

type SettleESIChargeParams struct {
	ID        int64
	LimitKey  string
	Amount    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) SettleESICharge(ctx context.Context, arg SettleESIChargeParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleESICharge,
		arg.ID,
		arg.LimitKey,
		arg.Amount,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const snapshotESIBudget = `-- name: SnapshotESIBudget :exec
UPDATE eve_esi_limits l SET
 remaining=greatest(0,l.capacity-(SELECT coalesce(sum(c.amount),0) FROM eve_esi_charges c WHERE c.limit_key=l.limit_key AND c.expires_at>clock_timestamp())),
 reset_at=coalesce((SELECT max(c.expires_at) FROM eve_esi_charges c WHERE c.limit_key=l.limit_key AND c.amount>0 AND c.expires_at>clock_timestamp()),clock_timestamp()),
 updated_at=clock_timestamp() WHERE l.limit_key=$1
`

func (q *Queries) SnapshotESIBudget(ctx context.Context, limitKey string) error {
	_, err := q.db.Exec(ctx, snapshotESIBudget, limitKey)
	return err
}
