// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: static_search.sql

package store

import (
	"context"
)

const searchStaticTypes = `-- name: SearchStaticTypes :many
SELECT n.type_id,n.name_zh,n.name_en FROM eve_sde_type_names n JOIN eve_sde_active_names a ON a.release_id=n.release_id
WHERE n.type_id>0 AND (n.type_id::text=$1::text OR strpos(lower(n.name_zh),lower($1))>0 OR strpos(lower(n.name_en),lower($1))>0)
ORDER BY CASE WHEN n.type_id::text=$1 THEN 0 ELSE 1 END,n.type_id LIMIT 30
`

type SearchStaticTypesRow struct {
	TypeID int64
	NameZh string
	NameEn string
}

func (q *Queries) SearchStaticTypes(ctx context.Context, term string) ([]SearchStaticTypesRow, error) {
	rows, err := q.db.Query(ctx, searchStaticTypes, term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchStaticTypesRow{}
	for rows.Next() {
		var i SearchStaticTypesRow
		if err := rows.Scan(&i.TypeID, &i.NameZh, &i.NameEn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
