// Code generated by sqlc. DO NOT EDIT.
package store

import "context"

const structureSources = `-- name: StructureSources :many
SELECT c.character_id,c.grant_generation,c.owner_hash,s.corporation_id,s.corporation_name,s.alliance_id,s.ceo_id
FROM eve_credentials c JOIN eve_role_snapshots s USING(character_id)
WHERE c.state IN ('ready','retry') AND s.valid_until>now() AND s.owner_hash=c.owner_hash
AND (c.roles_not_before IS NULL OR c.roles_not_before<=now())
AND (c.character_id=s.ceo_id OR 'Director'=ANY(s.roles))
AND ('esi-corporations.read_structures.v1'=ANY(c.scopes) OR 'esi-corporations.read_starbases.v1'=ANY(c.scopes))
ORDER BY s.corporation_id,(c.character_id=s.ceo_id) DESC,c.character_id
`

type StructureSourcesRow struct {
	CharacterID     int64
	GrantGeneration int64
	OwnerHash       []byte
	CorporationID   int64
	CorporationName string
	AllianceID      int64
	CeoID           int64
}

func (q *Queries) StructureSources(ctx context.Context) ([]StructureSourcesRow, error) {
	rows, err := q.db.Query(ctx, structureSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	result := []StructureSourcesRow{}
	for rows.Next() {
		var row StructureSourcesRow
		if err := rows.Scan(&row.CharacterID, &row.GrantGeneration, &row.OwnerHash, &row.CorporationID, &row.CorporationName, &row.AllianceID, &row.CeoID); err != nil {
			return nil, err
		}
		result = append(result, row)
	}
	return result, rows.Err()
}
