// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonSyncRuns = `-- name: AbandonSyncRuns :exec
UPDATE eve_sync_runs SET outcome='interrupted',reason='worker_interrupted',finished_at=now() WHERE target_id=$1 AND finished_at IS NULL
`

func (q *Queries) AbandonSyncRuns(ctx context.Context, targetID int64) error {
	_, err := q.db.Exec(ctx, abandonSyncRuns, targetID)
	return err
}

const advanceGeneration = `-- name: AdvanceGeneration :one
UPDATE eve_credentials SET grant_generation=grant_generation+1 WHERE character_id=$1 RETURNING grant_generation
`

func (q *Queries) AdvanceGeneration(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRow(ctx, advanceGeneration, characterID)
	var grant_generation int64
	err := row.Scan(&grant_generation)
	return grant_generation, err
}

const beginSyncRun = `-- name: BeginSyncRun :exec
INSERT INTO eve_sync_runs(target_id,job_id,fence) VALUES($1,$2,$3)
`

type BeginSyncRunParams struct {
	TargetID int64
	JobID    int64
	Fence    int64
}

func (q *Queries) BeginSyncRun(ctx context.Context, arg BeginSyncRunParams) error {
	_, err := q.db.Exec(ctx, beginSyncRun, arg.TargetID, arg.JobID, arg.Fence)
	return err
}

const blockCharacterSync = `-- name: BlockCharacterSync :exec
UPDATE eve_sync_targets SET state='blocked',reason=$2,active_job_id=NULL,lease_until=NULL,fence=fence+1,updated_at=now() WHERE character_id=$1 AND resource<>'profile'
`

type BlockCharacterSyncParams struct {
	CharacterID int64
	Reason      string
}

func (q *Queries) BlockCharacterSync(ctx context.Context, arg BlockCharacterSyncParams) error {
	_, err := q.db.Exec(ctx, blockCharacterSync, arg.CharacterID, arg.Reason)
	return err
}

const blockESILimit = `-- name: BlockESILimit :exec
INSERT INTO eve_esi_limits(limit_key,blocked_until) VALUES($1,$2)
ON CONFLICT(limit_key) DO UPDATE SET blocked_until=greatest(eve_esi_limits.blocked_until,excluded.blocked_until),updated_at=now()
`

type BlockESILimitParams struct {
	LimitKey     string
	BlockedUntil pgtype.Timestamptz
}

func (q *Queries) BlockESILimit(ctx context.Context, arg BlockESILimitParams) error {
	_, err := q.db.Exec(ctx, blockESILimit, arg.LimitKey, arg.BlockedUntil)
	return err
}

const cacheUsage = `-- name: CacheUsage :one
SELECT count(*)::bigint AS entries,coalesce(sum(octet_length(body)),0)::bigint AS bytes FROM eve_esi_cache
`

type CacheUsageRow struct {
	Entries int64
	Bytes   int64
}

func (q *Queries) CacheUsage(ctx context.Context) (CacheUsageRow, error) {
	row := q.db.QueryRow(ctx, cacheUsage)
	var i CacheUsageRow
	err := row.Scan(&i.Entries, &i.Bytes)
	return i, err
}

const claimSync = `-- name: ClaimSync :one
UPDATE eve_sync_targets SET state='running',fence=fence+1,last_attempt_at=now(),lease_until=now()+interval '90 seconds',updated_at=now()
WHERE id=$1 AND generation=$2 AND active_job_id=$3 AND (lease_until IS NULL OR lease_until<now()) RETURNING id, character_id, resource, generation, display_name, state, reason, next_due_at, last_attempt_at, last_success_at, valid_until, content_updated_at, active_job_id, completed_job_id, fence, lease_until, failures, updated_at
`

type ClaimSyncParams struct {
	ID          int64
	Generation  int64
	ActiveJobID pgtype.Int8
}

func (q *Queries) ClaimSync(ctx context.Context, arg ClaimSyncParams) (EveSyncTarget, error) {
	row := q.db.QueryRow(ctx, claimSync, arg.ID, arg.Generation, arg.ActiveJobID)
	var i EveSyncTarget
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Resource,
		&i.Generation,
		&i.DisplayName,
		&i.State,
		&i.Reason,
		&i.NextDueAt,
		&i.LastAttemptAt,
		&i.LastSuccessAt,
		&i.ValidUntil,
		&i.ContentUpdatedAt,
		&i.ActiveJobID,
		&i.CompletedJobID,
		&i.Fence,
		&i.LeaseUntil,
		&i.Failures,
		&i.UpdatedAt,
	)
	return i, err
}

const cleanupSyncCache = `-- name: CleanupSyncCache :exec
DELETE FROM eve_esi_cache WHERE cache_key IN (SELECT cache_key FROM eve_esi_cache WHERE expires_at<now()-interval '1 day' ORDER BY expires_at LIMIT 500)
`

func (q *Queries) CleanupSyncCache(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupSyncCache)
	return err
}

const cleanupSyncRuns = `-- name: CleanupSyncRuns :exec
WITH expired AS (
 (SELECT id,finished_at FROM eve_sync_runs
  WHERE outcome='success' AND finished_at<now()-interval '14 days'
  ORDER BY finished_at,id LIMIT 500)
 UNION ALL
 (SELECT id,finished_at FROM eve_sync_runs
  WHERE outcome<>'success' AND finished_at<now()-interval '30 days'
  ORDER BY finished_at,id LIMIT 500)
), batch AS (
 SELECT id FROM expired ORDER BY finished_at,id LIMIT 500
)
DELETE FROM eve_sync_runs WHERE id IN (SELECT id FROM batch)
 AND ((outcome='success' AND finished_at<now()-interval '14 days')
   OR (outcome<>'success' AND finished_at<now()-interval '30 days'))
`

func (q *Queries) CleanupSyncRuns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupSyncRuns)
	return err
}

const deferSyncTarget = `-- name: DeferSyncTarget :execrows
UPDATE eve_sync_targets SET state='deferred',reason=$3,next_due_at=$4,lease_until=NULL,failures=$5,updated_at=now()
WHERE id=$1 AND fence=$2
`

type DeferSyncTargetParams struct {
	ID        int64
	Fence     int64
	Reason    string
	NextDueAt pgtype.Timestamptz
	Failures  int32
}

func (q *Queries) DeferSyncTarget(ctx context.Context, arg DeferSyncTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deferSyncTarget,
		arg.ID,
		arg.Fence,
		arg.Reason,
		arg.NextDueAt,
		arg.Failures,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteESICache = `-- name: DeleteESICache :exec
DELETE FROM eve_esi_cache WHERE cache_key=$1
`

func (q *Queries) DeleteESICache(ctx context.Context, cacheKey string) error {
	_, err := q.db.Exec(ctx, deleteESICache, cacheKey)
	return err
}

const deletePrivateCache = `-- name: DeletePrivateCache :exec
DELETE FROM eve_esi_cache WHERE character_id=$1::bigint
`

func (q *Queries) DeletePrivateCache(ctx context.Context, characterID int64) error {
	_, err := q.db.Exec(ctx, deletePrivateCache, characterID)
	return err
}

const ensureESILimit = `-- name: EnsureESILimit :exec
INSERT INTO eve_esi_limits(limit_key) VALUES($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureESILimit(ctx context.Context, limitKey string) error {
	_, err := q.db.Exec(ctx, ensureESILimit, limitKey)
	return err
}

const finishSyncRun = `-- name: FinishSyncRun :exec
UPDATE eve_sync_runs SET finished_at=now(),outcome=$3,reason=$4,http_status=$5 WHERE target_id=$1 AND fence=$2
`

type FinishSyncRunParams struct {
	TargetID   int64
	Fence      int64
	Outcome    string
	Reason     string
	HttpStatus int32
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error {
	_, err := q.db.Exec(ctx, finishSyncRun,
		arg.TargetID,
		arg.Fence,
		arg.Outcome,
		arg.Reason,
		arg.HttpStatus,
	)
	return err
}

const finishSyncTarget = `-- name: FinishSyncTarget :execrows
UPDATE eve_sync_targets SET state=$1,reason=$2,next_due_at=$3,
 active_job_id=NULL,completed_job_id=$4,lease_until=NULL,failures=$5,updated_at=now(),
 last_success_at=CASE WHEN $6::boolean THEN now() ELSE last_success_at END,
 valid_until=CASE WHEN $6::boolean THEN $7::timestamptz ELSE valid_until END,
 content_updated_at=CASE WHEN $6::boolean THEN coalesce($8::timestamptz,content_updated_at,now()) ELSE content_updated_at END
WHERE id=$9 AND fence=$10 AND generation=$11 AND lease_until>now()
`

type FinishSyncTargetParams struct {
	State            string
	Reason           string
	NextDueAt        pgtype.Timestamptz
	JobID            pgtype.Int8
	Failures         int32
	Success          bool
	ValidUntil       pgtype.Timestamptz
	ContentUpdatedAt pgtype.Timestamptz
	ID               int64
	Fence            int64
	Generation       int64
}

func (q *Queries) FinishSyncTarget(ctx context.Context, arg FinishSyncTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishSyncTarget,
		arg.State,
		arg.Reason,
		arg.NextDueAt,
		arg.JobID,
		arg.Failures,
		arg.Success,
		arg.ValidUntil,
		arg.ContentUpdatedAt,
		arg.ID,
		arg.Fence,
		arg.Generation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCredential = `-- name: GetCredential :one
SELECT character_id, owner_hash, sealed, state, next_sync_at, updated_at, scopes, grant_generation, refresh_revision, roles_not_before FROM eve_credentials WHERE character_id=$1
`

func (q *Queries) GetCredential(ctx context.Context, characterID int64) (EveCredential, error) {
	row := q.db.QueryRow(ctx, getCredential, characterID)
	var i EveCredential
	err := row.Scan(
		&i.CharacterID,
		&i.OwnerHash,
		&i.Sealed,
		&i.State,
		&i.NextSyncAt,
		&i.UpdatedAt,
		&i.Scopes,
		&i.GrantGeneration,
		&i.RefreshRevision,
		&i.RolesNotBefore,
	)
	return i, err
}

const getCredentialForUpdate = `-- name: GetCredentialForUpdate :one
SELECT character_id, owner_hash, sealed, state, next_sync_at, updated_at, scopes, grant_generation, refresh_revision, roles_not_before FROM eve_credentials WHERE character_id=$1 FOR UPDATE
`

func (q *Queries) GetCredentialForUpdate(ctx context.Context, characterID int64) (EveCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialForUpdate, characterID)
	var i EveCredential
	err := row.Scan(
		&i.CharacterID,
		&i.OwnerHash,
		&i.Sealed,
		&i.State,
		&i.NextSyncAt,
		&i.UpdatedAt,
		&i.Scopes,
		&i.GrantGeneration,
		&i.RefreshRevision,
		&i.RolesNotBefore,
	)
	return i, err
}

const getESIRoute = `-- name: GetESIRoute :one
SELECT group_name FROM eve_esi_routes WHERE route_key=$1
`

func (q *Queries) GetESIRoute(ctx context.Context, routeKey string) (string, error) {
	row := q.db.QueryRow(ctx, getESIRoute, routeKey)
	var group_name string
	err := row.Scan(&group_name)
	return group_name, err
}

const getSyncTarget = `-- name: GetSyncTarget :one
SELECT id, character_id, resource, generation, display_name, state, reason, next_due_at, last_attempt_at, last_success_at, valid_until, content_updated_at, active_job_id, completed_job_id, fence, lease_until, failures, updated_at FROM eve_sync_targets WHERE id=$1
`

func (q *Queries) GetSyncTarget(ctx context.Context, id int64) (EveSyncTarget, error) {
	row := q.db.QueryRow(ctx, getSyncTarget, id)
	var i EveSyncTarget
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Resource,
		&i.Generation,
		&i.DisplayName,
		&i.State,
		&i.Reason,
		&i.NextDueAt,
		&i.LastAttemptAt,
		&i.LastSuccessAt,
		&i.ValidUntil,
		&i.ContentUpdatedAt,
		&i.ActiveJobID,
		&i.CompletedJobID,
		&i.Fence,
		&i.LeaseUntil,
		&i.Failures,
		&i.UpdatedAt,
	)
	return i, err
}

const listCharacterSync = `-- name: ListCharacterSync :many
SELECT id, character_id, resource, generation, display_name, state, reason, next_due_at, last_attempt_at, last_success_at, valid_until, content_updated_at, active_job_id, completed_job_id, fence, lease_until, failures, updated_at FROM eve_sync_targets WHERE character_id=$1 ORDER BY resource
`

func (q *Queries) ListCharacterSync(ctx context.Context, characterID int64) ([]EveSyncTarget, error) {
	rows, err := q.db.Query(ctx, listCharacterSync, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EveSyncTarget{}
	for rows.Next() {
		var i EveSyncTarget
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Resource,
			&i.Generation,
			&i.DisplayName,
			&i.State,
			&i.Reason,
			&i.NextDueAt,
			&i.LastAttemptAt,
			&i.LastSuccessAt,
			&i.ValidUntil,
			&i.ContentUpdatedAt,
			&i.ActiveJobID,
			&i.CompletedJobID,
			&i.Fence,
			&i.LeaseUntil,
			&i.Failures,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncRuns = `-- name: ListSyncRuns :many
SELECT id, target_id, job_id, fence, started_at, finished_at, outcome, reason, http_status FROM eve_sync_runs WHERE target_id=$1 ORDER BY id DESC LIMIT 20
`

func (q *Queries) ListSyncRuns(ctx context.Context, targetID int64) ([]EveSyncRun, error) {
	rows, err := q.db.Query(ctx, listSyncRuns, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EveSyncRun{}
	for rows.Next() {
		var i EveSyncRun
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.JobID,
			&i.Fence,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Outcome,
			&i.Reason,
			&i.HttpStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncTargets = `-- name: ListSyncTargets :many
SELECT id, character_id, resource, generation, display_name, state, reason, next_due_at, last_attempt_at, last_success_at, valid_until, content_updated_at, active_job_id, completed_job_id, fence, lease_until, failures, updated_at FROM eve_sync_targets WHERE id>$1 AND ($2::text='' OR state=$2)
AND ($3::text='' OR display_name ILIKE '%'||$3||'%' OR character_id::text=$3) ORDER BY id LIMIT 31
`

type ListSyncTargetsParams struct {
	AfterID     int64
	StateFilter string
	Search      string
}

func (q *Queries) ListSyncTargets(ctx context.Context, arg ListSyncTargetsParams) ([]EveSyncTarget, error) {
	rows, err := q.db.Query(ctx, listSyncTargets, arg.AfterID, arg.StateFilter, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EveSyncTarget{}
	for rows.Next() {
		var i EveSyncTarget
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Resource,
			&i.Generation,
			&i.DisplayName,
			&i.State,
			&i.Reason,
			&i.NextDueAt,
			&i.LastAttemptAt,
			&i.LastSuccessAt,
			&i.ValidUntil,
			&i.ContentUpdatedAt,
			&i.ActiveJobID,
			&i.CompletedJobID,
			&i.Fence,
			&i.LeaseUntil,
			&i.Failures,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCacheCredential = `-- name: LockCacheCredential :one
SELECT grant_generation,state FROM eve_credentials WHERE character_id=$1 FOR SHARE
`

type LockCacheCredentialRow struct {
	GrantGeneration int64
	State           string
}

func (q *Queries) LockCacheCredential(ctx context.Context, characterID int64) (LockCacheCredentialRow, error) {
	row := q.db.QueryRow(ctx, lockCacheCredential, characterID)
	var i LockCacheCredentialRow
	err := row.Scan(&i.GrantGeneration, &i.State)
	return i, err
}

const lockCacheQuota = `-- name: LockCacheQuota :exec
SELECT pg_advisory_xact_lock(743285110)
`

func (q *Queries) LockCacheQuota(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockCacheQuota)
	return err
}

const lockDueTargets = `-- name: LockDueTargets :many
SELECT id, character_id, resource, generation, display_name, state, reason, next_due_at, last_attempt_at, last_success_at, valid_until, content_updated_at, active_job_id, completed_job_id, fence, lease_until, failures, updated_at FROM eve_sync_targets WHERE state<>'blocked' AND ((resource NOT LIKE 'wallet_%' AND resource NOT LIKE 'corporation_wallet_%') OR $1::boolean) AND (resource<>'killmails' OR $2::boolean) AND (resource<>'online' OR $3::boolean) AND (resource<>'fittings' OR $4::boolean) AND (resource<>'skills' OR $4::boolean OR $5::boolean) AND (resource<>'skillqueue' OR $5::boolean) AND next_due_at<=now() ORDER BY CASE WHEN resource='online' THEN 0 ELSE 1 END,next_due_at,id LIMIT 100 FOR UPDATE SKIP LOCKED
`

type LockDueTargetsParams struct {
	WalletEnabled   bool
	LossesEnabled   bool
	OnlineEnabled   bool
	FittingsEnabled bool
	SkillsEnabled   bool
}

// Give time-sensitive online observations the first slots in each bounded scan; the larger batch still leaves capacity for other resources.
func (q *Queries) LockDueTargets(ctx context.Context, arg LockDueTargetsParams) ([]EveSyncTarget, error) {
	rows, err := q.db.Query(ctx, lockDueTargets,
		arg.WalletEnabled,
		arg.LossesEnabled,
		arg.OnlineEnabled,
		arg.FittingsEnabled,
		arg.SkillsEnabled,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EveSyncTarget{}
	for rows.Next() {
		var i EveSyncTarget
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Resource,
			&i.Generation,
			&i.DisplayName,
			&i.State,
			&i.Reason,
			&i.NextDueAt,
			&i.LastAttemptAt,
			&i.LastSuccessAt,
			&i.ValidUntil,
			&i.ContentUpdatedAt,
			&i.ActiveJobID,
			&i.CompletedJobID,
			&i.Fence,
			&i.LeaseUntil,
			&i.Failures,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockESILimit = `-- name: LockESILimit :one
SELECT limit_key, blocked_until, next_request_at, remaining, capacity, window_seconds, reset_at, updated_at FROM eve_esi_limits WHERE limit_key=$1 FOR UPDATE
`

func (q *Queries) LockESILimit(ctx context.Context, limitKey string) (EveEsiLimit, error) {
	row := q.db.QueryRow(ctx, lockESILimit, limitKey)
	var i EveEsiLimit
	err := row.Scan(
		&i.LimitKey,
		&i.BlockedUntil,
		&i.NextRequestAt,
		&i.Remaining,
		&i.Capacity,
		&i.WindowSeconds,
		&i.ResetAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSyncTarget = `-- name: LockSyncTarget :one
SELECT id, character_id, resource, generation, display_name, state, reason, next_due_at, last_attempt_at, last_success_at, valid_until, content_updated_at, active_job_id, completed_job_id, fence, lease_until, failures, updated_at FROM eve_sync_targets WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockSyncTarget(ctx context.Context, id int64) (EveSyncTarget, error) {
	row := q.db.QueryRow(ctx, lockSyncTarget, id)
	var i EveSyncTarget
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Resource,
		&i.Generation,
		&i.DisplayName,
		&i.State,
		&i.Reason,
		&i.NextDueAt,
		&i.LastAttemptAt,
		&i.LastSuccessAt,
		&i.ValidUntil,
		&i.ContentUpdatedAt,
		&i.ActiveJobID,
		&i.CompletedJobID,
		&i.Fence,
		&i.LeaseUntil,
		&i.Failures,
		&i.UpdatedAt,
	)
	return i, err
}

const persistRotation = `-- name: PersistRotation :exec
UPDATE eve_credentials SET sealed=$2,refresh_revision=refresh_revision+1,updated_at=now() WHERE character_id=$1
`

type PersistRotationParams struct {
	CharacterID int64
	Sealed      []byte
}

func (q *Queries) PersistRotation(ctx context.Context, arg PersistRotationParams) error {
	_, err := q.db.Exec(ctx, persistRotation, arg.CharacterID, arg.Sealed)
	return err
}

const readESICache = `-- name: ReadESICache :one
SELECT cache_key, character_id, generation, body, etag, last_modified, content_updated_at, expires_at, updated_at, page_count FROM eve_esi_cache WHERE cache_key=$1
`

func (q *Queries) ReadESICache(ctx context.Context, cacheKey string) (EveEsiCache, error) {
	row := q.db.QueryRow(ctx, readESICache, cacheKey)
	var i EveEsiCache
	err := row.Scan(
		&i.CacheKey,
		&i.CharacterID,
		&i.Generation,
		&i.Body,
		&i.Etag,
		&i.LastModified,
		&i.ContentUpdatedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
		&i.PageCount,
	)
	return i, err
}

const reserveESILimit = `-- name: ReserveESILimit :exec
UPDATE eve_esi_limits SET next_request_at=$2,updated_at=now() WHERE limit_key=$1
`

type ReserveESILimitParams struct {
	LimitKey      string
	NextRequestAt pgtype.Timestamptz
}

func (q *Queries) ReserveESILimit(ctx context.Context, arg ReserveESILimitParams) error {
	_, err := q.db.Exec(ctx, reserveESILimit, arg.LimitKey, arg.NextRequestAt)
	return err
}

const resetSyncTarget = `-- name: ResetSyncTarget :exec
UPDATE eve_sync_targets SET state='idle',reason='',active_job_id=NULL,lease_until=NULL,updated_at=now() WHERE id=$1
`

func (q *Queries) ResetSyncTarget(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetSyncTarget, id)
	return err
}

const saveCharacterProfile = `-- name: SaveCharacterProfile :exec
INSERT INTO eve_character_profiles(character_id,name,corporation_id,alliance_id,checked_at,valid_until) VALUES($1,$2,$3,$4,now(),$5)
ON CONFLICT(character_id) DO UPDATE SET name=excluded.name,corporation_id=excluded.corporation_id,alliance_id=excluded.alliance_id,checked_at=excluded.checked_at,valid_until=excluded.valid_until
`

type SaveCharacterProfileParams struct {
	CharacterID   int64
	Name          string
	CorporationID int64
	AllianceID    int64
	ValidUntil    pgtype.Timestamptz
}

func (q *Queries) SaveCharacterProfile(ctx context.Context, arg SaveCharacterProfileParams) error {
	_, err := q.db.Exec(ctx, saveCharacterProfile,
		arg.CharacterID,
		arg.Name,
		arg.CorporationID,
		arg.AllianceID,
		arg.ValidUntil,
	)
	return err
}

const saveESIBudget = `-- name: SaveESIBudget :exec
UPDATE eve_esi_limits SET remaining=$2,capacity=$3,window_seconds=$4,reset_at=$5,updated_at=now() WHERE limit_key=$1
`

type SaveESIBudgetParams struct {
	LimitKey      string
	Remaining     int64
	Capacity      int64
	WindowSeconds int64
	ResetAt       pgtype.Timestamptz
}

func (q *Queries) SaveESIBudget(ctx context.Context, arg SaveESIBudgetParams) error {
	_, err := q.db.Exec(ctx, saveESIBudget,
		arg.LimitKey,
		arg.Remaining,
		arg.Capacity,
		arg.WindowSeconds,
		arg.ResetAt,
	)
	return err
}

const seedSyncTargets = `-- name: SeedSyncTargets :exec
INSERT INTO eve_sync_targets(character_id,resource,generation,display_name,next_due_at,state,reason)
SELECT c.character_id,resource,c.grant_generation,$1::text,
 CASE WHEN resource IN ('profile','authorization') THEN c.next_sync_at ELSE now() END,
 CASE WHEN scope<>'' AND NOT scope=ANY(c.scopes) THEN 'blocked' ELSE 'idle' END,
 CASE WHEN scope<>'' AND NOT scope=ANY(c.scopes) THEN 'missing_scope' ELSE '' END
FROM eve_credentials c CROSS JOIN (VALUES ('profile',''),('authorization',''),('character_contracts','esi-contracts.read_character_contracts.v1'),('corporation_contracts','esi-contracts.read_corporation_contracts.v1'),('corporation_structures','')) r(resource,scope) WHERE c.character_id=$2
ON CONFLICT(character_id,resource) DO UPDATE SET generation=excluded.generation,display_name=excluded.display_name,
 state=excluded.state,reason=excluded.reason,active_job_id=NULL,lease_until=NULL,fence=eve_sync_targets.fence+1,failures=0,
 next_due_at=greatest(eve_sync_targets.next_due_at,now()),updated_at=now()
`

type SeedSyncTargetsParams struct {
	DisplayName string
	CharacterID int64
}

func (q *Queries) SeedSyncTargets(ctx context.Context, arg SeedSyncTargetsParams) error {
	_, err := q.db.Exec(ctx, seedSyncTargets, arg.DisplayName, arg.CharacterID)
	return err
}

const setESIRoute = `-- name: SetESIRoute :exec
INSERT INTO eve_esi_routes(route_key,group_name) VALUES($1,$2) ON CONFLICT(route_key) DO UPDATE SET group_name=excluded.group_name
`

type SetESIRouteParams struct {
	RouteKey  string
	GroupName string
}

func (q *Queries) SetESIRoute(ctx context.Context, arg SetESIRouteParams) error {
	_, err := q.db.Exec(ctx, setESIRoute, arg.RouteKey, arg.GroupName)
	return err
}

const setRoleBarrier = `-- name: SetRoleBarrier :exec
UPDATE eve_credentials SET roles_not_before=greatest(now()+interval '5 minutes',$1::timestamptz,
 (SELECT max(expires_at) FROM eve_esi_cache WHERE character_id=$2::bigint)) WHERE character_id=$2
`

type SetRoleBarrierParams struct {
	UntilAt     pgtype.Timestamptz
	CharacterID int64
}

func (q *Queries) SetRoleBarrier(ctx context.Context, arg SetRoleBarrierParams) error {
	_, err := q.db.Exec(ctx, setRoleBarrier, arg.UntilAt, arg.CharacterID)
	return err
}

const setSyncJob = `-- name: SetSyncJob :exec
UPDATE eve_sync_targets SET active_job_id=$2,state='queued',updated_at=now() WHERE id=$1
`

type SetSyncJobParams struct {
	ID          int64
	ActiveJobID pgtype.Int8
}

func (q *Queries) SetSyncJob(ctx context.Context, arg SetSyncJobParams) error {
	_, err := q.db.Exec(ctx, setSyncJob, arg.ID, arg.ActiveJobID)
	return err
}

const setSyncName = `-- name: SetSyncName :exec
UPDATE eve_sync_targets SET display_name=$2 WHERE character_id=$1
`

type SetSyncNameParams struct {
	CharacterID int64
	DisplayName string
}

func (q *Queries) SetSyncName(ctx context.Context, arg SetSyncNameParams) error {
	_, err := q.db.Exec(ctx, setSyncName, arg.CharacterID, arg.DisplayName)
	return err
}

const syncAudit = `-- name: SyncAudit :exec
INSERT INTO eve_sync_audit(user_id,character_id,target_id,action,outcome) VALUES($1,$2,$3,$4,$5)
`

type SyncAuditParams struct {
	UserID      pgtype.UUID
	CharacterID int64
	TargetID    int64
	Action      string
	Outcome     string
}

func (q *Queries) SyncAudit(ctx context.Context, arg SyncAuditParams) error {
	_, err := q.db.Exec(ctx, syncAudit,
		arg.UserID,
		arg.CharacterID,
		arg.TargetID,
		arg.Action,
		arg.Outcome,
	)
	return err
}

const writeESICache = `-- name: WriteESICache :exec
INSERT INTO eve_esi_cache(cache_key,character_id,generation,body,etag,last_modified,expires_at,content_updated_at,page_count) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT(cache_key) DO UPDATE SET body=excluded.body,etag=excluded.etag,last_modified=excluded.last_modified,expires_at=excluded.expires_at,content_updated_at=excluded.content_updated_at,page_count=excluded.page_count,updated_at=now()
`

type WriteESICacheParams struct {
	CacheKey         string
	CharacterID      pgtype.Int8
	Generation       int64
	Body             []byte
	Etag             string
	LastModified     string
	ExpiresAt        pgtype.Timestamptz
	ContentUpdatedAt pgtype.Timestamptz
	PageCount        int32
}

func (q *Queries) WriteESICache(ctx context.Context, arg WriteESICacheParams) error {
	_, err := q.db.Exec(ctx, writeESICache,
		arg.CacheKey,
		arg.CharacterID,
		arg.Generation,
		arg.Body,
		arg.Etag,
		arg.LastModified,
		arg.ExpiresAt,
		arg.ContentUpdatedAt,
		arg.PageCount,
	)
	return err
}
