// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token_observation.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupTokenEvents = `-- name: CleanupTokenEvents :exec
DELETE FROM eve_token_events WHERE id IN (SELECT id FROM eve_token_events WHERE occurred_at<now()-interval '30 days' ORDER BY occurred_at LIMIT 500)
`

func (q *Queries) CleanupTokenEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupTokenEvents)
	return err
}

const insertTokenEvent = `-- name: InsertTokenEvent :exec
INSERT INTO eve_token_events(character_id,generation,outcome,reason,duration_ms)
SELECT c.character_id,c.grant_generation,$1,$2,$3::bigint
FROM eve_credentials c WHERE c.character_id=$4 AND c.grant_generation=$5
`

type InsertTokenEventParams struct {
	Outcome     string
	Reason      string
	DurationMs  int64
	CharacterID int64
	Generation  int64
}

func (q *Queries) InsertTokenEvent(ctx context.Context, arg InsertTokenEventParams) error {
	_, err := q.db.Exec(ctx, insertTokenEvent,
		arg.Outcome,
		arg.Reason,
		arg.DurationMs,
		arg.CharacterID,
		arg.Generation,
	)
	return err
}

const listTokenEvents = `-- name: ListTokenEvents :many
SELECT id,generation,occurred_at,outcome,reason,duration_ms FROM eve_token_events WHERE character_id=$1 ORDER BY id DESC LIMIT 20
`

type ListTokenEventsRow struct {
	ID         int64
	Generation int64
	OccurredAt pgtype.Timestamptz
	Outcome    string
	Reason     string
	DurationMs int64
}

func (q *Queries) ListTokenEvents(ctx context.Context, characterID int64) ([]ListTokenEventsRow, error) {
	rows, err := q.db.Query(ctx, listTokenEvents, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenEventsRow{}
	for rows.Next() {
		var i ListTokenEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Generation,
			&i.OccurredAt,
			&i.Outcome,
			&i.Reason,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenObservations = `-- name: ListTokenObservations :many
SELECT c.character_id,c.state AS credential_state,c.grant_generation,c.scopes,
coalesce((SELECT display_name FROM eve_sync_targets t WHERE t.character_id=c.character_id ORDER BY t.id LIMIT 1),'')::text AS display_name,
o.character_id, o.generation, o.observed_since, o.access_expires_at, o.last_used_at, o.reuse_count, o.last_refresh_attempt_at, o.last_refresh_success_at, o.last_refresh_reason, o.refresh_successes, o.refresh_failures, o.consecutive_failures, o.last_request_at, o.last_request_status, o.last_request_reason, o.network_requests, o.cache_hits, o.rate_limit_waits, o.request_failures FROM eve_credentials c JOIN eve_token_observations o USING(character_id)
WHERE c.character_id>$1 AND ($2::text='' OR c.character_id::text=$2
 OR EXISTS(SELECT 1 FROM eve_sync_targets t WHERE t.character_id=c.character_id AND t.display_name ILIKE '%'||$2||'%'))
AND ($3::text='' OR
 CASE WHEN c.state='reauthorize' THEN 'reauthorize'
 WHEN o.consecutive_failures>0 THEN 'refresh_failed'
 WHEN o.access_expires_at IS NULL THEN 'unknown'
 WHEN o.access_expires_at<=now()+interval '1 minute' THEN 'refresh_due' ELSE 'valid' END=$3)
ORDER BY c.character_id LIMIT 31
`

type ListTokenObservationsParams struct {
	AfterID     int64
	Search      string
	StateFilter string
}

type ListTokenObservationsRow struct {
	CharacterID          int64
	CredentialState      string
	GrantGeneration      int64
	Scopes               []string
	DisplayName          string
	CharacterID_2        int64
	Generation           int64
	ObservedSince        pgtype.Timestamptz
	AccessExpiresAt      pgtype.Timestamptz
	LastUsedAt           pgtype.Timestamptz
	ReuseCount           int64
	LastRefreshAttemptAt pgtype.Timestamptz
	LastRefreshSuccessAt pgtype.Timestamptz
	LastRefreshReason    string
	RefreshSuccesses     int64
	RefreshFailures      int64
	ConsecutiveFailures  int64
	LastRequestAt        pgtype.Timestamptz
	LastRequestStatus    int32
	LastRequestReason    string
	NetworkRequests      int64
	CacheHits            int64
	RateLimitWaits       int64
	RequestFailures      int64
}

func (q *Queries) ListTokenObservations(ctx context.Context, arg ListTokenObservationsParams) ([]ListTokenObservationsRow, error) {
	rows, err := q.db.Query(ctx, listTokenObservations, arg.AfterID, arg.Search, arg.StateFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenObservationsRow{}
	for rows.Next() {
		var i ListTokenObservationsRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.CredentialState,
			&i.GrantGeneration,
			&i.Scopes,
			&i.DisplayName,
			&i.CharacterID_2,
			&i.Generation,
			&i.ObservedSince,
			&i.AccessExpiresAt,
			&i.LastUsedAt,
			&i.ReuseCount,
			&i.LastRefreshAttemptAt,
			&i.LastRefreshSuccessAt,
			&i.LastRefreshReason,
			&i.RefreshSuccesses,
			&i.RefreshFailures,
			&i.ConsecutiveFailures,
			&i.LastRequestAt,
			&i.LastRequestStatus,
			&i.LastRequestReason,
			&i.NetworkRequests,
			&i.CacheHits,
			&i.RateLimitWaits,
			&i.RequestFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observeTokenRefresh = `-- name: ObserveTokenRefresh :exec
UPDATE eve_token_observations SET observed_since=coalesce(observed_since,$1::timestamptz),
last_refresh_attempt_at=$1,last_refresh_reason=$2,
last_refresh_success_at=CASE WHEN $3::boolean THEN clock_timestamp() ELSE last_refresh_success_at END,
refresh_successes=refresh_successes+CASE WHEN $3 THEN 1 ELSE 0 END,
refresh_failures=refresh_failures+CASE WHEN $3 THEN 0 ELSE 1 END,
consecutive_failures=CASE WHEN $3 THEN 0 ELSE consecutive_failures+1 END
WHERE character_id=$4 AND generation=$5
`

type ObserveTokenRefreshParams struct {
	AttemptedAt pgtype.Timestamptz
	Reason      string
	Success     bool
	CharacterID int64
	Generation  int64
}

func (q *Queries) ObserveTokenRefresh(ctx context.Context, arg ObserveTokenRefreshParams) error {
	_, err := q.db.Exec(ctx, observeTokenRefresh,
		arg.AttemptedAt,
		arg.Reason,
		arg.Success,
		arg.CharacterID,
		arg.Generation,
	)
	return err
}

const observeTokenRequest = `-- name: ObserveTokenRequest :exec
UPDATE eve_token_observations o SET observed_since=coalesce(observed_since,clock_timestamp()),
last_request_at=clock_timestamp(),last_request_status=$1,last_request_reason=$2,
network_requests=network_requests+$3::bigint,cache_hits=cache_hits+$4::bigint,
rate_limit_waits=rate_limit_waits+$5::bigint,request_failures=request_failures+$6::bigint
WHERE o.character_id=$7 AND o.generation=$8
AND EXISTS(SELECT 1 FROM eve_credentials c WHERE c.character_id=o.character_id AND c.grant_generation=o.generation AND c.state<>'reauthorize')
`

type ObserveTokenRequestParams struct {
	HttpStatus  int32
	Reason      string
	Network     int64
	CacheHit    int64
	Limited     int64
	Failed      int64
	CharacterID int64
	Generation  int64
}

func (q *Queries) ObserveTokenRequest(ctx context.Context, arg ObserveTokenRequestParams) error {
	_, err := q.db.Exec(ctx, observeTokenRequest,
		arg.HttpStatus,
		arg.Reason,
		arg.Network,
		arg.CacheHit,
		arg.Limited,
		arg.Failed,
		arg.CharacterID,
		arg.Generation,
	)
	return err
}

const observeTokenUse = `-- name: ObserveTokenUse :exec
UPDATE eve_token_observations SET observed_since=coalesce(observed_since,clock_timestamp()),
access_expires_at=$1,last_used_at=clock_timestamp(),reuse_count=reuse_count+$2::bigint
WHERE character_id=$3 AND generation=$4
`

type ObserveTokenUseParams struct {
	ExpiresAt   pgtype.Timestamptz
	Reused      int64
	CharacterID int64
	Generation  int64
}

func (q *Queries) ObserveTokenUse(ctx context.Context, arg ObserveTokenUseParams) error {
	_, err := q.db.Exec(ctx, observeTokenUse,
		arg.ExpiresAt,
		arg.Reused,
		arg.CharacterID,
		arg.Generation,
	)
	return err
}

const resetTokenObservation = `-- name: ResetTokenObservation :exec
INSERT INTO eve_token_observations(character_id,generation,observed_since,access_expires_at)
SELECT c.character_id,c.grant_generation,clock_timestamp(),$1::timestamptz FROM eve_credentials c WHERE c.character_id=$2
ON CONFLICT(character_id) DO UPDATE SET generation=excluded.generation,observed_since=excluded.observed_since,
access_expires_at=excluded.access_expires_at,last_used_at=NULL,reuse_count=0,last_refresh_attempt_at=NULL,last_refresh_success_at=NULL,
last_refresh_reason='',refresh_successes=0,refresh_failures=0,consecutive_failures=0,
last_request_at=NULL,last_request_status=0,last_request_reason='',network_requests=0,cache_hits=0,rate_limit_waits=0,request_failures=0
`

type ResetTokenObservationParams struct {
	ExpiresAt   pgtype.Timestamptz
	CharacterID int64
}

func (q *Queries) ResetTokenObservation(ctx context.Context, arg ResetTokenObservationParams) error {
	_, err := q.db.Exec(ctx, resetTokenObservation, arg.ExpiresAt, arg.CharacterID)
	return err
}

const tokenObservationExists = `-- name: TokenObservationExists :one
SELECT EXISTS(SELECT 1 FROM eve_credentials WHERE character_id=$1)
`

func (q *Queries) TokenObservationExists(ctx context.Context, characterID int64) (bool, error) {
	row := q.db.QueryRow(ctx, tokenObservationExists, characterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
